### ISSUE TITLE
Search of views through predefined keywords must be processed with "AND" and not with "OR" in some cases.

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#134]
Search process of views through pre-defined keywords must be arranged differently: 

"OR" must be used when selecting more items within the same group of items (e.g. environment and social in classes must result in data from both categories being shown) 

"AND" must be used when combining choices of items from different group of items (e.g. environment in classes and pollution in collections must result in all environmental data that are in colelctions. Not in the totality of environmental data and pollution data).

**Comment by thomaspiller** [comment]
As it's the current behavior of the filters, I close this issue.
