### ISSUE TITLE
Titles and abstract should be selectable for copy paste and click on hyperlinks

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#169]
When a user needs to copy a title, something from an abstract or the entire text that is available from the views list, he cannot do it without accessing the view's configuration window.
Not being able to select text from the views' list also makes url links in the abstract to be unaccessible. The links cannot be clicked at the present state.
This improvement will also help all users with publisher rights and, especially, us that keep track of published items on googlesheet.

![abstract and title cannot be selected](https://user-images.githubusercontent.com/30286565/34418699-a7d04838-ebff-11e7-8587-281916481bb0.JPG)

**Comment by thomaspiller** [comment]
> Not being able to select text from the views' list also makes url links in the abstract to be unaccessible. The links cannot be clicked at the present state.

As this is no longer the case, is this issue still relevant?

**Comment by antobenve** [comment]
Yes, it is true that hyperlinks are fully functional now. However, IMHO, the issue is still relevant because it is not possible to copy abstract and title of a view unless one does it from the configuration window of the view.

**Comment by antobenve** [comment]
The issue is closed because the item is reported in the list of improvements of issue #446
