### ISSUE TITLE
Raster rendering on map causes black rectangles to appear around the image depending on zoom levels

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#175]
When a raster is visualized it sometimes happens that black areas are shown around it depending on the zoom. Changing zoom level cause them to appear, change position or disappear.
Here 4 pictures at different zooms showing that the black area appears when the zoom increases, it moves, and finally disappear when zoom is higher.
![raster black areas_1](https://user-images.githubusercontent.com/30286565/35100047-95e6cba4-fc5a-11e7-9769-8a7b08ab8106.JPG)
![raster black areas_2](https://user-images.githubusercontent.com/30286565/35100049-9828c020-fc5a-11e7-99cd-0669e971824b.JPG)
![raster black areas_3](https://user-images.githubusercontent.com/30286565/35100050-99b55cb4-fc5a-11e7-9752-0ca16fe94dce.JPG)
![raster black areas_4](https://user-images.githubusercontent.com/30286565/35100053-9b043dce-fc5a-11e7-8d69-42e023f6b547.JPG)

**Comment by thomaspiller** [comment]
I'm not sure that it is related to MapX. Something similar happened to me while displaying data fetched from a GeoServer. It was a cache related issue.
