### ISSUE TITLE
Source schema : title in dropdown menu does not update after name change in form.

### ISSUE THREAD

**Issue by fxi** [unep-grid/map-x-mgl#18]
### Expected Behavior

The name of the source should change after saving the source meta data

### Current Behavior

The title is not updated after the text is updated in form

### Steps to Reproduce

1. Edit a source
2. Change the title
3. Save the source

**Comment by antobenve** [comment]
The problem still exist with "Edit source metadata" in V5

**Comment by thomaspiller** [comment]
After a bit of testing, this issue seems to be solved. Reopen it if you encounter this problem again.
