### ISSUE TITLE
Attribute window variables are listed in alphabetical order rather than order indicated in the configure view window

### ISSUE THREAD

**Issue by davidedwardjensen** [unep-grid/map-x-mgl#181]
Hi

The variables in my attribute window are listed in alphabetical order rather than the order that I indicate when I configure the view.

**Comment by fxi** [comment]
fixed in 5e3d4a2 (available in /test)

**Comment by fxi** [comment]
Does not work : order is not preserved between ui and view object.

**Comment by thomaspiller** [comment]
Solved. The order of the attributes defined in the edit panel is kept in the pop-up.
