### ISSUE TITLE
Transparency values for colors in legend not matched to point colors on map

### ISSUE THREAD

**Issue by davidedwardjensen** [unep-grid/map-x-mgl#182]
There seems to be a mismatch between the values for the colors on the legend and the same colors used on the map itself.  Here is a screen shot showing the legend colour for red (RGB values 247 211 208) versus red on the map itself (RBG values 221 86 77). These should obviously be the same.

![image](https://user-images.githubusercontent.com/17933528/35588492-1bd4d8f0-0601-11e8-9cb1-57e7257e8338.png)

![image](https://user-images.githubusercontent.com/17933528/35588479-109b9b36-0601-11e8-8565-127158c31f00.png)

**Comment by antobenve** [comment]
@thomaspiller , do you think this is still unsolved? It seems solved to me. Transparency is well displayed in the legend as on map.

**Comment by thomaspiller** [comment]
Yes, I made a few tests and it seems solved to me too.
