### ISSUE TITLE
Have the possibility to select WLD source layers when creating a view in a country for overlapping issues.

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#192]
While creating an overlap view:
I cannot create a view that shows the intersection between a global dataset (published in WLD) and a local dataset (that was published in a country) because the view configuration window doesn't give access to the source layers published out of the country where I am creating the view.

Ex: If a create a country view that is associated to the local source layer I won't have the possibility to select the WLD source layer as a mask. On the other hand, if I create a WLD view that is associated to the global source layer, I won't have the possibility to select the local source layer as a mask.

Either one of the cases or both in the view configuration window should offer the availability of all source layers of the platform, indipendently from the country where they were published in.

**Comment by thomaspiller** [comment]
Not relevant anymore as we changed the way we organize the data in MapX from countries to projects.
