### ISSUE TITLE
Correcting data in dashboards

### ISSUE THREAD

**Issue by davidedwardjensen** [unep-grid/map-x-mgl#198]
One of the most common feature requests that came from our dashboards for Iraq and Ivory Coast by the programmme managers was how to make changes to data points within a dash board as well as add new ones. This also came from government focal points. This sounds like a feature we should consider going forward as we also develop the Kobo application.

**Comment by thomaspiller** [comment]
Publishers can edit their datasets using QGIS or any PostgreSQL client. This solution should meet this demand.
