### ISSUE TITLE
howto : heatmap

### ISSUE THREAD

**Issue by fxi** [unep-grid/map-x-mgl#203]
How to create heatmaps in mapx : 

![image](https://user-images.githubusercontent.com/1196833/36435245-6e81d8b2-1661-11e8-846e-f2bcac8f0dc8.png)

1. Create a vector view
2. Set title, abstract, source and attributes ( and alternative attributes )
3. In edit style, add a json like this in `Custom style` (here, we weight on 'fatalities'):

```json
{
  "enable": true,
  "paint": {
    "heatmap-weight": [
      "interpolate",
      [
        "linear"
      ],
      [
        "get",
        "fatalities"
      ],
      0, 0.1,
      1, 0.5
    ],
    "heatmap-intensity": [
      "interpolate",
      [
        "linear"
      ],
      [
        "zoom"
      ],
      0, 1,
      9, 3
    ],
    "heatmap-color": [
      "interpolate",
      [
        "linear"
      ],
      [
        "heatmap-density"
      ],
      0.1,"rgba(107, 0, 71, 0.1)",
      0.2,"rgba(163, 0, 109, 1)",
      0.7,"rgba(250, 150, 0, 1)",
      0.8,"rgba(255, 231, 46, 1)",
      1,"rgba(255, 247, 184, 1)"
    ],
    "heatmap-radius": [
      "interpolate",
      [
        "linear"
      ],
      [
        "zoom"
      ],
      0, 2,
      9, 20
    ],
    "heatmap-opacity": [
      "interpolate",
      [
        "linear"
      ],
      [
        "zoom"
      ],
      0, 1,
      20, 1
    ]
  },
  "layout": {},
  "filter": ["all"],
  "minzoom": 0,
  "maxzoom": 22,
  "type": "heatmap"
}

```

Based on example : https://www.mapbox.com/mapbox-gl-js/example/heatmap-layer/
Doc : https://www.mapbox.com/mapbox-gl-js/style-spec/#layers-heatmap

**Comment by fxi** [comment]
How to make legend works in custom style

### Dummy legends on any attribute : 
<img width="656" alt="pastedgraphic-2" src="https://user-images.githubusercontent.com/1196833/36682522-977ca12a-1b1b-11e8-8689-7353723a152b.png">

### Filters data values : 

![mx_custom_style_legend_filter](https://user-images.githubusercontent.com/1196833/36682561-b36c1bae-1b1b-11e8-8f8f-a658a1421755.gif)

**Comment by thomaspiller** [comment]
The content of this issue has been moved to the wiki.
