### ISSUE TITLE
Namibia doesn't exist as country

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#207]
When searching for Namibia the result is null. 
When double clicking in Namibia the country selected is blank.

**Comment by PierreLacroix** [comment]
@antobenve can you close this one?

**Comment by thomaspiller** [comment]
@PierreLacroix @antobenve Namibia is still not in the list of countries.

**Comment by antobenve** [comment]
It is true that the issue is not so relevant anymore for the way MapX manages the projects. @PierreLacroix should I close it?

However, Namibia can't still be selected as country to clip a dataset when downloading a layer, performing a overlap analysis, or configuring a project. I don't understand the reason for this because GAUL has Namibia's entry in its table. @thomaspiller , any thoughts?
