### ISSUE TITLE
Country selection and language menus not appearing correctly in safari on iPad 2

### ISSUE THREAD

**Issue by davidedwardjensen** [unep-grid/map-x-mgl#211]
The new country selection menu and language menu do not display correctly on safari / iPad 2. The options never appear. 

[edit]
- Formating

**Comment by fxi** [comment]
Could you please add the version of safari mobile you are using ?

**Comment by thomaspiller** [comment]
Since no feedback has been provided for over a year and MapX has much evolved since then, I close this issue.
