### ISSUE TITLE
Custom code OnClose is not always triggered – maybe in dashboards and custom style too.

### ISSUE THREAD

**Issue by fxi** [unep-grid/map-x-mgl#223]
Two main bugs happen in custom code view. They produce cascading issues in the whole app:

- When a view is open after a custom-code view was already open, the custom-code view is reevaluated from scratch.
- When closing a custom-code view, the onClose is not triggered, which could lead to a huge mess if onClose is meant to remove listeners.

**Comment by fxi** [comment]
@thomaspiller Is it still an issue ?

**Comment by thomaspiller** [comment]
I just did a little round of testing and I think these bugs have been fixed.
