### ISSUE TITLE
How to handle badly formatted HTML from story map slides ?

### ISSUE THREAD

**Issue by fxi** [unep-grid/map-x-mgl#230]
## Description of a possible issue
- When the visual editor is launched , a cog logo appears and the editor toolbar does not show up.
- An error is visible in the console:
```js
Error: Transition is undefined: ...
```
- Other "it does not work after I've made a manual operation" errors.

## Probable cause
Badly formatted HTML in a slide

## How to avoid it
Use the visual editor and don't modify HTML manually.

## How to solve an issue

For large story map JSON, it could be difficult to detect errors simply by reading the code. A solution is to use a HTML validation tool, such as the one available in [jsfiddle.net](https://jsfiddle.net/).

MapX also has an integrated validator, but it's turned off at the moment. So, you will have to use an external tool for now.

1. Copy the JSON code from the story map editor
2. Open a javascript console
3. Paste the JSON in a variable. e.g. 
```js 
var story={ "steps": []} 
```
4. Using a nested loop, extract the HTML for the desired language:
```js
var txt = "";
story.steps.forEach(
  function(s) {
    s.slides.forEach(function(sl) {
      txt = txt + sl.html.en
    })
  })
```
5. Copy the result. In Chrome interactive console, the command `copy(txt)` will copy the result in your clipboard.
6. Paste the result in [jsfiddle.net](https://jsfiddle.net/), under the HTML section
7. Now you can see issues visually. E.g. 
![image](https://user-images.githubusercontent.com/1196833/38861742-92971480-4233-11e8-927b-d75c61aa8c69.png)

**Comment by antobenve** [comment]
Thanks! Interesting way to detect errors!

**Comment by fxi** [comment]
Yep. I will enable the Ace plugin to do it in MapX directly, this method is really sketchy.

**Comment by thomaspiller** [comment]
Le contenu de cette issue a été déplacer dans le wiki.
