### ISSUE TITLE
Enable set of method for cross-origin communication 

### ISSUE THREAD

**Issue by fxi** [unep-grid/map-x-mgl#233]
#### Parent -> iframe -> parent

MapX should have a minimal interface between a parent window when it's embedded in an iframe. Here is a list of case that could be implemented.

- [x] Check which current user is logged in.  `sendMessage("getCurrentUser")` result : `{id:1,guest:false}`;
- [x] Get a list of project
- [x] Get a list of view 
- [x] Set the current project
- [x] Set some UI features : hide buttons, show panels, etc.

### Example: get user id 
![mx_parent_iframe_com](https://user-images.githubusercontent.com/1196833/40473675-26640152-5f3d-11e8-9ba5-8d3a2448cd5b.gif)

**Comment by thomaspiller** [comment]
See MapX SDK.
