### ISSUE TITLE
"Share this view" and "metadata information" buttons missing for custom code views

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#239]

**Comment by thomaspiller** [comment]
The button to access the metadata panel is now available.
The one for sharing the view is still missing.

**Comment by antobenve** [comment]
@thomaspiller , a nice solution would be the creation of a field in the configuration window where an external url can be placed, as for raster views.

**Comment by antobenve** [comment]
This is solved in v.1.6.23. The issue is closed.
