### ISSUE TITLE
Change MAP-X to MapX in emails from bot@mapx.org

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#241]
Current text and subject of emails received when requesting log in is still showing the old name of the application.

**Comment by thomaspiller** [comment]
![capture](https://user-images.githubusercontent.com/19908801/42929121-6cf632fc-8b39-11e8-953c-51caa952c677.JPG)

**Comment by antobenve** [comment]
Still an issue...

**Comment by antobenve** [comment]
FCC: imap://antonio.benvenuti%40unepgrid.ch@mail.infomaniak.com/Sent
X-Identity-Key: id1
X-Account-Key: account1
From: Antonio 
Subject: Out of office
Openpgp: preference=signencrypt
Autocrypt: addr=antonio.benvenuti@unepgrid.ch; keydata=
 mQENBFyq8qEBCADGPSsONvTI++8Vp7YlTgpAYyyKVw80JCeqL8qRrrFdxZ4+GYlJGyHOD3/I
 Nbey4WK/mLMr9nz4gdVToqwRWViqjygfU77kx5/WtBT+Y9b3IxvEXj68wDhJEW2yZsuqYB27
 WsFNY587LP0q3rKpUO1sh2XIluZCKjV7j1KG4sph/6njRQ36HotmWkJapynTbxef6IQytde2
 zeeeyu82prydpzyurFXd2QduY7Y/otHs5QbepiIIjruecUZir9WgxhXo0FvsFHnQUNP+ePp+
 cQ5/fhpfCAcX6NU6gzFY5wN/g2B8PdN1tg9MT1tpdfHg5vdUdkc4ByZSgp6sLFmKYUvxABEB
 AAG0J0FudG9uaW8gPGFudG9uaW8uYmVudmVudXRpQHVuZXBncmlkLmNoPokBVAQTAQgAPhYh
 BHnHPW6lf0hHluvrMAtkWNW186h+BQJcqvKjAhsDBQkB4TOABQsJCAcCBhUKCQgLAgQWAgMB
 Ah4BAheAAAoJEAtkWNW186h+V/EH/i3+f9VdqiFhr77AdbPGxVtEHEECVVjYQIMNfExoZ3X5
 xaUaBGTc4FYsIey7Zv5MdcZR0WQy1lc7WT1ydYX9BBFGq33IGz+IKypWCWfUGhMLu/P2MyYP
 ZnpeL1ekoK4Kyb2WM+y1f+ccS2uUdZ3QjtW89UugEZ6IiyyNKacN2H7LGL/f7d0yRgWiO2This is an OpenPGP/MIME encrypted message (RFC 4880 and 3156)
--aUBqyQZMRMCLAepLQUtnBnuK0g7HUVI2a
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification

Version: 1

--aUBqyQZMRMCLAepLQUtnBnuK0g7HUVI2a
Content-Type: application/octet-stream; name="encrypted.asc"
Content-Description: OpenPGP encrypted message
Content-Disposition: inline; filename="encrypted.asc"

-----BEGIN PGP MESSAGE-----

hQEMAzDSLnyi6ICsAQf/S4FTEZG8VcSLL8UkkImfsXTRm4kd0kBj/h6natVjC6PH
J8DWaZZy5t0cstbU7fV7H9DdM1Qv9NVsTtgSlsXT8iqrWTTYxUHn2ytBtz+C1cn4
t+0xzxD1/onGdGsaeLGFjYifcoURiFQWa7lkXKs70KTIR+lXZQlSqfpHGNnUJ84c
N5e6cj1L3Eltvf6TzrDhroDr69H6V6Bofqzz3rN8aj//jkhLp55XGZiu5H5UixU4
odFKbpjkQY0Zow9K83g0EXxP2Sz8TkoYInlqDUR96MN6pTDrl+W35LPaPVUGvH63
O7rLuvY//IPTzNfa3NdffAFdVNWQWcmNQr3p233M2NLpAdResXBR9OJ3DEey1bMs
iLmYfvTOTunp1paqpAn5v8f/WEo5KCaPMexMrTCAYrvtUZre5dCJ3FQVHaUhhLam
LGaevcqgjinh1Zk6KdqF3V4INgkNMKmgxdXTcPWhqaNuYF9odNLHg7syn3NwNisv
7LMUjfQpX47J5HWeMAOK23YWdFALatjRiZXKMBb/m8EzTOvV2FlN6mDmsIS5XX5Y
rKNIFKHVGmGPIpah64rPmZfjjo2v12jTk3EYC1sUOyO8tgwQPVAv6vM5HQ4zLpes
0EzSDD3CkDVFPs+Vz881vJwql6rEJRf4n7DRNt0hPDTy/qpDb/y36suV49bXNJNy
sYTQZoBS5zGTmJq3pe8Y0SStXdDTWimzynbRlCJvLdsyf0wLAUIVcH6rSdb68UWX
hVD0W38FWW/vplJMlB0nGn8TUboLoYezUjfHIOtVFOCAuI7kJSnH3exoImF/HX7D
cKWQkGFrQy3rectEGpR2STnQMsGZXrhSQKPUzW6YlDq/2ez6Zz1k1NcwJEjNIEQ0
AWxplQA3W39iec3epxAzTZvw2+9ZpyvUsqW7W2PyEzzG/2gEN0qSuRM9mFueLGPE
lZwUuf3O2dwiqma/eDSZlbARl8UQsr/LN4DMBxImd9kejSQ7LcXLerncsjqN/IOG
f1el/ZB5LnZ7kSBdy2/BZx4WpAOQE8oZ02B5kiHFxpydi4jRmFABqQ==
=zqZg
-----END PGP MESSAGE-----

--aUBqyQZMRMCLAepLQUtnBnuK0g7HUVI2a--
