### ISSUE TITLE
Only one legend downloaded for multiple view screenshot 

### ISSUE THREAD

**Issue by tdearden** [unep-grid/map-x-mgl#250]
### Expected Behavior
When taking a screenshot of multiple views, the output should include all of the legends from views that are selected or visible on the map. 

### Current Behavior
When taking a screenshot of multiple views, the "map" PNG and PDF output will show all of the views but only one legend (belonging to the view from which the user clicked "take a screenshot"). 

### Possible Solution
Pop-up asking if you want to also download the legends for all views activated on the screen. Could prompt user to click "Filter activated views".

### Steps to Reproduce

1. Activate multiple views 
2. Click take a screenshot

**Comment by thomaspiller** [comment]
The screenshot tool is no more available in MapX.
It is replaced by the new map composer.
