### ISSUE TITLE
Allow administrators to disable the membership request option for their project(s)

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#251]
For now, a user can request to be a member of a project from the drop-down list by clicking on the _join button_ (see below).
![image](https://user-images.githubusercontent.com/19908801/42865588-6c4c06ee-8a6a-11e8-83bf-37171ba86609.png)
All public projects are listed in that drop-down list therefore, a user can request membership to all of them.
As an administrator of a project, it would be nice to have the option to disable that membership request feature.

**Comment by fxi** [comment]
Added in 1.5.52, available to test.

**Comment by thomaspiller** [comment]
Tested in MapX v1.5.53.1 (local), everything seems to work as expected.
