### ISSUE TITLE
Abstract and legend: expanded or collapsed

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#263]
For the moment, the legends and abstracts appear entirely by default mode (and it should remain like this). However, it is complicated to have an overview of the view menu when several layers are activated at the same time. Therefore, there should be an option to collapse entirely the abstract **and/or** (both independently) the legend if necessary.

**Suggestion**:
_Position 1 (default)_:
![abstract legend position 1](https://user-images.githubusercontent.com/25179050/43400751-d060a0b0-940e-11e8-8df2-94e6df50b492.png)

_Position 2 (if necessary)_:
![abstract legend position 2](https://user-images.githubusercontent.com/25179050/43400774-ddcf870c-940e-11e8-81f7-349d0e29829a.png)

**Comment by MarionPlanque** [comment]
I bring this topic back as a **feature request**: it would be nice to have the possibility to expand/collapse both legends and abstracts if wanted/necessary (could be quite useful when multiple layers are opened at the same time...)

**Comment by fxi** [comment]
You are right, this was the case before, but some users were not satisfied with an intricate sequence required to display basic abstract. I will find a compromise in the next iteration.

**Comment by antobenve** [comment]
I'm closing this old issue as the abstracts are shown on a limited space that can be scrolled to display the hidden text.
