### ISSUE TITLE
"Join sandbox" link sends back automatically the MapX interface

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#268]
From the UN Biodiversity Lab, once the user asks to join a sandbox and the validation email is sent, the link takes the user to the sandbox in **MapX**, not into the biolab. 
If possible, this needs to be re-directed so the user lands back in the actual sandbox environment within the biolab interface.
_Solution to be discussed with the developer_

**Comment by antobenve** [comment]
Fixed

**Comment by MarionPlanque** [comment]
Many thanks Antonio; where can I test this? I tested it directly on UN Biodiversity Lab but it didn't work, I guess it's because nothing has been pushed on the current MapX version; but then I can't test it on the MapX test version because the link is not integrated in the UNBiolab (plus the link in the biolab is still  mvp.app.mapx...)

**Comment by antobenve** [comment]
My bad Marion. I guess I was a bit tired yesterday evening. This problem is not fixed. 
What is fixed is the problem occurring when someone creates a project and loads it --> it seemed to me that the person was previously redirected to MapX out of unbiodiversitylab.org but I may be wrong. In any case I re-open the issue.

**Comment by antobenve** [comment]
@fxi, do you have any solution on this problem? It seems to me something very complicated as we don't have control over the host-page where the i-frame is embedded (the two don't talk to eachother). Therefore I don't think it is possible to have a specific link to redirect the person to the right MapX project hosted as an i-frame within a web page like unenvironment.org. Please let me know if the issue must remain open or not.

**Comment by MarionPlanque** [comment]
@antobenve If we don't have a solution for that pb for the moment, I think we should probably find a way to include a guidance in the email that the user will receive to indicate they should go back to the un bio lab webiste (the general one) and not the MapX one. But how to keep this guidance general enough and not targeting specifically the UN Bio lab? I need to think about this, it is tricky... Any help in thinking about this with me is welcomed :)
