### ISSUE TITLE
Autotranslate widget

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#269]
Currently, the language plugin only works for English and French only. We should remove other languages until they are ready.
Also, we should test an autotranslate widget **_in_** the MapX platform, like in any other website so that users speaking various languages (out of English and French) can understand the content of the data layers.

**Comment by fxi** [comment]
The map main labels are all translated, together with all country names in the UI. The only language that is not supported at all, and could be removed is Bengali. Not sure why it's there. 
Then, all the dictionaries are available for free to be completed in this repository. Instead of removing those languages, we should add more of them and invite community to contribute to this project. 
And automatic translation is a very, very, very bad idea : it will never happen, sorry.

**Comment by PierreLacroix** [comment]
Translation will be done in a few weeks, so it is wiser indeed to wait for a translation than to remove and put back.
For what concerns the automatic translator it is not the role of the dev team to say that this will never happen (the client will have the final decision), but it is its role to indicate why it is a very bad idea. 
1) I have never seen SDIs where layers titles have been translated
2) I have tested Google Translate on a few dozens of titles, from English to French. The results is sometimes not so bad and indicative, sometimes ugly. Units are not always translated (e.g. km/h), and other issues
3) translation of the abstract is approximative and can be measleading, especially when they are long or when there is some scientific background where all words have been chosen very precisely
4) other translators should be tested by the person who posted this issue. Some of them have been improved a lot recently

**Comment by MarionPlanque** [comment]
@PierreLacroix Well noted, I'll make some tests with various translators. I don't really know how it will look like, as you said some things may look very ugly then, but it should be ugly as well using Google translate... I'll make a couple of tests and let you know how it goes

**Comment by fxi** [comment]
@PierreLacroix : I know this could seems strange to some people, but as a dev team – as of today, composed of myself only – we have to make sure that this kind of tools never comes to our application. As it could violate present or future confidentiality rules in MapX, and possibly some copyright. Using automatic translation tools, you literally give all the text content to a company that is not well known for respecting privacy or working transparently. So, it's just not a question about client wishes, feasibility and translation quality : there is a strong technical and legal component here. 

@MarionPlanque, don't waste your time with that, and learn how to contribute to the MapX translation; I've made a little guide in the wiki : https://github.com/fxi/map-x-mgl/wiki/How-to-contribute. You can also contribute to the wiki itself by providing more in-depth explanation for non-technical person, once you have grasped it.

**Comment by PierreLacroix** [comment]
OK if there are confidentiality issues I agree
