### ISSUE TITLE
Wrong views count 

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#278]
@fxi  In this post, a 'shared' view (story map or vector view) refers to the way through the **button 'share this view'** in the view menu (the one that allows sharing a hyperlink), then '**Share in another project**' --> 'Add the view to another project'

_If_:
1) scenario 1:
- a **vector view** is created in a project A
- it is shared in a project B
- the **project** A is deleted
2) scenario 2:
- a **vector view** is created in a project A
- it is shared in a project B
- the original **vector view** in the project A is deleted
3) scenario 3:
- a **story map** is created in a project A
- it is shared in a project B
- the original **story map** in the project A is deleted
4) scenario 4
- a **story map** is created in a project A
- it is shared in a project B
- the **project** A is deleted

_Then_:
The vector view/story map no longer appears in the project B, BUT in the window listing all the projects, the vector view/story map **is counted in the number of views available**:

(in this photo, there are 3 views in my project whereas the project window informs me that there are 5 of them; the two extra ones have been added when I shared views in this project for bug testing purposes but haven't disappeared when I deleted them)
![2018-08-07_180829](https://user-images.githubusercontent.com/25179050/43788121-f0333c7c-9a6c-11e8-93da-0e170d80ffd2.png)

More details about the bug:
(In the situations listed above) If the views are shared using the **configuration button** then **'Other projects where the view is visible'**,  then the view count is exact: it automaticaaly updates and delete the view that was shared.

**Comment by antobenve** [comment]
I cut part of the text on security information about deleting projects with shared views and views that are shared with other projects in a separated issue #287.

**Comment by MarionPlanque** [comment]
The projects no longer display the number of views, so I guess this is now off-topic
