### ISSUE TITLE
Data integrity entry descriptions

### ISSUE THREAD

**Issue by scabecks** [unep-grid/map-x-mgl#284]
There needs to be a short description of what the possible entries mean withing the data integrity input form in source metadata (e.g., what do the possible values of 0, 1, 2, or 3 indicate). As a simple way I would recommend something like: "Evaluation of the data integrity: 0 - does not meet criteria; 1 - partially meets criteria; 2 - mostly meets criteria; 3 - fully meets criteria" or something like that.

**Comment by antobenve** [comment]
#257

**Comment by antobenve** [comment]
Hi @scabecks, can you close the issue please? The bug has been solved meanwhile. Thanks
