### ISSUE TITLE
Edit source form : multiple item should be visible in selection box.

### ISSUE THREAD

**Issue by fxi** [unep-grid/map-x-mgl#3]
### Expected Behavior

In edit sources, multiple source item should appear.

### Current Behavior

Only one source item is visible.

**Comment by antobenve** [comment]
@fxi is this to be closed? I'm not sure what you meant when you opened the issue over 1 year ago.

**Comment by thomaspiller** [comment]
I close this one as it hasn't had any activity for almost 3 years.
