### ISSUE TITLE
Feature request: have a circle (or arrow) automatically draw on a view to show relevant feature (important within a story map)

### ISSUE THREAD

**Issue by nicolasray** [unep-grid/map-x-mgl#30]
For the circle, or a simple line, or whatever form, I wonder whether the solution is with the "Animate a line" example of Mapbox GL/JS: 

[https://www.mapbox.com/mapbox-gl-js/example/animate-a-line/](https://www.mapbox.com/mapbox-gl-js/example/animate-a-line/)

We could simply circle the area of interest to look at. This could mean doing an ad-hoc addition in the code of the story map, but this is worth it for some our our future key story map.

**Comment by fxi** [comment]
Thanks.

The example you have mentioned shows a method to update a LineString geojson source, using time steps. You want to animate something ? Using what, time or scroll ? Totally doable and quite simple.

What is complex is how the story map creator will interact with this thing: create, update, edit, delete.

Can you describe briefly how do you see each of those parts ?
