### ISSUE TITLE
Upload module glitches

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#301]
- [x] Once the upload is done, MapX needs to be reloaded to have access to the new source.
- [x] Upload via drag'n'drop: the name specified by the user in the upload panel is not preserved. The file name (without its extension) is used instead.
- [ ] ~Errors explaining the problem should be displayed in the upload panel in the following cases:~
~1) when the source is uploaded with the same name of an existing one~
~2) when the spatial reference system of the source is not supported.~
~Currently, the importation process to the db gets stuck after the upload.~ _(not relevant anymore because of the input SRS option in the upload process)_
```
POST https://api.mapx.org/upload/vector/ 500 ()
VM274:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at n (common-d664964dee009e5c4cb2.bundle.js:39)
    at g (common-d664964dee009e5c4cb2.bundle.js:39)
    at Object.onMessage (common-d664964dee009e5c4cb2.bundle.js:39)
    at XMLHttpRequest.e.xhr.onreadystatechange (common-d664964dee009e5c4cb2.bundle.js:39)
n @ common-d664964dee009e5c4cb2.bundle.js:39
g @ common-d664964dee009e5c4cb2.bundle.js:39
onMessage @ common-d664964dee009e5c4cb2.bundle.js:39
e.xhr.onreadystatechange @ common-d664964dee009e5c4cb2.bundle.js:39
XMLHttpRequest.send (async)
g @ common-d664964dee009e5c4cb2.bundle.js:39
t.sendData @ common-d664964dee009e5c4cb2.bundle.js:39
o @ common-d664964dee009e5c4cb2.bundle.js:39
n.on @ common-d664964dee009e5c4cb2.bundle.js:39
```

**Comment by fxi** [comment]
Is that still an issue ?

**Comment by thomaspiller** [comment]
Yes, it is and the name specified by the user is not preserved.

**Comment by thomaspiller** [comment]
The first point affects both upload methods, the second only the drag'n'drop.
