### ISSUE TITLE
Make possible to forbid admins of a project to change its title

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#303]
For formal projects such as the national-projects of the UNBiodiversityLab it is necessary that the future admins of those projects don't change their tittle for two reasons:
- because, currently, the projects that are shown in the projects' list are filtered by their title (showProjectListByTitle=UNBiodiversityLab);
- because the naming of the project must remain standard while we need to give admin rights to external people.

Training users involves a lot of "please don't change the title of the project when you will be the administrator" which is not safe for us.

**Comment by fxi** [comment]
I think this is an x/y problem here.

x = Changing a project title produce change in an host app
y = Solution to x : avoid changing title, report a issue on github

The correct solution would be to add a "label" to projects. 

So, the request would be  showProjectByGroupLabel = MX-AODE-ADsS-VPO-12n

Or, as already discussed in Slack, using sub-project would solve this : 
```js
[
  {
    "id": "mx-asda-adse",
    "public":true,
    "title": "UNBiodiversityLab",
    "subproject_of": null,
    "admins": [
      1
    ]
  },
  {
    "id": "mx-xkcl-poadn",
    "title": "Sierra-Leone",
    "subproject_of": "mx-asda-adse",
    "admins": [
      17,
      1
    ]
  },
  {
    "id": "mx-flari-laos",
    "title": "My secrete sub-project",
    "subproject_of": "mx-asda-adse",
    "admins": [
      1
    ]
  }
]
```

 That would be more future proof, than an arbitrary limitation or random labeling.

**Comment by antobenve** [comment]
Either cases it would solve the situation. Especially the subprojects will be safer.

**Comment by antobenve** [comment]
I'm closing it as it is not a priority currently. The issue will be reopen in the future if relevant again.
