### ISSUE TITLE
Allow to use national boundary of single country for all clipping processes

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#308]
This issue is about the **clipping process** of global datasets by country admin boundaries.

Currently we are trying to have the rights to redistribute the UN admin boundaries.

What is required by the users of country project is to be able to select their national admin data to perform the clip when they download a global dataset.

_Possible solution:_
Grant admins of each project to publish a national administrative boundary data and set it as "default" geometry data for all processes that involve boundary data:
1) calculate area of selected features that fall within the country.
2) download global vector layers clipped by the country.
@fxi:
I would like to know if this is possible, and how much time it can take to make it possible.

**Comment by scabecks** [comment]
I would be interested to see what that would work like; would pre-cutting some some of the larger layers (like ecoregions) to countries make calculation of  areas more possible (assuming we can only mask one layer at a time) and in some cases users need to know how much of layer A is within layer B within a country (i.e., how much ecoregion is within protected areas in a country)?

**Comment by fxi** [comment]
`WHERE` clause is just an optional parameter that would filter source features and/or mask feature. 

For example, given a vector view that is configured as `source = protected areas` and `mask = country borders`, if we set the optional `WHERE` clause in the source as `WHERE iucn_cat="not reported"` and the mask as `where iso3_code="BRA"` we can make, server side, vector tiles of protected areas inside Brazil where the protected area category is not reported. Then, with the client side tool "Calculate area", we can extract the area of those areas, only for brazil. 

What you describe sounds like triple  intersects `eco region ∩ country ∩ protected areas` that's again another story. I can do it server side too, but doing this on the fly is quite foolish. Client side is not an option. 

But.. there is a very experimental feature in GeoCompo: after the compositing is done, we can try to extract the geometry back using a marching square algorithm and use `turf` to get an approximation of the area...

Or.. is someone still reading this, still using GeoCompo, I can try to estimate the area covered by the pixel in the resulting canvas and then, multiply activated pixels by the pixel area to get the approximation.

So, to wrap up:

- Existing tool : clicking on a feature, we can filter value by attribute. Eg. we can filter by country if the attribute country exists.
- Existing tool : clicking on the area calculator button, MapX dump every visible geometry from loaded vector tiles in a single object, get buffers, estimate the area. Could be used together with filtering by legend AND filtering by date AND filtering by time AND filtering by attribute. 
- Polygon clipping client side : not an option for complex data. Works fine with simple geometry.
- Server side clipping in PostGIS with new `WHERE` clause: filter features before building tiles. Heavy for the server, no calculation on the client. Only two layers (for now) and performance issue.
- GeoCompo :
    -  Extract overlapping pixels, then producing a vector using marching square (e.g. D3-contour). Using turf to estimate the area. 
    - Extract overlapping pixels, estimate pixel area at the current zoom to get the area.

**Comment by antobenve** [comment]
This issue should not be addressed before 2019 provided that new funding is received.

**Comment by antobenve** [comment]
I'm closing this issue as not relevant anymore. 
The useful insights that were provided in the discussion will be proposed in a new dedicated issue if funds will be provided to develop a "clip by custom layers" tool.
