### ISSUE TITLE
Map/Screenshot creation and download error - Firefox/Linux

### ISSUE THREAD

**Issue by scabecks** [unep-grid/map-x-mgl#311]
Screenshots are failing to create and download in Firefox (no problems in Chromium) on Linux.

Console output: 
`Error: "addImage does not support files of type 'UNKNOWN', please ensure that a plugin for 'UNKNOWN' support is added."
addImagehttps://mvp.app.mapx.org/16-6b9ee1a7f09cc9ddb6a5.bundle.js:42:6500bhttps://mvp.app.mapx.org/common-6b9ee1a7f09cc9ddb6a5.bundle.js:39:468571`

OS: Linux Mint 19
Browser: Firefox 61.0.1

**Comment by fxi** [comment]
Thanks.
I was able to reproduce it with Firefox 61.0.2. Browser specific issue appart, maybe related to https://github.com/MrRio/jsPDF/issues/1899

**Comment by tdearden** [comment]
Screenshots are also failing on Macs. On Safari, it says "Screenshot generation, please wait" and the bar loads but nothing is saved anywhere. Automatic downloads are enabled. On Chrome, it says "Screenshot generation, please wait" but gets stuck and doesn't advance (see screenshot).
 
![4aa828c85b8605fcbbe7074c21e6b0e1d2704344a77ed97e3b pimgpsh_thumbnail_win_distr](https://user-images.githubusercontent.com/41048297/44773864-eb2c4000-ab71-11e8-9321-2d9163d5550c.jpg)

**Comment by scabecks** [comment]
Just a further (new) note on failing screenshots:

Browser: Firefox 64.0 (but also failing on Chromium)
OS:Linux Mint 19.1
Error occurring: the process just hangs and the page must be reloaded.

Console output: `IndexSizeError: Index or size is negative or greater than the allowed amount 19.chunk.js:1`

**Comment by scabecks** [comment]
re: the previous comment - the issue seems to relate to the legend (or lack there of in this case). Using a dummy legend (from another related view) allows the screenshot/print screen to output normally.

**Comment by thomaspiller** [comment]
The screenshot tool is no more available in MapX.
It is replaced by the new map composer.
