### ISSUE TITLE
MapX test version: Filter mode: multiple categories activated don't filter the views properly

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#319]
Inside a type of filter, only the views of the **last** category activated are displayed. 

1) In the filter tool, **inside** a type of filter (ex: theme, or type of view, or collection), if **several** categories are activated (ex: layers (40 views), story maps (3 views), the views filtered in the menu correspond to the views of the **last** category activated in the list (order of **appearance** in the list), meaning the 3 story maps only. 

2) If a second type of filter is activated (ex: theme=environment (2 views), theme=extractive (1 view) ), the bug happens again: only the extractive views will be displayed

-->  The views displayed on the screen will be the views filtered from the step 1. (the 3 story maps only, while the 'layers' category is also activated) overlapped with the views filtered from the step 2. (the 'Extractive' tagged views only, while the 'Environment' tagged views are also activated ). 
The final result is the story map tagged as extractive only. 
____________________

**NB**: the number of views associated with each category is not updated while filters are activated.
_Example_:
If a project contains:
- 40 layers and 3 story maps
- 20 "environment" views and 10 "extractive" views
If a user selects:
- story maps (3 views)
- and "extractive", then the number of views associated with "extractive" will be the initial number of extractive views (Extractive (20) ) and not the number of views tagged as extractive among the story maps views activated Extractive (1)
The result would be 1 story map tagged as extractive.

@fxi is this **NB** part of the same bug or should I post this separately?

**Comment by fxi** [comment]
mmh, that's bad. Two people validated this.
Anyway.. For the view count, it was not asked, but try https://test.app.mapx.org again. You will need to refresh your browser once after the first load.
The count reflects what's currently shown, based on the current selection.
@thomaspiller check that also.

**Comment by thomaspiller** [comment]
I tested the filters in V1.5.17. The logic is respected: "AND" operator between filters and "OR" in a specific one. The auto-updated view count is a great addition and it works well.

**Comment by antobenve** [comment]
I had the same problem Marion until I emptied the cache of the browser. Fred suggested me to do this to make sure you empty the cache of the website:
Console --> Application --> Clear Storage --> Clear Site data
![image](https://user-images.githubusercontent.com/30286565/44921753-b839a600-ad43-11e8-95a0-2aa5fc3c6a11.png)

**Comment by MarionPlanque** [comment]
@fxi Now it's fine indeed; both bugs of multiple categories AND number of views associated with activated categories have been solved.
All good!
