### ISSUE TITLE
MapX deconnect and reconnect too often

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#343]
The problem has been experienced by different users in different ways. For some it is really a problem as it may happen during the upload of a source layer or the configuration process of a view. I am also experiencing this problem more often at home (Win 10) compared to at work (Win 7) on Chrome. No console error.

**Comment by fxi** [comment]
If I can't reproduce it, I will not be able to solve it.
Please add a concise, relevant, technical and clean way of reproducing this.

**Comment by antobenve** [comment]
I can't reproduce it on purpose. To me it happens to deconnect when I leave the app for a while untouched, not always after the same time period of inactivity in my opinion. However, to others it seems that they were affected by it during their action on the platform but I don't know more about it right now. It was mention in a google sheet by UNDP and got no further information. Sorry.

**Comment by antobenve** [comment]
It has been reported to me that the problem is mostly (but not only) experienced in low band connectivity countries (Samoa, Seychelles etc). If this is a real problem due to low connectivity, is there any way to avoid the rebooting when the connection is recovered?

**Comment by antobenve** [comment]
FYI, I managed to have a log where more information were displayed.
```
Fri Oct 19 2018 17:03:17 GMT+0200 (Ora legale dell’Europa centrale) [INF]: Disconnect detected; attempting reconnect
shiny-server-client.min.js:1 Fri Oct 19 2018 17:03:17 GMT+0200 (Ora legale dell’Europa centrale) [INF]: Connection restored
shiny-server-client.min.js:1 Fri Oct 19 2018 17:03:17 GMT+0200 (Ora legale dell’Europa centrale) [INF]: Connection closed. Info: {"type":"close","code":4705,"reason":"Your session could not be resumed on the server.","wasClean":true}
shiny-server-client.min.js:1 Fri Oct 19 2018 17:03:17 GMT+0200 (Ora legale dell’Europa centrale) [DBG]: SockJS connection closed
shiny-server-client.min.js:1 Fri Oct 19 2018 17:03:17 GMT+0200 (Ora legale dell’Europa centrale) [DBG]: Channel 0 is closed
shiny-server-client.min.js:1 Fri Oct 19 2018 17:03:17 GMT+0200 (Ora legale dell’Europa centrale) [DBG]: Removed channel 0, 0 left
```

This happened with the configuration window of a view open in mapx while I was working on another tab (no mapx). I realized it was disconnected when I switched back to the MapX tab.

Here the whole console log:
[app.mapx.org-1539961433864.log](https://github.com/fxi/map-x-mgl/files/2496375/app.mapx.org-1539961433864.log)

**Comment by antobenve** [comment]
Might be useful as well: https://support.rstudio.com/hc/en-us/articles/220315848-Troubleshooting-applications-in-Shiny-Server-Pro

**Comment by fxi** [comment]
Except that we don't use shiny-server pro... 
No env variables, no session timeout, etc.. That's not relevant in our case.

**Comment by antobenve** [comment]
Unfortunately not then. My bad. I hope the console log helps.

**Comment by fxi** [comment]
No problem. However, the "database connection" part could be relevant, though, but before 18.10.2018:

```sh
pg_1       | 2018-10-18 13:33:00.910 UTC [496] LOG:  could not write temporary statistics file "pg_stat_tmp/db_0.tmp": No space left on device
pg_1       | 2018-10-18 13:33:00.910 UTC [496] LOG:  could not write temporary statistics file "pg_stat_tmp/global.tmp": No space left on device
pg_1       | 2018-10-18 13:33:06.217 UTC [22984] LOG:  using stale statistics instead of current ones because stats collector is not responding
pg_1       | 2018-10-18 13:33:11.049 UTC [495] LOG:  using stale statistics instead of current ones because stats collector is not responding
pg_1       | 2018-10-18 13:33:11.059 UTC [496] LOG:  could not write temporary statistics file "pg_stat_tmp/db_475696.tmp": No space left on device
pg_1       | 2018-10-18 13:33:11.059 UTC [496] LOG:  could not write temporary statistics file "pg_stat_tmp/db_0.tmp": No space left on device
pg_1       | 2018-10-18 13:33:11.059 UTC [496] LOG:  could not write temporary statistics file "pg_stat_tmp/global.tmp": No space left on device
pg_1       | 2018-10-18 13:33:15.777 UTC [496] LOG:  could not write temporary statistics file "pg_stat_tmp/db_0.tmp": No space left on device
```

**Comment by fxi** [comment]
Thanks for reporting this.

Sorry for any lost job. I've implemented a new unified auto-save mode for big forms like story maps editor, dashboards, style and custom code views. It should avoid any lost job due to network or disconnection issue. Available soon.

For the underlying issue, it sounds like an uncaught error occurs in the same node, server side, which produce a shut down all sessions at once. It's not related to the browser, at first sight. 

Is the disconnection happen after a certain action ? Opening modal windows or clicking on something ? Or as soon as the second tab is open, both instances disconnect ?

@antobenve @thomaspiller are you able to reproduce what @tdearden described ?

**Comment by antobenve** [comment]
@fxi , sometimes I experience disconnections at GRID on Windows 7 on Chrome. I usually realize that a disconnection occurred when I get back to MapX tab after being on another one. This is not only happening when 2 or more tabs of MapX are open. 
After many investigations, I couldn't find a reason for the disconnections. I would say it is unrelated to specific actions on the tabs as I first reported in this issue in October.

I tried to reproduce the specific problem of @tdearden on story map making with 2 tabs open without success on my laptop at home on Windows 10. Half hour with 2 tabs open, displaying views, editing views and changing project in one, making, saving, editing, playing a story map in the other: it never disconnected.

**Comment by antobenve** [comment]
Hi @fxi, Please find [this](https://owncloud.unepgrid.ch/index.php/s/sw3uJLpwK2QP4Yd) report on the connectivity problem of MapX in low bandwidth countries. The report is based on data collected from different users as described in it. I hope it can help. If you need further information please let me know.

**Comment by fxi** [comment]
There are some privacy issues here :
- Some links provided disclose private user data : name, details, precise location. Maybe not great for those peoples.
- Some logs contain encrypted URL : those links can trigger action in MapX in behalf of the targeted user and should not be publicly available. 

Furthermore, there are some issues in the report, from my point of view.

- There is a collection of hardly connected issues covering a wide range of time and domain. To name a few:
    -  corrupted service workers from an old version of the app, 
    -  slow network, 
    - connection issue, 
    - 404 errors,  
    - ERR_NETWORK_CHANGED issues,
    - Issues unrelated to MapX app,
    - Very long logs with many issues..
- If all tests are negative, it means it's not OK. Each record should provide at least the result of this test to remove all doubt about the browser, network, context. 
- We need a little bit of a rigorous approach. For each case, we need, for example : browser version, location, meaningful part of logs, dates,  app version, etc. See the example below, more scientific : 

Date | URL | Logs | App version | Country | Disconnect after (min) | Browser | Extensions | Tests |  Private network | Notes
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
10.05.19 | mapx.org | link | 1.5.35 | unknown | 0 | Chrome 75 | Yes | Pass | Yes |
11.05.19 | shiny.io | link | NA | Gana | 1 | Chrome 75 | No | Fail |  No|
12.05.19 | mapx.org | link | 1.5.37 | Peru | 2 | Chrome 75 | Yes | Pass |  No |
13.05.19 | mapx.org | link | 1.5.38 | Samalia | 3 | Chrome 75 | No | Fail |  
14.05.19 | mapx.org | link | 1.5.39 | Switzerland | 4 | Chrome 75 | Yes | Pass |  
15.05.19 | mapx.org | link | 1.5.40 | Hungary | 5 | Chrome 75 | No | Fail |  
16.05.19 | mapx.org | link | 1.5.41 | unknown | 6 | Chrome 75 | Yes | Pass |  
...

But thanks for providing something.

**Comment by antobenve** [comment]
@fxi I wish we had more complete information. I made the report this way because with the information we have it would not make sense, to me, to create a table like the one you suggested. Too many things that we didn't collect because the users provided only sparse information except few cases. Furthermore, tests were all 100% positive (I wrote negative, my bad) and didn't catch the issue. If you need to check them they are listed in the second link that I provided in the 5th line of the report.
In case you want, I can provide a table like that one when back in July.

The summary I proposed you provides you with the important points based on the information that was received as tables and from email exchanges. Supplementary logs add value to the summary for what I could not summarize myself. The logs are long, but I thought that cleaning them from specific lines that were not related to MapX would not be a good idea as this would have taken time and potentially have had a negative impact, considering that I would often be unsure about whether to remove a line or not. Furthermore, the fact that logs contain hardly connected issues is something I could not be sure myself. I think it is a good idea that you have checked them.

Finally, I'm removing the link to the report from the previous comment. Sorry for this inconvenient. You will be provided the link privately if you need to access the report again.

**Comment by thomaspiller** [comment]
It seems that nothing has been reported since June 2019. Can I close this issue?

**Comment by antobenve** [comment]
well, it's an old one, it's true. Let's close it and we'll see later if we need to reopen it again.
