### ISSUE TITLE
PixOp - Script terminated by timeout at: o.prototype._findOverlapSpotlight [Firefox 62.0.2 test.app.mapx.org]

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#344]
No highlight is displayed. The whole page becomes inactive and the message "A web page is slowing down your browser" appears.

Console:
`Error: Script terminated by timeout at:
o.prototype._findOverlapSpotlight@https://test.app.mapx.org/common-731fbe68d98bcd1a7936.bundle.js:39:526124
o.prototype.renderMethod@https://test.app.mapx.org/common-731fbe68d98bcd1a7936.bundle.js:39:524367
o.prototype.render/<@https://test.app.mapx.org/common-731fbe68d98bcd1a7936.bundle.js:39:523145
o.prototype.render@https://test.app.mapx.org/common-731fbe68d98bcd1a7936.bundle.js:39:523103
t.overlapsSpotlightUpdate@https://test.app.mapx.org/common-731fbe68d98bcd1a7936.bundle.js:39:439510
r/</B.prototype.fire@https://test.app.mapx.org/common-731fbe68d98bcd1a7936.bundle.js:45:18806
r/</Rn</n.prototype._afterEase@https://test.app.mapx.org/common-731fbe68d98bcd1a7936.bundle.js:45:581343
r/</Rn</n.prototype.easeTo/<@https://test.app.mapx.org/common-731fbe68d98bcd1a7936.bundle.js:45:580555
r/</Rn</n.prototype.stop@https://test.app.mapx.org/common-731fbe68d98bcd1a7936.bundle.js:45:583425
r/</Rn</n.prototype._renderFrameCallback@https://test.app.mapx.org/common-731fbe68d98bcd1a7936.bundle.js:45:583938
r/</qn.prototype.run@https://test.app.mapx.org/common-731fbe68d98bcd1a7936.bundle.js:45:588353
r/</Gn</o.prototype._render@https://test.app.mapx.org/common-731fbe68d98bcd1a7936.bundle.js:45:605808
r/</Gn</o.prototype._rerender/this._frame<@https://test.app.mapx.org/common-731fbe68d98bcd1a7936.bundle.js:45:607678
 common-731fbe68d98bcd1a7936.bundle.js:39:526124
`

**Comment by fxi** [comment]
It could be great if I got something clear, concise, complete to be able to reproduce this error. 

Could you add the project you are currently working on, the views list you are trying to analyse, and the number of layers needed to be considered as overlap in the settings (tools panel) ?

Thanks

**Comment by antobenve** [comment]
@fxi , 
The app blocks with any polygon-type view in any project as long as at least 2 polygon-views and the overlap tool are active.
The problem doesn't occur if point views are being overlapped with other point views or with 1 polygon view.  However, I just saw that when **line or point views** are overlapped alone or with 1 polygon view **the highlight is not displayed**.

**Comment by antobenve** [comment]
@fxi, FYI, This issue is still affecting the preview overlap tool in Firefox. No error in console unless the process is stopped answering "Stop it" to the question in the yellow bar on top of the page. In that case, the error is the one reported in the opening text of the issue.
![image](https://user-images.githubusercontent.com/30286565/49072486-a0819900-f230-11e8-80f2-ea28ce7e9a74.png)

**Comment by thomaspiller** [comment]
@antobenve Is this problem still present?

**Comment by antobenve** [comment]
Unfortunately PixOp still causes some issues on Firefox. 
I couldn't experience the issue described above but I still couldn't use the tool and I got the following errors in console when activating PixOp on any number of layer with any toolbox option set.
Please check this as example:
https://app.staging.mapx.org?project=MX-YBJ-YYF-08R-UUR-QW6&views=&viewsOpen=MX-3PH1G-OOJHT-6FS0X,MX-ML9PZ-PZ1SI-WVV85,MX-Y3HWB-9IXHB-3AW3N&language=en&viewsListFilterActivated=true&

**Comment by thomaspiller** [comment]
PixOp has been disabled in non-blink browsers (safari, firefox) that don't handle off-screen canvas (see 77fe629). Consequently, this issue doesn't affect MapX anymore.

**Comment by fxi** [comment]
Note: Firefox supports offscreen canvas, but not resetting sizes from worker. This could be solved in a future version of PixOp, using a different approach. Impacted features : SpotLight, Visual overlaps.
