### ISSUE TITLE
Bugs v.1.5.27

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#358]
Chromium and Firefox:
- [x] If at least one country is selected in the field "Countries to be highlighted" under "Project configuration", its removal is not taken into account when the project is saved. No error is thrown. Project seems saved correctly but the changes are not registered.
- [x] MapX logo is not displayed in the title bar.
- [x] Edit source metadata window doesn't automatically resize if the dropdown list is clicked (other source layers can only be seen if the content is scrolled). Furthermore, the window can only resize its width if the vertex is selected with the mouse.
- [x] Edit metadata: if the title of a source layer is edited, the source layer will still be identified with the old name in any list until the page is refreshed.

Chromium only:
- [x] Hidden portions of the legend of vector views don't display when scrolled down until an entry is clicked.

Firefox only:
- [x] No message is displayed to confirm that the process of sharing a view to an external project was positively terminated.

**Comment by thomaspiller** [comment]
@antobenve: are the remaining two items still relevant? If not, could you close this issue please.

**Comment by antobenve** [comment]
Yes, both items are fixed. I am closing the issue.
