### ISSUE TITLE
How to add custom alias/label to attributes names ?

### ISSUE THREAD

**Issue by fxi** [unep-grid/map-x-mgl#359]
# Add Custom Labels to Source Attributes Names
It's often valuable to replace technical or obscure attribute names by something clearer. For example, a source using the attribute name  `x_1Mp_mean` would be more comprehensive with this name : "Average monthly precipitation [mm]" in English and "Précipitation mensuelle moyenne [mm]" in French. To do so, you will use the metadata editor in MapX, and modify the labels under  `metadata > textual > alias for attributes names`. Vailable since `1.5.27`
Here is a quick video of the process:
![demo_labels](https://user-images.githubusercontent.com/19908801/124259127-77cf8780-db2e-11eb-8ede-1b6cd4976c45.gif)

**Comment by thomaspiller** [comment]
The content of this page has been transferred to the wiki.
