### ISSUE TITLE
Problematic: It is unclear that the empty category in access rights refers to "myself"

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#362]
When configuring a view, for the read or edition access, it is not clear that leaving the category blank refers to "myself".
_Suggestion_: In the previous version, "myself" was one of the categories, it would be good to restore this if possible.

**Comment by MarionPlanque** [comment]
I bring this topic back as the problem is still there

**Comment by thomaspiller** [comment]
"Myself" is available in the new version.
