### ISSUE TITLE
Improvement: zoom to displayed features --> zoom to selected features (button for vector views)

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#367]
Current behaviour:
- The zoom to displayed features button depends on the current bbox + the selected features.
Problem:
- Clicking repeatedly the "zoom to displayed features" button always changes the bbox of the map because it tends to include the total extent of features that were partly visible on map. 

Proposition: 
- Zoom to selected features only.  --> rename the button "Zoom on selected features"?

**Comment by thomaspiller** [comment]
The button was renamed "Zoom on displayed features" and the tool works well.
