### ISSUE TITLE
Priority 2 - Export of views - legend problems

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#371]
#### Update v.1.5.35 20/12/2018

**Issue 1** --> This issue is still reproduced in Marion's work laptop and, in less amount, in Lucy's work laptop. The issue seems fine with the computers where I could test it. 
The issue was only encountered in **Chrome** in **Windows 10**. Firefox seems OK.
**Issue 2** --> Seems fine in both Firefox and Chrome.
**Issue 3** --> Still a problem for Marion's work laptop in **Chrome** in **Windows 10**. Not systematically reproduced.

_**New issue (which might be unrelated to MapX but I'm not entirely sure)**_
**Issue 4** --> The download of multiple zip files for the number of views that are active on map (when the user clicks "Print Current") doesn't work for Marion's work laptop in **Chrome** in **Windows 10**. Only 1 zip is downloaded. After that, MapX must be restarted to export again using "Print current". No error is thrown in console.  "Take a screenshot" works instead in this case too. The download of multiple files is allowed in her browser (https://ccm.net/faq/32938-google-chrome-allow-websites-to-perform-simultaneous-downloads)

### Updated table
browser | version | issue 1 | issue 2 | issue 3 | issue 4 | mapx version | OS
-- | -- | -- | -- | -- | -- | -- | --
Firefox | 63.0.3 (64-bit) | ok| ok | ok| ok | v1.5.35 | win 10
Chrome | 71.0.3578.80   (64-bit) | failed| failed | failed| failed | v1.5.35 | win 10
Edge | 42.17134.1.0 | ok |   | -- | -- | v1.5.30 | win 10
Chrome | 70.0.3538.110 (64 bit) | ok | ok | -- | -- | v1.5.30 | Ubuntu
Firefox | 63.0.3 (64-bit) | ok | ok | -- | -- | v1.5.30 | Ubuntu

#### Bugs description
- [ ] Issue 1: Pdf and png files -> Legend text is cut in a not appropriate way with "..." when the lenght of the text is not that high. Screenshot in [comment below](https://github.com/fxi/map-x-mgl/issues/371#issuecomment-445760414).

- [ ] Issue 2: Png file (for views with many rows in the legend) -> The value of the legend is not displayed next to the symbol for the rows after a certain position. Full screenshot in [here](https://owncloud.unepgrid.ch/index.php/s/Uso7jjxVvcHxkFb/download).
Here a zoom in.
![image](https://user-images.githubusercontent.com/30286565/49741242-45bb5900-fc96-11e8-801c-910d505f8065.png)

- [ ] Issue 3: Pdf and png files -> The text of legend values and title in pdf and png files is so small that it can barely be detected. The resolution of text is also very low. Therefore we can only see pixels that occupy a very small area where you can guess from their relative length that they represents the text. 
The bug seems recurrent once it had occurred for a first time. Restarting MapX seems to solve the issue in this case. Zoom and resolution don’t affect it. 
However, the bug is very rare and still not possible to be reproduced in a systematic way. 
It was reported on Chrome (64 bits up to date) on Windows 10 on the online version v1.5.29. The same issue was reported with a higher frequency in the local testing environment on a previous version until it was addressed by changing the way the legends were generated.

**Comment by PierreLacroix** [comment]
Priority 2 for now, as we have first to deliver a series of tools in the coming weeks

**Comment by fxi** [comment]
@PierreLacroix , you should be allowed to set priorities. Click on labels, on the right side of each issue, to search for the priority you want to set.

**Comment by thomaspiller** [comment]
![tempsnip](https://user-images.githubusercontent.com/19908801/49725375-d2045680-fc6b-11e8-8177-6d6a5ed6e0f0.png)


Legend text is cut in a not appropriate way with "..."


MapX local: v1.5.30 latest
Windows 10 Pro


Firefox 63.0.3 (64-bit) | Chrome 71.0.3578.80 (64-bit) | Microsoft Edge 42.17134.1.0
-- | -- | --
issue | ok | ok

**Comment by antobenve** [comment]
> The value of the legend is not displayed next to the symbol for the rows after a certain position

For very long legends like this [view](https://app.mapx.org?project=MX-XNI-RMZ-KKL-FMS-DVH&views=MX-305PX-2NDC3-NOO27) 
![mx-legend](https://user-images.githubusercontent.com/30286565/49741930-caf33d80-fc97-11e8-8b89-ad2ab78726d2.png)

**Comment by thomaspiller** [comment]
I close this issue as the soon to be released "map composer" should solve all of that.
