### ISSUE TITLE
Bug - Safari - TypeError: Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#372]
The MapX page doesn't fully load the information related to buttons, views and project name. The only text is "Sort by" and "Activated view only".
The error `TypeError: Attempted to assign to readonly property` is sent by the console. I found some information about it here http://craigsworks.com/projects/forums/showthread.php?tid=3649&pid=14200#pid14200
It seems a Mac bug and that changing this part `opts['corner'] = TRUE;` might solve the problem.
Also here: https://stackoverflow.com/questions/26044056/typeerror-attempted-to-assign-to-readonly-property-in-angularjs-application-on

> Online version
> MacOS (10.10.5)
> Safari Version 10.1.2

**Comment by thomaspiller** [comment]
@antobenve the version of macOS and safari are very quite old, is this issue still relevant?

**Comment by antobenve** [comment]
I'd say we can close it. We can always resuscitate it in case.
