### ISSUE TITLE
Feature request: Set style according to 2 variables (1 for size, 1 for colors) for point data

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#38]
### Expected Behavior
When setting up the style, rules should be created according to two different variables (separately): 1 rule for setting up size of points, 1 rule for setting up the color of point. This way, colors and size would depend on two different variables.

### Current Behavior
Only one variable can be used for categorical rules. Both colors and size depend on the same values.

### Steps to Reproduce

1. Create a view of a point source layer.
2. Set the style

### Detailed Description
This is a suggestion in case this is doable because I don't know if it is complicated to make different rules to interact. I think that it might be very useful for point data.

**Comment by thomaspiller** [comment]
It would be interesting to do the same for polygon "layers".
Example: colors based on a first variable & patterns based on a second variable (both from the same source obviously)

**Comment by thomaspiller** [comment]
Custom style allows bi-variate styling.
