### ISSUE TITLE
General improvements [new]

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#383]
_Based on issues #177 #258 #334 #338_

- [ ] Toolbox: when deselecting a view for which an area has been calculated or changing project, the area of visible features must be cleared.

- [ ] Metadata - additional notes: English input should be displayed when MapX is in another language.

- [ ] Modal panels: inputs should only be resizable in Y-axis.

- [ ] mx_logs: It would be useful to be able to know the time activity of users into each project

- [ ] Pop-up: allow users to close the pop-up window but keep the filter on with the "x". Add a button "Reset filter and close" to close the pop-up like now.

- [ ] Projet selection: if the project can't be loaded, the user should read why and be given options to log-in (if unlogged) and try again to load the project using the new credentials or to continue towards the default public project.

- [ ] Sort by ...: no indication of which filter is active (possible solution: color of active filter = red)

- [ ] Dashboard: the symbols in the circles (top corners) are not centered.

- [ ] Responsiveness: dashboard overlaps the left panel when the screen is small (embedded MapX in JsFiddle).

**Comment by Svensl** [comment]
Scalable resizable popup windows
URL in popup windows
Labeling of features

**Comment by thomaspiller** [comment]
Merged with #446 & #447.
