### ISSUE TITLE
"Other projects where the view is visible" is no longer useful

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#385]
The category "Other projects where the view is visible" in the configuration menu is no longer **useful** since there is the **other optio**n to share the view in another project from the share button.
Keeping these two categories entails a risk of **confusion** for users and risk of sharing views on two different ways which is complicated for **views management**.

_Suggestion_: **delete** the possibility to share views in another project with the "Other projects where the view is visible" and keep **ONLY** the share button, which is clearer

**Comment by antobenve** [comment]
As discussed today I still think the old system is useful as it allows us to set a certain view available in a project without allowing its publishers to un-share it.
