### ISSUE TITLE
rev. 1.5.38 testing 

### ISSUE THREAD

**Issue by fxi** [unep-grid/map-x-mgl#393]
Blocking bugs of the rev. 1.5.38.

### Solved
- [x] Dashboards. All widgets using Highcharts are not displayed.
- [x] Save view edit. Disconnected after clicking on the button. No unexpected issue pop-up. Console: The application exited unexpectedly. socket hang up
- [x] View metadata button. Disconnected after clicking on the button: unexpected issue = argument is not interpretable as logical
- [x] Disconnected after clicking on the button: unexpected issue = mxSendMail : Server can't send email to < user email >.
- [x] JSON country list : Namibia still missing
- [x] View edit save : all view filter are updated, except "layers" filter item. The saved view is removed from the count. 

- [x] Geserver binding, source edit panel: Clicking "Update", even if nothing is changed, cause disconnection. No unexpected issue pop-up
- [x]  GeoServer binding : wms/wfs. Both workspaces that are created for a project ("...a", "...b") have the same active services (WMS,WCS,WFS).
- [x] Geserver binding, source edit panel. After enabling WMS for a source, the workspaces are created but I sometimes get disconnected when I edit views especially after a "read access" change.
- [x] Geserver binding. Deleting a view or changing the "read access" : public to ... -> layer is not delete in the GeoServer
- [x] Language change : project name in left panel doesn't update when the language is changed

### Not able to reproduce
- [ ] Drop down list, windows not resizing.
- [ ] View edit save. Adding/removing a collection (new or existing) to a view can cause disconnection when saving.
- [ ] Mapbox gl : webgl context lost after a story map reading. The map disappeared once.
- [ ] Save edited project configuration. Save button must be clicked twice in the project configuration window
- [ ] Update service worker : Popup doesn't close after installation is completed. "Install" button grayed. "Close" is active. 

### Not yet reproduced - non blocking
- [ ] Diaf star tooltip summary : text as mouse hovers the star doesn't display in new language until the page is refreshed after the language is changed
- [ ] View creation. allow special characters. See #299 
- [x] Project creation: allow special characters (-â etc... in title
- [x] Edit metadata form DIAF: the translation of the input values is no longer present (e.g. dont_know): the translation of the input values is no longer present (e.g. dont_know)
- [x] "source_meta_data" is not stated in english - in the metadata window that is reached from the views panel through the "i" button.
Notes:
- This is based on issue #388 and #389.
- Please add only reproducible bugs. If not consistent, mention steps used to trigger at least once the bug.

**Comment by antobenve** [comment]
> Geserver binding, source edit panel: Clicking "Update", even if nothing is changed, cause disconnection. No unexpected issue pop-up
This point was related to missing "services" column in mx_sources. So, I suggest you to remove it from the list of bugs.

**Comment by antobenve** [comment]
As for the bug:
>Save edited project configuration. Save button must be clicked twice in the project configuration window

It might be a focus problem, as you suggested, that occur when the cursor is not removed from text fields before clicking "Save".

If I enter some text in the Description field and I immediately click "Save" it doesn't save. If I click somewhere else in the modal window and then click "Save" it saves.

This is the message in Network-WS that is sent when I click "Save" without success:

"ACK AA"] | 10 | 16:34:18.739 |  
-- | -- | -- | --
["24#0\|m\|{\"method\":\"update\",\"data\":{\"projectDescriptionSchema_values\":{\"msg\":{\"en\":\"antonio bla\",\"fr\":\"\",\"es\":\"\",\"ru\":\"\",\"zh\":\"\",\"de\":\"\",\"bn\":\"\",\"fa\":\"\",\"ps\":\"\"},\"time\":\"2019-01-31T15:34:25.319Z\"},\"projectDescriptionSchema_issues\":{\"msg\":[],\"time\":\"2019-01-31T15:34:25.319Z\"}}}"] | 337 | 16:34:25.320 |  
a["AA#0\|m\|{\"busy\":\"busy\"}"] | 31 | 16:34:25.334 |  
a["AB#0\|m\|{\"custom\":{\"mxButtonToggle\":{\"id\":\"btnSaveProjectConfig\",\"disable\":false,\"warning\":false}}}"] | 115 | 16:34:25.413 |  
a["AC#0\|m\|{\"progress\":{\"type\":\"binding\",\"message\":{\"id\":\"projectConfig_validation\"}}}"] | 99 | 16:34:25.414 |  
a["AD#0\|m\|{\"recalculating\":{\"name\":\"projectConfig_validation\",\"status\":\"recalculating\"}}"] | 100 | 16:34:25.417 |  
a["AE#0\|m\|{\"recalculating\":{\"name\":\"projectConfig_validation\",\"status\":\"recalculated\"}}"] | 99 | 16:34:25.418 |  
a["AF#0\|m\|{\"busy\":\"idle\"}"] | 31 | 16:34:25.419 |  
a["B0#0\|m\|{\"errors\":[],\"values\":{\"projectConfig_validation\":{\"html\":\"<ul class=\\\"list-group mx-error-list-container\\\"><\\/ul>\",\"deps\":[]}},\"inputMessages\":[]}"] | 178 | 16:34:25.421 |  
a["ACK 25"] | 11 | 16:34:27.330 |  
["ACK B1"]

**Comment by antobenve** [comment]
Hi @fxi, as a complement to the non-blocking issues of the version 38 (now in prod) I would like to add this:

- [ ] "source_meta_data" is not stated in english - in the metadata window that is reached from the views panel through the "i" button.
