### ISSUE TITLE
Upgrade postgres images

### ISSUE THREAD

**Issue by fxi** [unep-grid/map-x-mgl#395]
Based on @thomaspiller instructions : 

docker-compose.yml
```yml
...
  pg: image: mdillon/postgis:11-alpine
...
```

With full stack launched with docker-compose (app, api, etc). e.g. local testing stack. In prod, this is a little more complicated : no idea to get this working without downtime. To be continued.

```sh
docker-compose exec pg pg_dumpall -U postgres | gzip > {filename.gz}
docker-compose up -d --scale pg=0
docker-compose exec app /bin/bash
mv /shared/postgres /shared/postgres_orig
exit
docker-compose up -d
gunzip < {filename.gz} | docker-compose exec -T pg psql -U postgres -d mapx
```

**Comment by thomaspiller** [comment]
Moved to a dedicated page in the wiki: https://github.com/unep-grid/map-x-mgl/wiki/Upgrade-Docker-image:-PostgreSQL-with-PostGIS-extensions
