### ISSUE TITLE
New request: list updates to UI when installing new versions of MapX 

### ISSUE THREAD

**Issue by tdearden** [unep-grid/map-x-mgl#401]
When a new version of MapX is pushed live, and the user must re-install MapX in their browser, is it possible to add some text in that pop-up describing what the updates are to the user journey? I believe this will be the easiest way to communicate to users that features they are used to are changing. 

For example, the last version would read something like this:

**New updates for MapX Version 5._____:
- Color picker for views updated. Create customized palettes based on ColorBrewer cartography. 
- "Make source downloadable" now moved to "Manage Sources"in the toolbox. 
- etc.** 

I am happy to help writing this copy if needed.

**Comment by fxi** [comment]
Hi @tdearden,
Sure, it would be very useful.
Does a link to a changelog file in this repository could do the trick ?  E.g. the current readme file ?
The modal open, says that there is an update and below, that a link to the readme.
Note that the readme is a little behind the current version : I'm waaaay behind schedule on everything and that was not a priority.

Thanks !

**Comment by tdearden** [comment]
Hi @fxi, sorry about the delayed response! 

I think ideally it would be a mix of both - simple copy for users, and a link to the readme for people that want to know more (providing it is up to date 😇). See an example from Global Fishing Watch below. 
![GFW](https://user-images.githubusercontent.com/41048297/57283157-c8faa280-70ae-11e9-9f1c-b20e876908ec.jpg)

**Comment by fxi** [comment]
Thanks for the example.
I think we have to discuss this with @PierreLacroix.
I will have to build a tool to handle this in multiple languages. The solution I described is not good enough.
The solution I see is converting the changelog.md file into a JSON file, and maintain this instead.
Something like :

```js
{
  "1.5.45": [
    {
      "en": "Map Composer : new tool to build and export the current map, legends and text as a single image, easy to put in a word processing software",
      "fr": "Map Composer : nouvel outil d'export de carte sous forme d'image, avec legendes et texte pour une utilisation facilitée dans un document word"
    },
    {
      "en": "Attribute table : new tool to visualize, export and filter the map using the attribute table from the main source",
      "fr": "Table attributaire : nouvel outil de visualisation, export et filtre de la carte basé sur la table attributaire de la source"
    }
  ],
  "1.5.41": [
    {
      "en": "Description of the new feature",
      "fr": "Description de la nouvelle fonctionalité"
    }
  ]
}

```
That would be translated to a clean message like the one you provided :



> **Whats new in version 1.5.45 :**
> - Map Composer : new tool to build and export the current map, legends and text as a single image, easy to put in a word processing software
> 
> **Whats new in version  1.5.44 :**
> - Description of the new feature

**Comment by thomaspiller** [comment]
This issue was discussed internally and the solution of a link to the changelog was favored.
