### ISSUE TITLE
Overlap utilities improvements

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#403]
Hi @fxi,

Here is a list of changes in terminology and interface improvements suggested by UNDP after they tested the “Overlap utilities”.

#### Terminology
- [x] Change “Overlap utilities” to “Area intersection tool”
- [x] Change “Launch Analysis” to “Run Analysis”
- [x] Change “Overlaping area (km2)” to “Area of intersection (km2)”

####  Interface improvements
- [ ] “Add sources by view” should be activated by default.
- [x] The list of views should be arranged in alphabetical order.
- [x] Add new header under country that says “Select Analysis” where users can click one of two boxes:  “Calculate area of intersection” or “Create new layer”.

**Comment by antobenve** [comment]
Hi @thomaspiller and @fxi , I need to integrate this with a last comment that was sent us and two personal suggestions of the same kind:
- [ ] Add a progress bar or something that indicates that the process is still active in the background and didn't freeze, especially in case of long calculations.

Finally, on my side:
- [ ] send an email to users when the process of creation of a new source was completed.
- [ ] inform users in the overlap utilities window that they are going to receive an email and that they can close the window meanwhile.
Thanks

**Comment by fxi** [comment]
This should be solved since 1.5.39, available in docker hub.
