### ISSUE TITLE
Story maps: the slide classe drop-down menu is "blocked" and too small

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#406]
In the story map engine, the drop-down menu to choose a slide classe is now "blocked" and doesn't expand entirely. There is a slider on the side to scroll down and choose the classe of our choice, but the size of the window is too small and doesn't allow to visualize the propositions nor to click easily on one of the categories.

![image](https://user-images.githubusercontent.com/25179050/53802375-fbb6dc00-3f41-11e9-9dec-18427476dfce.png)

![image](https://user-images.githubusercontent.com/25179050/53802446-230da900-3f42-11e9-9b8b-2a5ad6602319.png)

**Comment by fxi** [comment]
Is that happening after a fresh app session, e.g. after a restart  ?
If not, what are the step made prior editing a story map  ? E.g. after editing a project or a source ?

**Comment by MarionPlanque** [comment]
@fxi Did you do something about that? Because I don't have the same issue anymore, so I wonder if the bug has been solved or if it was simply a "temporary" bug?

**Comment by fxi** [comment]
No idea, maybe a bug that occurs after a given action, as I suggested in my previous comment.
You can close this and reopen it if you find the right sequence of action.

**Comment by MarionPlanque** [comment]
Ok, I close it for the moment, I'll let you know if this happens again!
