### ISSUE TITLE
The 50-character limit for a source title is too short

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#408]
A limit of 50 characters for a source title has been implemented; however, this is quite short and doesn't allow to name properly the layers.

_Suggestion_: delete the limit of characters 

![image](https://user-images.githubusercontent.com/25179050/54135753-b0f20400-441a-11e9-9fcf-ede1d4356739.png)

**Comment by MarionPlanque** [comment]
_Edit_: same problem for the name of a project, a 50-character limit is too restrictive.
_Suggestion_: increase it to 100 (to have some margin)

**Comment by MarionPlanque** [comment]
@fxi  @thomaspiller  Reminder for next week

**Comment by antobenve** [comment]
Closing the issue because topic is developed in #480
