### ISSUE TITLE
Note: Buttons "draw polygons" and "configure a view" are identical

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#412]
The buttons "draw polygons" and "configure a view" are identical.
_Suggestion_: change the layout of the "draw polygons" button to something different. Maybe something like [that](https://www.google.com/search?rlz=1C1GCEB_enCH775CH775&biw=1920&bih=938&tbm=isch&sa=1&ei=zZyTXKWgFsrbwAK_64igAQ&q=draw+polygon+icon&oq=draw+polygon+icon&gs_l=img.3...3707.8536..8759...0.0..0.198.1482.15j2......1....1..gws-wiz-img.......0j0i67j0i10j0i30j0i19j0i5i30i19j0i8i30i19j0i30i19.weVXh2slb-M#imgrc=ENqOxnwI6NcLwM:)?

**Comment by fxi** [comment]
Yep, we can change this.

I've drawn a new logo for this: 
![image](https://user-images.githubusercontent.com/1196833/54765548-04720800-4bfa-11e9-9da3-e258f1c749d4.png)

Or you can search here :
https://fontawesome.com/v4.7.0/icons/

**Comment by MarionPlanque** [comment]
Great!! That's perfect, thanks
