### ISSUE TITLE
 Import/Export of layers evaluation

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#413]
Hi, this is the first results of the evaluation of the import/export processes in MapX

format | import d&d | import file | export as gpx 
-- | -- | -- | --
gpx | Y | N 2 | N 1 
kml | Y 3,4 | Y 5 | N 1 
shapefile | Y | Y 5 | N 1 
gpkg | N 1 | Y | N 1 
geojson | Y | Y | N 1 

##### Main remarks:
1) Not implemented
2) Failed with this message: 
`Failed. Verify your logs (no logs in docker nor console)`
3) KML specific columns are removed.
4) Multipolygons consisting of more than 1 polygon are converted into geometry collections when a kml file is imported through drag and drop. (You can test yourself using layer n.4 as mentioned in the list at the end of the issue)
5) Layers with null geometries: Null geometries are imported as collections (KML using Toolbox), null geometry type (SHP usingToolbox) or multipolygon (in all other combinations of formats and methods).

#### Tested with:
Tested with 2 files that were saved in all formats, published in MapX locally using both methods and later exported through all methods each of them:
1) A light version of mx_countries created through FME and validated in PostGIS and saved initially as .gpkg https://owncloud.unepgrid.ch/index.php/s/N9LcTrAvWFivnNU
2) mx_vector_sp5jo_1jv01_wn9xy_eqyev_u_109 from MapXLocal, exported in all different formats and republished in MapX locally. https://owncloud.unepgrid.ch/index.php/s/Rm7ksmluUkQWAHO

For gpx data we used a demo dataset downloaded from the web. 
3) https://owncloud.unepgrid.ch/index.php/s/r2DksOFS0iV1xEf 

For further investigations on the kml side, we also used 
4) A newly drawn layer with 2 combined polygons and 3 polygons through the MapX drawer. Exported through QGIS as kml file and later re-published in MapX locally: https://owncloud.unepgrid.ch/index.php/s/eDExohhHDcx3WtA

**Comment by antobenve** [comment]
Test of Togeojson library and GDAL for a better understanding of the upload process in MapX:
### Results: 
- The library Togeojson converts (kml) multipolygons into (geojson) geometry collections. The problem must be corrected at library-scale, not in MapX.
- The ogr2ogr conversion tool behaves as expected. I tested kml to geojson. It reads the kml files as in MapX (null geometries -> geom_collections, multipolygons -> multipolygons).

**Comment by fxi** [comment]
@antobenve thanks. Have you tried `tmcw/togeojson`? MapX uses `mapbox/togeojson`, but it's no more maintained.

**Comment by antobenve** [comment]
@fxi Same result. No luck.

**Comment by fxi** [comment]
Here is a summary of my tests, after adding support for SRS assignation in 5e3493a6ab7bf

format | input drag/drop | input file | export | status
-- | -- | -- | -- | --
geojson | pass | pass | pass | 🚀   
gpkg | na <sup>3</sup>  | pass | pass | 😃   
sqlite | na <sup>3</sup> | pass | pass | 😃   
kml | pass<sup>1</sup> | pass<sup>1</sup>  | pass<sup>1</sup> | 😞 
shapefile | pass <sup>1</sup>| pass <sup>1</sup> | pass | 😞 
dxf | na <sup>3</sup> | pass <sup>1,</sup><sup>4</sup>  | pass<sup>1</sup> | 😞 
csv | na <sup>3</sup> | pass <sup>1,</sup><sup>4</sup>  | pass<sup>1</sup> | 😞 
gpx | pass<sup>1</sup> | pass<sup>1</sup> | **fail** <sup>2</sup> | 💩 

<sup>1</sup> partial support, data could be altered, missing attribute, missing geometry
<sup>2</sup> driver error
<sup>3</sup> not yet available
<sup>4</sup> need SRS assignation

**Comment by thomaspiller** [comment]
I think the table summarizing the formats supported by MapX could be transferred to the wiki. This will make it easier to update and provide better visibility.
@fxi @antobenve If it's okay with you, I'll do this ASAP.

**Comment by thomaspiller** [comment]
The content of this issue has been moved to the wiki
