### ISSUE TITLE
Low priority bugs/glitches

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#414]
- [ ] Click on orange triangle related to metadata check: "Source missing" should be "Missing source" for coherency.
- [ ] Temporary access to db: At the end, the edited layer is displayed on map although the view is not toggled on -> Suggestion: toggle the view on too.
- [x] Story maps: slide content rule ('Value must be at least 3 characters') is not applied: the story map can be saved anyway. -> Suggestion: remove rule.

**Comment by thomaspiller** [comment]
Remaining items moved to other issues (see above).
