### ISSUE TITLE
Typo: MapX disclaimer

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#419]
"This site may contain links and references to third-party web sites. The linked sites are not under the control of UN Environment Programmme and UN Environment Programme is not responsible for, nor does it necessarily endorse, any of ***the their*** content."

Correction:
"This site may contain links and references to third-party web sites. The linked sites are not under the control of UN Environment Programmme and UN Environment Programme is not responsible for, nor does it necessarily endorse, any of ***their*** content."

**Comment by thomaspiller** [comment]
Fixed
