### ISSUE TITLE
Feature request: Add additional documents such as xls files as annexes to a dataset

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#42]
### Expected Behavior
When filling the metadata form, under "Annexes" it might be useful to also have an option for dropping files that are not stored under URLs.

### Current Behavior
Only URLs are accepted

### Steps to Reproduce

1. Create a new source.
2. Fill metadata
3. Go to "Annexes"
...

**Comment by alejandraarango** [comment]
For the moment the fields that are not online are stored in the owncloud and shared. This way you can have a url. See the source layer “River network” on AFG.

**Comment by antobenve** [comment]
The issue is closed because the item is reported in the list of improvements of issue #447
