### ISSUE TITLE
rev. v.1.5.42 testing

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#420]
Hi @fxi, I tested the new version locally and here are the bugs I found:

#### Non-blocking bugs:
- [ ] Get layer summary -> no stats is generated. The module that opens is empty.
- [ ] "Delete" button in "Manage sources" is not grayed, nor the message  "Deletion of a source disabled because at least one view depends on it" is displayed when the button is not active.

**Comment by thomaspiller** [comment]
Move to #427
