### ISSUE TITLE
Typo in the "Area Intersection Utilities" window

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#421]
The title of the window is the following "Aera intersection utilities"
_**Correction**_: "Area intersection utilities"

**Comment by MarionPlanque** [comment]
I bring this topic back

**Comment by MarionPlanque** [comment]
@fxi  @thomaspiller  Reminder for next week

**Comment by thomaspiller** [comment]
This typo will be fixed in the next version of MapX.
