### ISSUE TITLE
Metadata window: comments and suggestions

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#423]
The new version of the metadata window is great: clear, clean and comprehensive. 
The stats provided as well as the email addresses of the publishers are extremely useful.

_Comment:_
 For the moment, the source exists as a hyperlink in the title of the sources only. Two comments about this:

1. the hyperlink refers to the link of the "source homepage" in the metadata window; it is not a problem, but then we lose the specific hyperlink to retrieve the data. 

2. When there is no source mentioned in the metadata window, the title still contains a hyperlink which automatically sends users to the page of the MapX project. I think it can be confusing for the users.

**Suggestion**:  add two categories in the new metadata window to reflect both "homepage source" and "exact data source"; it would also allow avoiding the problem of the mapx hyperlink when the source is not mentioned since it would be clear that the source is NOT indicated for this dataset.

**Comment by MarionPlanque** [comment]
_Edit to that post:_
Still concerning the metadata window, but concerning the rasters this time, the link to the database containing the data is gone (like the preview one)
It would be good to put it back as it was a useful feature.

**Comment by thomaspiller** [comment]
Will be available in the next online version of MapX. Do not hesitate to reopen this issue if something does not work as expected.
