### ISSUE TITLE
Can't Submit a Join Reqest

### ISSUE THREAD

**Issue by swidnikk** [unep-grid/map-x-mgl#425]
# Summary
I attempted to join a project and received an unhandled error listed below

![image](https://user-images.githubusercontent.com/275252/57057094-84f54100-6c5b-11e9-8ba0-3e3720c2b257.png)

# Details
Chrome latest, OSX

**Comment by thomaspiller** [comment]
Hi @swidnikk,

I can not reproduce this error. Could you try again please?
If it fails again, could you click on _More info_ and post its content here.

Thanks.

**Comment by fxi** [comment]
@swidnikk, thanks for reporting this issue in MapX.

I close this issue as it's likely an isolated issue related to our provider blocking an automatic email. 
 
Please feel free to reopen it if needed !
