### ISSUE TITLE
Bug in story maps (or change in the logic): background color/opacity of the *slide* containing a photo now refers to the background color/opacity of the *photo* itself

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#430]
In the story map menu, there has been a modification of the "logic" of the slides containing photos.
_Before_:
If a slide contained a photo, and the slide indicated -for instance- Color: black/Opacity:0.5, these parameters were applied to the **slide**, meaning if the photo was full screen, these parameters had no effect on the photo, only on the slide containing the photo.

_Now_:
If a slide contains a photo, and the slide indicates -for instance- Color: black/Opacity:0.5, these parameters are now applied to the **photo** itself, meaning the photo has some sort of black/opaque "voile" covering it.

**Suggestion**: 
This new logic (or maybe it's a bug?) is quite confusing, the background parameters should apply to the slide itself like it was set before.

**Comment by fxi** [comment]
Solved. Front slide where kept behind background, solved in css. 
Will be available in next release !
Thanks for reporting this.

**Comment by MarionPlanque** [comment]
Great! Thanks!

**Comment by fxi** [comment]
It's not yet tested, so feel free to reopen it if the fix does not cover your cases.

**Comment by thomaspiller** [comment]
After some tests, the problem seems solved.
