### ISSUE TITLE
MapX disconnects during loading process if the "style" parameter is used in URL

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#431]
If MapX is loaded with a set url (previously set using the Sharing Manager module), the loading process stops immediately, the application disconnects and this message is sent in console:

```
[INF]: Connection closed. Info: {"type":"close","code":4503,"reason":"The application unexpectedly exited","wasClean":true}
```

[Here](https://app.mapx.org?style=eyJteF91aV90ZXh0IjoicmdiYSg1Myw1Myw1MywxKSIsIm14X3VpX3RleHRfZmFkZWQiOiJyZ2JhKDUzLDUzLDUzLDAuNSkiLCJteF91aV9oaWRkZW4iOiJyZ2JhKDIsMTg2LDI1MywwKSIsIm14X3VpX2JvcmRlciI6InJnYmEoMTU2LDE1NiwxNTYsMC40KSIsIm14X3VpX2JhY2tncm91bmQiOiJyZ2JhKDI1NSwyNTUsMjU1LDEpIiwibXhfdWlfc2hhZG93IjoicmdiYSgxNTMsMTUzLDE1MywwLjQpIiwibXhfbWFwX2JhY2tncm91bmQiOiJyZ2JhKDI1NSwyNTUsMjU1LDEpIiwibXhfbWFwX21hc2siOiJyZ2JhKDE1MywxNTMsMTUzLDAuNCkiLCJteF9tYXBfdGV4dCI6InJnYmEoNTMsNTMsNTMsMC45KSIsIm14X21hcF90ZXh0X291dGxpbmUiOiJyZ2JhKDI1NSwyNTUsMjU1LDAuNSkiLCJteF9tYXBfd2F0ZXIiOiJyZ2JhKDEwMiwxMDIsMTAyLDEpIiwibXhfbWFwX3JvYWQiOiJyZ2JhKDI1NSwyNTUsMjU1LDEpIiwibXhfbWFwX3JvYWRfYm9yZGVyIjoicmdiYSgyMjAsMjIwLDIyMCwwLjUpIiwibXhfbWFwX2J1aWxkaW5nIjoicmdiYSgyMjAsMjIwLDIyMCwwLjUpIiwibXhfbWFwX2FkbWluIjoicmdiYSgxMjcsMTI3LDEyNywxKSIsIm14X21hcF9hZG1pbl9kaXNwdXRlZCI6InJnYmEoMTI3LDEyNywxMjcsMSkifQ==&project=MX-2LD-FBB-58N-ROK-8RH) for a testing url.

**Comment by fxi** [comment]
Does it concerns only base64 encoded style or all parameters ?

The log you provided is unrelated : it's the websocket connection that's closed.

Thanks!

F

**Comment by antobenve** [comment]
As far as I could test, it's the style only that stops MapX from loading.

**Comment by antobenve** [comment]
Thanks. I will close the issue after testing it.

**Comment by antobenve** [comment]
Issue solved. I'm closing it.
