### ISSUE TITLE
WMS GetFeatureInfo bug when using a secondary style

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#434]
Hi @fxi , 

The GetFeatureInfo request does not provide values for the displayed pixels of a vector layer if the layer is displayed with other than its default style.

**Suggestion**:
Add the parameter "style" in  function `queryWms(opt)` and get the value from "styles" in the GetMap request that is being used.

**Comment by fxi** [comment]
Is this solved by 1.5.48 - and your pull request ?

**Comment by antobenve** [comment]
No @fxi , this is not solved with v.1.5.48. 
The current issue can be solved if the parameter "styles" is specified in the GetFeatureInfo request, and uses the value of "styles" that is used in the GetMap request. 
This implies that each GetFeatureInfo request is used for a maximum of 1 layer, for which we specify the style. This is not high priority btw.

**Comment by antobenve** [comment]
Solved in v.1.5.49 (evaluated locally)
