### ISSUE TITLE
SQL query maker: requests return 403 error

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#436]
SQL query is not generated after clicking "CREATE". The request returns a 403 error with the following message: 

> Bad request error: relation " < table id > " does not exist

A few tests were made and each time, the selected table was present in the database.

**Comment by thomaspiller** [comment]
Seems fixed in v1.5.48.
@antobenve Is it also ok on your side?

**Comment by antobenve** [comment]
Yes, perfect on my side too.
