### ISSUE TITLE
Data Mismatch Major mineral deposits of the world of tin, tungstene, tantalum, cobalt and gold (USGS - 2005)

### ISSUE THREAD

**Issue by erikcpost** [unep-grid/map-x-mgl#439]
In the data series Major mineral deposits of the world of tin, tungstene, tantalum, cobalt and gold (USGS - 2005), the data points for the gold deposits in Niger and in Eastern Mauritania are the other way around.

**Comment by fxi** [comment]
Thanks for reporting this.
@antobenve : can you investigate which project is linked to this layer and suggest a solution ?

**Comment by antobenve** [comment]
Dear @erikcpost ,
Thanks for your post. We will correct the error as soon as possible.

The dataset was downloaded from USGS. @MarionPlanque is contacting them in order to know what is the correct way to proceed license-wise.

**Comment by thomaspiller** [comment]
@antobenve has this view been corrected?

**Comment by antobenve** [comment]
No Thomas, we've never got the answer back from USGS. Thus the dataset either stays the way it is or I'll correct it my self. What would the right choice in your opinion?

**Comment by thomaspiller** [comment]
I think you can make the correction and indicate what you did in the "Additional notes" section of the metadata.

**Comment by antobenve** [comment]
It's done. I'm closing the issue.
