### ISSUE TITLE
Service Worker "quota exceeded" 

### ISSUE THREAD

**Issue by fxi** [unep-grid/map-x-mgl#441]
In some cases, service workers can't be used.

If this is linked to a lack of disk space on the client, we should unregister our service worker.

Add a rule in service worker init (`init_sw.js`) to test this, like that : 

```js

if ('storage' in navigator && 'estimate' in navigator.storage) {

     navigator.storage.estimate()
          .then(function(estimate){

               console.log(`Using ${estimate.usage} out of ${estimate.quota} bytes.`);

          });
     }

```

Logs reported by email by @antobenve.

**Comment by thomaspiller** [comment]
Tested locally in MapX v1.5.53.1, everything seems to work as expected.
