### ISSUE TITLE
Annexes of source layers are not displayed in the new metadata display panel.

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#443]
The new method for displaying metadata does not include the URL to annexes in 
`
"annex": {
    "references": []
  }, 
`

Suggestion:
Add the field "Annexes" in the "Summary of the source".
In case no annexe is provided, a "-" or empty line should be foreseen.

**Comment by thomaspiller** [comment]
@antobenve Bad timing on my part. I am merging this issue with #444
