### ISSUE TITLE
Metadata panel improvements

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#444]
- [x] Add annexes (with links) in _Summary of the source_ (see #443)
- [x] In _Contacts list_, if no value is provided for _Contact name_ or/and _Function_ in the metadata, we can end up with parentheses that are not relevant in the interface (e.g. neither is provided -> "()" ).
- [x] Replace "Raster metadata" by "Metadata Entry" #445

**Comment by MarionPlanque** [comment]
@thomaspiller Great thanks! I tried to do it but I couldn't edit your post

**Comment by thomaspiller** [comment]
@MarionPlanque Yep, you don't have the right to edit issues opened by other users but you can always leave a comment with your inputs.

**Comment by MarionPlanque** [comment]
True
I didn't even think about it :)
