### ISSUE TITLE
Metadata panel improvements (bis)

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#445]
Great for the updated version of the metadata panel!
Quick suggestions for some of the entries:

- [ ] Replace "Raster metadata" by "Metadata Entry"

**Comment by thomaspiller** [comment]
@MarionPlanque If you have items to add to an issue, write a comment in the issue rather than create a new one. It avoids to scatter the information.Thanks. Moved to #444
