### ISSUE TITLE
story map tips do not necessarly reflect the real constrainsts of the tool nor the good practices

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#449]
We should consider giving more general tips for the story map users, related to the length, the images, the data etc.
Happy to discuss this!

**Comment by thomaspiller** [comment]
I think there is no place in the interface to put all this information but as a solution, we can add a page dedicated to the story maps in the wiki.

**Comment by thomaspiller** [comment]
Story map tips have been updated lately.
