### ISSUE TITLE
Improvement : Table of attributes feature

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#451]
### Suggestion:
The feature "table of attribute" is great and allows to filter well the data/interact with the data.
However, I feel like two additional but **major** ways to filter data could be added:
- sort by alphabetical order (A to Z OR Z to A)
- sort by numerical order (lower to higher OR higher to lower values)

That would be extremely useful to better interact with the data.

**Comment by thomaspiller** [comment]
@MarionPlanque Columns can be sorted by alphabetic or numerical order by clicking on their header.

![Peek 2019-06-17 10-30](https://user-images.githubusercontent.com/19908801/59589810-0a895f00-90eb-11e9-9055-011b49833de8.gif)
