### ISSUE TITLE
Custom views from external projects are not accepted in story maps

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#452]
Hi @fxi ,
I spot a bug that concerns the use of custom code views in story maps:

- [ ] Custom views are not displayed in story maps if the custom view is published in an external project.

- The following error is thrown in console when the view should be displayed.
`TypeError: Cannot read property 'appendChild' of null
    at init (eval at <anonymous> (common.bundle.js:1), <anonymous>:160:24)
    at eval (eval at <anonymous> (common.bundle.js:1), <anonymous>:119:17)`

- Console for completeness
[custom_views_storymaps_app.mapx.org-1560328760395.log](https://github.com/unep-grid/map-x-mgl/files/3280572/custom_views_storymaps_app.mapx.org-1560328760395.log)

[edit by @fxi : avoid heading/titles for emphasis, simple list, italic or bold are better ]

**Comment by fxi** [comment]
This seems to be an issue with your custom view.

I don't have access to your custom view code, but there is high probability that there is something like:

```js
legendTitle = document.createElement("div");
legendTitle.innerText = "Legend";
legendTitle.style = "padding-left:10px; margin-bottom:10px;";
o.elLegend.appendChild(legendTitle);
```
If the legend block does not exists in DOM, which can occurs in story maps, o.elLegend will be null.

Please report back if that's the case.

**Comment by antobenve** [comment]
Hi @fxi, 
That's correct. The view has exactly that block. 

Should the code of the custom view be edited?
Thanks

Link to the custom code view: https://app.mapx.org/?project=MX-XNI-RMZ-KKL-FMS-DVH&views=MX-6M8ZV-4EJRP-GMHNS

**Comment by fxi** [comment]
Mmh, yes. Custom views are disconnected from the main application. Very flexible, but very unpredictable : MapX can't predict what will be done in custom view. In a custom view – or dashboard or story map – you can program a script that deletes the client side of the app and send to a remote server all users' data without MapX being able to do anything. 

Anyway, here is an example of code that could fix the issue (not tested ): 
```js
var h = mx.helpers;
if(h.isElement(o.elLegend)){
    legendTitle = document.createElement("div");
    legendTitle.innerText = "Legend";
    legendTitle.style = "padding-left:10px; margin-bottom:10px;";
    o.elLegend.appendChild(legendTitle);
}
```
`legendTitle` or another `o.elLegend.appendChild` could be referred elsewhere : read the code.

Try that and report back if this fixes the issue.

**Comment by antobenve** [comment]
I'm not able to test locally. If that's fine I'll test online tomorrow or in July locally. 
@fxi, Please let me know. I'm happy to help if I can.

**Comment by fxi** [comment]
@thomaspiller : if you can handle this before July, that would be awesome.

**Comment by thomaspiller** [comment]
Sure. I'll have a look at it ASAP.
@antobenve Can you add me to the editors of the custom code view please? Thanks

**Comment by antobenve** [comment]
Sure @thomaspiller, as soon as I have access to a computer tomorrow. But I guess you can try on other views as well. Try the earthquakes one for instance. I tried to use it and I got the same problem.

**Comment by antobenve** [comment]
@thomaspiller , you should now be able to access the custom code view's code.

**Comment by thomaspiller** [comment]
@antobenve The code provided by @fxi solves this issue. I updated some of the custom code views for which I have editing rights.
