### ISSUE TITLE
Suggestion map composer: generate a mapx logo

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#454]
The map composer is a great tool that allows creating easily high-quality maps.
To improve the tool, I would suggest generating automatically the mapx logo amongst the components to be arranged in the map.
It would help creating "official" MapX branded maps.

**Comment by antobenve** [comment]
Hi @MarionPlanque , this option was already discussed and discarded, the main reason being that maps generated in MapX should be as neutral as possible and therefore not to be featured with a MapX logo. 
@thomaspiller , if this is not in the to do list, should we close the issue?
