### ISSUE TITLE
Shapefile: zip file structure for a successful import

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#456]
ESRI Shapefiles being composed of multiple files, it's necessary to zip them in an archive to be uploaded in MapX. The files (at least: .shp, .shx, .dbf & .prj) should be located at the first level of the archive. 

If the files are not at the top level of the zip archive, the importation process will end up with an error that will be forwarded to the user by email and in MapX's interface.

**TO DO**
- [ ] add support for zip archives with files at the second level

**Comment by antobenve** [comment]
Support is added for drag and drop method.

**Comment by thomaspiller** [comment]
The content of this issue has been moved to the wiki.
