### ISSUE TITLE
Typo/rewording in the configuration window

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#458]
The configuration window contains the following option: "Allow nonmember to request a membership to this project"

The text could be replaced by: "Allow non-members to request access to this project"
![image](https://user-images.githubusercontent.com/25179050/60336074-a5adee80-999f-11e9-96fd-d663689b15cf.png)

**Comment by thomaspiller** [comment]
This typo will be fixed in the next version of MapX.
