### ISSUE TITLE
Issue: attribute table functionality not available in Firefox and Edge

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#459]
The functionality "attribute table" is not supported by Firefox nor Edge, only by Chrome and Safari (version 12.1.1).
_Suggestion_: all the functionalities and MapX, in general, should be supported the same way by all browsers to avoid discrepancies between users

**Comment by fxi** [comment]
It seems to be fine on Firefox.

Which version do you use ?

![image](https://user-images.githubusercontent.com/1196833/60342216-21fcfd80-99b1-11e9-99cc-288c314c9da1.png)

**Comment by MarionPlanque** [comment]
![image](https://user-images.githubusercontent.com/25179050/60342409-abaccb00-99b1-11e9-8adc-a814003e3675.png)

Version 63.0.3 (64-bit)

**Comment by thomaspiller** [comment]
I tried on my side and it works on Firefox 67.0.4 (Windows 10) but not on Edge 42.17134.1.0.

**Comment by MarionPlanque** [comment]
And for Edge: Microsoft Edge 41.16299.1004.0

**Comment by fxi** [comment]
@MarionPlanque you have to update firefox: 63 is nearly one year old. Keeping your browser up to date is important for security reasons.

@thomaspiller : it does not work on Edge 42 ? Can you give me the EdgeHTML version ?

*Solutions :* 
- I can modify the code to avoid ReadableStreams. 
- I can add a polyfill : https://www.npmjs.com/package/web-streams-polyfill

Thanks for mentioning this.

F

**Comment by thomaspiller** [comment]
No, it doesn't work on Edge 42 (Microsoft EdgeHTML 17.17134).

I got that message (nothing in the web console):
![image](https://user-images.githubusercontent.com/19908801/60343291-f0396600-99b3-11e9-9bca-f479bfd561c4.png)

**Comment by MarionPlanque** [comment]
@fxi Indeed, I can easily fix this issue by updating my browser (and I will), but I'm more worried about the other users who don't know that it's linked to the version of their browser **or** who don't know how to update their browser (we have to think about all types of users), **or** who are just not "committed" enough to undertake some browser updates

I don't know if there are some solutions to "open" this functionality to all versions of browsers, but if not,  we should at least propose some mitigation measures:
- a clear message indicating the problem, like "Hi, it seems that you're using a version of XXX that is too old for this functionality. 
- a quick explanation on how to solve the problem: "Please download the latest version of your browser. Click on the menu icon on the top right corner of your browser window and  bla bla bla"
- if it doesn't work/users don't have time etc, propose a plan B, like: "Try to open MapX on another browser"

**Comment by fxi** [comment]
In my last message, I proposed two solutions, if you did not notice. Both of them will solve this issue.

I will not add custom messages in such specific cases if there is a seamless and easy solution.

Then, Firefox users seem very quick to adopt new versions. Here is a graph I've made with the latest available usage data  : 

![image](https://user-images.githubusercontent.com/1196833/60345100-84a5c780-99b8-11e9-9357-61f3fbfa7b66.png)
_World Firefox marked share by browser version in percent (2019-06-28). Source_  : http://gs.statcounter.com/

It's not possible to cover all users. That's a fact. But we have to cover most cases, I agree.

**Comment by MarionPlanque** [comment]
@fxi Oops, my bad, I didn't see your response indeed
If there is a technical solution, it's great!

**Comment by PierreLacroix** [comment]
Not priority 1 as it works on recent versions of FF and Microsoft Edge not officially supported by MapX

**Comment by fxi** [comment]
@PierreLacroix Maybe you rather wanted to write Internet Explorer instead of Edge, am I wrong ?
In all cases I rewrote the code that uses `ReadableStream` and used the classic `XMLHTTPRequest` method instead.
This should be available in the next version.

**Comment by thomaspiller** [comment]
@MarionPlanque Is this still not working?

**Comment by thomaspiller** [comment]
I close this issue as it is inactive for a while.
