### ISSUE TITLE
Size limit for the file upload

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#460]
As no size limit is set for the file upload, big datasets can be uploaded in MapX. Lately, two 5GB GeoJSONs were uploaded in MapX and they generated an error when trying to create views based on them ([More info](https://stackoverflow.com/questions/38288436/error-array-size-exceeds-the-maximum-allowed-1073741823)): 
```
ERROR: array size exceeds the maximum allowed (1073741823). 
```
**TO DO**
- [x] Add a size limit for the file upload

**Comment by fxi** [comment]
There was already a file size limit, but I've generalised that between form and geojson upload : 
- Use same validator; 
- Translated message; 
- Modal window;
- Stop as early as possible in the process.
