### ISSUE TITLE
Attribute table improvements

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#461]
- [x] change the style of the arrow to increase visibility when a filter is enabled
- [x] add a button to reduce/expand the modal panel
- [x] visualize in the panel the filters set by the user 
- [x] remove the possibility to download the data in csv if the option "allow download" is not selected in _Manage source_

**Comment by fxi** [comment]
The "visualize on the panel the filters set by the user" is already there : the caret in the filtered column becomes green if there is a filter set, the filter dropdown is pretty clear and the map features are filtered dynamically, which should be visible.

If you want a complete rules visualization interface – which would duplicate the one already there –  this is on another level: it's not an easy task to produce such a thing. It's not done within the hour. The rules are returned as a hierarchical structure. There is very little space in the modal. The translation is not trivial. This is, in my opinion, an overkill request. 

The reduce/expand button is done. 

For the download button, I've implemented what you wanted, along disabling direct selection, but it does **NOT** prevent the user to accessing the data, as I already said. The  attribute table data could still be fully acquired by anyone with a basic understanding of the web using : 
- A replay of the request,
- By extracting data from the map,
- By accessing the data from the hot object,
- By using the helper in the console;

@PierreLacroix Please make sure this last point is fully understood before releasing the new version.

**Comment by fxi** [comment]
Quick clarification:

When I said this : 
> For the download button, I've implemented what you wanted, along disabling direct selection, but it does not prevent the user to accessing the data [...]The attribute table data could still be fully acquired by anyone with a basic understanding of the web using [...] :

It does not mean "security breach" : this is how the web works. If you can access a document and display it on your screen, you can also store it, with minimal knowledge.

In MapX, you can always restrict target readers by settings that parameter in the view or source configuration panel.

**Comment by MarionPlanque** [comment]
@thomaspiller @fxi 
Change the color of either the 'filter' arrow or of the top cell of a column when a filter is activated
_Suggestion_: inversion of colors in the arrow

**Comment by thomaspiller** [comment]
I just added previous comment to the bulleted list.

**Comment by fxi** [comment]
![mx_attribute_table_filter_visibility](https://user-images.githubusercontent.com/1196833/65250804-75857000-daf6-11e9-8240-c14d242628e8.gif)

**Comment by MarionPlanque** [comment]
Great thanks!! 
But does it move?? I am not sure I see well...

**Comment by fxi** [comment]
It oscillates :) I can remove that or limit the number of oscillations. It could move 5 times then stop or continues forever. I can make it grow or shrink. I can make it pink.

**Comment by MarionPlanque** [comment]
I would say no permanent oscillations, it makes me a bit seasick :)
Why not a couple of oscillations at the beginning? and then repeat it once every minute?

**Comment by fxi** [comment]
I've pushed a version with only five oscillation at start. 
Repeat every minute is a little bit more complicated to do. It's doable : [delay between anim](https://css-tricks.com/css-keyframe-animation-delay-iterations/).

**Comment by MarionPlanque** [comment]
It's doesn't matter, what is important is that it doesn't oscillate all the time not to make users seasick :)
Thanks!
