### ISSUE TITLE
Wiki: add a section about the map composer

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#462]
- [x] add a section in the wiki about the map composer with clear explanations on how to use it to create and export maps
- [x] add a link to the wiki in the map composer modal panel

**Comment by MarionPlanque** [comment]
@fxi @thomaspiller Add a "?" button at the bottom of the window that sends to the wiki github page

**Comment by fxi** [comment]
I've added a "help" button which points to our wiki : 

![mx_help_button_map_comp](https://user-images.githubusercontent.com/1196833/64683284-45e5c080-d483-11e9-88d9-d71c46215b43.gif)

**Comment by MarionPlanque** [comment]
@fxi Great! However, the button is called "Aide".... Maybe "Help" instead? :-D

**Comment by fxi** [comment]
@MarionPlanque That's a translated. Map Composer is not yet fully translated but this button is.

**Comment by thomaspiller** [comment]
The wiki has just been published and the link in the map composer will be released in the next update.
