### ISSUE TITLE
Download links are not valid

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#466]
After requesting a dataset in MapX (tool:_Download the data_), the download link received via email is not valid:
_https://api:3030/download/....zip_ should be _https://api.mapx.org/download/....zip_

**Comment by fxi** [comment]
Thanks for reporting this. 
I've solved this issue 10 days ago (green label), waiting for feedback (blue label) from the test version:

![image](https://user-images.githubusercontent.com/1196833/64845258-fd0c4400-d609-11e9-8458-4d6ef63f74b6.png)

**Comment by thomaspiller** [comment]
Works well in the dev version of MapX. The patch will be available in the next update.
