### ISSUE TITLE
WDPA attributes return  No Value

### ISSUE THREAD

**Issue by scabecks** [unep-grid/map-x-mgl#468]
When a WDPA View (or any other View based on the WDPA - e.g. MPAs) is activated the polygons draw fine, but when clicked upon any and all attributes for any polygon are simply `[No value]`. No errors appear in the console. Is this expected behaviour?  

Occuring on Firefox (68.02) and Chrome ( 76.0.3809.100) Running Linux Mint 19.2.

**Comment by fxi** [comment]
Thanks for reporting this.
Is this related to all type of views or custom views only (color red) such as :

![image](https://user-images.githubusercontent.com/1196833/64164183-0267d280-ce43-11e9-91c5-1f9c4068d391.png)

**Comment by scabecks** [comment]
Nice Aussie location in the screenshot... It's only custom views. I may have been making it up in my head that the attributes used to be returned in these Views - speaking with Antonio that may be the case. If that is indeed the case (values were never returned) I'd put that in the category of a very much non-priority nice functionality to have in MapX in future.

**Comment by thomaspiller** [comment]
Fixed in the new version of MapX.
