### ISSUE TITLE
Suggestion/Improvement: Inconsistency between "transparency" and "opacity"

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#470]
The legend window and the "transparency" filter use two different terms to describe a same concept, the one of transparency/opacity.
Suggestion: in the legend window, switch from "Opacity" which is not the most intuitive, to "Transparency" as it is the concept most people are familar with.

**Comment by MarionPlanque** [comment]
@thomaspiller Sorry, I didn't understand: as this been implemented for the new version or simply shut down?

**Comment by fxi** [comment]
@MarionPlanque : it's mentioned in #327 : 

![image](https://user-images.githubusercontent.com/1196833/64037334-a4db3980-cb55-11e9-9b35-d10b620ff905.png)

**Comment by MarionPlanque** [comment]
Got it! Thanks
