### ISSUE TITLE
Arguments specified in the URL remain active

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#472]
All arguments specified in the URL remain active after a change of project.

Two solutions are available to solve this issue:
1. add a new argument "cleanUrl" to list what must be removed from the URL during a change of project
2. add a button in the UI that -1- indicates that views are currently filtered and -2- allows users to load all the views available in the project

A combination of these two solutions can also be considered.

**Comment by thomaspiller** [comment]
@PierreLacroix @antobenve Is this a "Priority 1" issue? Which solution do you like the most?

**Comment by fxi** [comment]
Third solution: 

Preset two groups : 

1. Permanent parameters – remain in url even after relaunch

- `lat`
- `lng`
- `project`
(...)

2. Temporary parameters – automatically removed after first load 

- `views`
- `collections`
- `collectionsSelectOperator`
- `requestMembership`
- `showProjectsListByRole`
- `showProjectsListByTitle`
- `lockProject`
(...)

Notes : 
- This solution assumes that users don't copy / paste URL and use only the sharing manager. 
- Many parameters will be deprecated once the SDK is stable

**Comment by PierreLacroix** [comment]
Third solution seems fine for me.

**Comment by antobenve** [comment]
I'm pro 3rd option too because it is like the previous behaviour - if I understand well. UNDP might benefit from not needing to change the way they build their URLs in the UNBL website.

**Comment by fxi** [comment]
@antobenve Could you just wrap up the list I've started ? Maybe as a table such as:

key | permanent | temporary
-- | -- | --
lat | x  | |
lng | x |  |
project | x |  
views |   | x
collections |   | x
colectionsOperator |   | x
language | x |  

Looking at this, it's quite obvious than only project and language should be kept.. Maybe lockProject ?

**Comment by antobenve** [comment]
Sure @fxi . 

key | permanent | temporary
-- | -- | --
lat | x |  
lng | x |  
project | x |  
views |   | x
collections |   | x
collectionsSelectOperator|   | x
language | x |  
requestMembership |   | x
showProjectsListByRole |   | x
showProjectsListByTitle |   | x
lockProject | x |  
noViews |  | x
storyAutoStart |  |  

In the online version, "storyAutoStart" is kept. I would remove it unless the "views" and "project" parameters are also kept in this specific case. This would allow users to reload the URL or sharing it to thirds in an easier way.

"lockProject" could be a good idea. It would avoid users navigating through projects if they switch to another project through the "House" button associated to a view.

**Comment by fxi** [comment]
@antobenve Could you add `action` in temporary and `style` in permanent ?

**Comment by antobenve** [comment]
@fxi, I included the two parameters in the list in message above.

**Comment by fxi** [comment]
@antobenve There is also `zoom` which is needed for `lat` and `lng`. 

This improvement revealed some inconsistencies.. Some search parameters have an impact on behavior after the application is launched. I've added a system to remove non-permanent argument when the application start and store the initial parameters in `mx.initQueryParams` which can be queried later. This storage is cleared after the next project change to match wanted behavior.
Permanent/temporary search parameters settings are currently stored in [mx_settings_default](https://github.com/unep-grid/map-x-mgl/blob/master/app/src/js/mx_settings_default.js#L35).
I'm not sure I've covered all cases and this will be modified again after the SDK.
Changes are available in [`1.6.7-beta`](https://github.com/unep-grid/map-x-mgl/releases/tag/1.6.7-beta).

**Comment by antobenve** [comment]
Hi @fxi , zoom is added to the above table as permanent parameter in line with lat and lng.

**Comment by fxi** [comment]
Is that still an issue ?

**Comment by antobenve** [comment]
I'm going to check this afternoon the 19 one and let you know.

**Comment by antobenve** [comment]
It seems that everything works fine except for:
- [ ] "zoom", "lat" and "lng" are maintained in the URL but they are not used when the project is changed through the interface, nor their values are updated.

I think they should either be removed from the URL, or their value be updated with the geographic centroid of the new project when a new project is loaded.

**Comment by thomaspiller** [comment]
@antobenve Is everything ok now? Can I close this issue?

**Comment by antobenve** [comment]
Sure @thomaspiller , it seems perfectly fine for me.
