### ISSUE TITLE
Dashboards: only MapX team should be able to access the dashboard edition button

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#477]
Currently, all users with publisher rights for a view can access and open the dashboard menu to create new dashboards.
As dashboards can be coded in Html only, only members of the MapX team with coding skills should be able to access this button. It is quite confusing for users with publisher rights otherwise (they want to create dashboards but they can't, and more important, they can try to code something and create severe bugs...)

**Comment by fxi** [comment]
Dashboard and custom views are coded in `JavaScript`, not `HTML`. You can generate `HTML` in `JavaScript`, but the language used in `JavaScript`.

I think it's good to let people play with code in dashboard and custom views. That could lead to new fun things : there is no limit to what we can create in those views.

But I agree that's bad if something not working is published : the project and even the current session could be compromised. Project managers and publishers should be aware of that. Custom views and dashboards are not sandboxed. That could also be a security threat.

I could add a select box in the project configuration to select trusted publishers that are able to code. 

@PierreLacroix: what do you think ?

**Comment by PierreLacroix** [comment]
Better to discuss it orally than on GitHub. This issue does not have only technical aspects.

**Comment by thomaspiller** [comment]
This subject will be discussed internally by the development team. I therefore close this issue.
