### ISSUE TITLE
Issue: Metadata are not displayed with the good format (as they were prepared)

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#48]
### Expected Behavior
 Text content of source's metadata should have white lines if they were entered in the metadata. 

### Current Behavior
When the source's metadata of a view is visualized, all the text fields are formatted in a way that no white lines are present.

### Steps to Reproduce
1. Select a view (i.e. for Afghanistan: Total population per district in 2016-17 (OCHA - 2016))
2. Select Display metadata
3. Check the abstract field i.e.
...

**Comment by antobenve** [comment]
Furthermore, I have realized that information such as keywords is not shown when Source's metadata are displayed from a view.

**Comment by antobenve** [comment]
The formatting problem persists in the new version.
Check the abstract of view "Urban population per province in 2016-17 (OCHA - 2016)" for example.

The other problem is instead solved. Metadata such as language and keywords are now shown.

**Comment by fxi** [comment]
Ok. What do you mean by white lines ? New lines aka end of line ?

**Comment by antobenve** [comment]
Yes, empty lines that were created between paragraphs do not appear when the metadata is visualized. Paragraphs are then all attached and it is difficult to distinguish between them.

**Comment by antobenve** [comment]
This issue is still present and is also expressed in the way the abstract of views is shown. Thus, text from source metadata and view information is expressed without following the layout that was conceived during their preparation.

![paragraphs in abstract](https://user-images.githubusercontent.com/30286565/33549177-f0a698ec-d8e9-11e7-8b9f-9ef5484ed19d.JPG)

**Comment by thomaspiller** [comment]
Not relevant anymore as a new metadata visualization system has been set up.
