### ISSUE TITLE
URL is not updated when loading brand-new projects

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#481]
After the creation of a new project, clicking "Load new project" doesn't update the URL accordingly. This is not in line with the usual behaviour of the application when projects are loaded.

**Comment by thomaspiller** [comment]
This seems to be solved in version 1.6.23. @antobenve Do you confirm?

**Comment by antobenve** [comment]
Confirmed. I'm closing the issue as well.
