### ISSUE TITLE
Bug: views can't be opened by clicking on the button, only by clicking on the title

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#484]
The views can not be opened by clicking on the button, only by clicking on the title of the views.

Edit: it may be only on my side (poor connection/bad processor), could you please check if it's the case on your side too?

**Comment by antobenve** [comment]
Hi @MarionPlanque , I confirm that I don't have this issue and that it might be on your side. Are you having errors on your console when clicking on the button?

**Comment by MarionPlanque** [comment]
![2019-10-16_13-26-43](https://user-images.githubusercontent.com/25179050/66915170-ab941200-f018-11e9-97df-8d74251f9803.png)
 Here it is!

**Comment by fxi** [comment]
Thanks for reporting this strange bug.

- Right click on the logs,
- "Save as",
- Drag the file in a new comment.

![mx_copy_logs](https://user-images.githubusercontent.com/1196833/66916089-d0898480-f01a-11e9-8fb4-45cc9ba28b0e.gif)

**Comment by MarionPlanque** [comment]
Ok, it's weird: it doesn't happen all the time. Right now, no problem for instance.
Should I follow up on that or do you assume that it's just my laptop/connection?

**Comment by fxi** [comment]
mmh, maybe your computer has its own will.

Have you tried "Expelliarmus" ?

**Comment by MarionPlanque** [comment]
I tried "Impero" but it didn't work...

Maybe I should let it go and flag it if it ever happens again?

**Comment by fxi** [comment]
Yep. You can do this. As said, copy + pasting full logs could help also.

Thanks!

**Comment by fxi** [comment]
Yep. I've done some tests with different browser, it does not seems to happen.

**Comment by thomaspiller** [comment]
@MarionPlanque Is this still an issue?

**Comment by MarionPlanque** [comment]
Nope!
