### ISSUE TITLE
MapComposer doesn't load for some specific custom code views

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#485]
Hi, the map composer won't load if any of the following custom code views is active on map. 
[USGS Earthquakes](https://app.mapx.org/?language=en&project=MX-XVK-HPH-OGN-HVE-GGN&views=MX-YLZJG-JAIID-V27X5) 
[Climate projections](https://app.mapx.org/?language=en&project=MX-5Z8-45E-K4I-SKH-75H&views=MX-6EH7N-INM1L-P1PJ9)

The following error is sent on console:
`Uncaught DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.`

[Console log](https://github.com/unep-grid/map-x-mgl/files/3735006/mapcomposer.failure.log)

 Other custom code views and other types of view do not provoke the error.

Tested locally and online.

**Comment by thomaspiller** [comment]
This issue seems solved on my side. @antobenve Is that also the case for you?

**Comment by antobenve** [comment]
Yes @thomaspiller . It seems all fine. Thanks. I'm closing it.
