### ISSUE TITLE
Map composer: high resolution deformations

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#487]
_This issue is Chrome specific and could not be reproduced in Firefox._

At high resolutions (> 400 dpi; seems to vary depending on the resolution of the screen), the map becomes distorted regardless of the mode selected in the map composer (layout or preview). The size of the map remains the same when the resolution is changed.

When the map is exported, the size of the map is different than in the map composer and is no more distorted. See below:

**Map composer**
![map_composer](https://user-images.githubusercontent.com/19908801/67771034-cc685880-fa57-11e9-9ecf-ce2fc6840e5e.jpg)

**Export**
![export](https://user-images.githubusercontent.com/19908801/67770942-a478f500-fa57-11e9-8d00-179fb08778db.jpg)

--------
MapX 1.6.21-beta (local)
Linux Mint 19.2
Chrome Version 78.0.3904.70 (Official Build) (64-bit)

**Comment by fxi** [comment]
@thomaspiller This should be fixed. If it's ok, please close the issue.

**Comment by thomaspiller** [comment]
Unfortunately, it is still unsolved. 

Steps to reproduce this issue:
1. open the map composer
2. change map dimensions
3. switch from px to in
4. increase dpi from 96 to 300

**Comment by thomaspiller** [comment]
This specific issue is solved in the current version of MapX. Remaining glitches are listed in #437.
