### ISSUE TITLE
Name of the filters.collections/etc is not visible anymore

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#489]
After the new version has been pushed, the name of the collections and filter has disappeared in the filter window

![image](https://user-images.githubusercontent.com/25179050/67941823-c77de300-fbd6-11e9-95a3-08839f5ff599.png)

**Comment by antobenve** [comment]
I actually have everything fine in Chrome on my computer. Do you have any error in Console during the installation / during the filtering process?

**Comment by MarionPlanque** [comment]
Seems good to me!

**Comment by thomaspiller** [comment]
Perfect. I close this issue.
