### ISSUE TITLE
Suggestion: add a close button to the filter window

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#490]
A close button would be convenient in the filter window to indicate more easily to users how to close it

![image](https://user-images.githubusercontent.com/25179050/67941920-f005dd00-fbd6-11e9-95c4-71ec1dd049bf.png)

**Comment by MarionPlanque** [comment]
Just to let you know that I've seen users using this tool and I confirm that they were looking for a cross or a close button :)

**Comment by thomaspiller** [comment]
This issue is not relevant anymore as the "Advanced filter" modal was redesigned in MapX 1.6.60.
