### ISSUE TITLE
Map composer: devicePixelRatio issue

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#492]
When the map composer is open and the map size is set using resolution and physical measurements, the devicePixelRatio is updated based on the dpi value provided by the user. At high dpi (~ 300 and more), if the map is resized, the devicePixelRatio value used is the updated one and not the actual value of the screen. As a result, the map becomes distorted and fuzzy.

Once the map composer is closed, the devicePixelRatio regains its normal value and a change in map size will make it shape again.

@fxi Not so easy to explain, I hope it is clear enough.

**Comment by fxi** [comment]
Yep. `devicePixelRatio` issue. I have to find a more reliable way to define temporary 'devicePixelRatio' : [see source](https://github.com/unep-grid/map-x-mgl/blob/6563d9b5a6ad884af9a61d583f7c281391c31f2b/app/src/js/map_composer/index.js#L172 )

**Comment by fxi** [comment]
@antobenve I don't think this should have the 'done' tag: it's still there. 

I've seen that what trigger the main map to render is the ... download bar in Chrome. It alters the size of the browser's window which forces the map to shrink. As the device pixel ratio was altered at this time to produce the correct MapComposer output, the main map get the wrong devicePixelRatio and look blurry or too sharp.

**Comment by antobenve** [comment]
@fxi, sorry. I think I made a mistake with another issue because I don't remember having set this label here. I'm removing the label in order to keep it active.

**Comment by fxi** [comment]
I don't think there is a solution here. I've added a background `<div>` in the map composer panel to hide the main map when the map composer is visible. As both map are on the same window and the window size can change, both map will read the same devicePixelRatio. As we need to render map composer map to reflect the resolution set by the user, this will impact the main map.
The solution should be an option in  `mapbox-gl`, as requested here : https://github.com/mapbox/mapbox-gl-js/issues/1953

Please add your +1 there if you want this to happen in MapX.
