### ISSUE TITLE
Edit accesses for views that are assigned by user ID are not evaluated (edit button is missing in views' panel)

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#494]
If a user is given edit rights over a view by specifically setting his account in the "edit access" field, the edit button of the view is not displayed for that user.

**Comment by fxi** [comment]
@antobenve This is the current logic : 
```sql
  (
    p.u_is_publisher AND (
      ( v.editor = {{idUser}} ) OR
      ( v.editors @> '[{{idUser}}]'::jsonb ) OR
      ( v.editors ?| array['publishers'] ) OR
      ( p.u_is_admin AND v.editors ?| array['admins'] )
    )
  )
```
I think this is correct. 
What you want is
```sql
  (
    v.editors @> '[{{idUser}}]'::jsonb OR
    p.u_is_publisher AND (
      ( v.editor = {{idUser}} ) OR
      ( v.editors ?| array['publishers'] ) OR
      ( p.u_is_admin AND v.editors ?| array['admins'] )
    )
  )
```
That is more a feature request than a bug.

**Comment by fxi** [comment]
Oups, it's rather this one:

```sql
  (
    v.editors @> '["{{idUser}}"]'::jsonb OR
    p.u_is_publisher AND (
      ( v.editor = {{idUser}} ) OR
      ( v.editors ?| array['publishers'] ) OR
      ( p.u_is_admin AND v.editors ?| array['admins'] )
    )
  )
```

**Comment by fxi** [comment]
Ready to be tested in 1.6.25

**Comment by antobenve** [comment]
As this was possible in the version available online before the latest update, I thought it was an unwanted behaviour. 
I just tested your correction and it seems all ok. Thanks. I'm also closing the issue.

**Comment by fxi** [comment]
Ok. As a side note, the logic is fully described in this file : [getViewsByProject.sql](https://github.com/unep-grid/map-x-mgl/blob/master/api/templates/sql/getViewsByProject.sql)
Feel free to explore that 🔬
