### ISSUE TITLE
autoStart option doesn't allow private story maps to be played by public users

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#495]
When sharing a story map with external users, the "auto start" option doesn't work anymore. It seems that it has been replaced by the "start when open" mode.

**Comment by antobenve** [comment]
I confirm. I can reproduce this issue as well. 

The result of opening the link of a story map with autoStart mode ON which is located in a private project is the loading of the default project with no views in it.

**Comment by fxi** [comment]
Ready to be tested in 1.6.25

**Comment by antobenve** [comment]
It seems fine to me. The issue will be closed when the function will be available online.
