### ISSUE TITLE
onClose event does not always clean data of custom code view on real time fires

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#497]
The data is not cleaned at onClose if the cc view is toggled off after another view is toggled off.

[View ](https://app.mapx.org?project=MX-XVK-HPH-OGN-HVE-GGN&viewsOpen=MX-6BI2W-R1HNH-THYSG)

**Comment by thomaspiller** [comment]
I just updated the view. This issue should be solved. 
@antobenve Can you check if it is the case?

**Comment by antobenve** [comment]
It seems perfect to me. Thanks.
