### ISSUE TITLE
URL is not correct in Share module if a story map was previously shared using storyAutoStart

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#500]
The proposed URL in the "Share" module of any view is not correct if a story map was previously shared using this method. 
The new link has the correct view ID, missing project ID, it employs "views" at the place of "viewsOpen" and the "storyAutoStart=true" piece.

![storyAutoStart](https://user-images.githubusercontent.com/30286565/68230172-db6f7d80-fff8-11e9-94c0-439f3b45bb74.gif)

**Comment by fxi** [comment]
This should be "solved" by the new share module, no ?

**Comment by antobenve** [comment]
Yes, it is not relevant anymore. I can close the issue. Thanks
