### ISSUE TITLE
Tiny bug: the mouse pointer doesn't indicate that the view scroll bar can be selected

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#502]
When a view is open, the scroll bar to read the abstract can not be easily grabbed: the mouse pointer doesn't indicate that the bar can be selected. (i.e. the "hand" remains open)

_Suggestion_: the hand turns into a finger (like when clicking on a hyperlink in the abstract) or the hand is closed on the scroll bar

**Comment by antobenve** [comment]
An arrow is present when moving across the abstract and its scroll bar. Only the title has the "hand" symbol. I'm closing the issue.
