### ISSUE TITLE
Bug: Interractive map is not working in the story maps

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#503]
In a story map, when the map is unlocked, the data can not be queried anymore. Clicking on a map feature doesn't open the attribute window anymore.

**Comment by fxi** [comment]
Seems to be fixed in 1.6.31

**Comment by thomaspiller** [comment]
This issue is solved in the online version.

**Comment by MarionPlanque** [comment]
Yes, works perfectly now
Thanks!
