### ISSUE TITLE
Bug: the search fonction "filter views" is not applicable to views in *sub* categories

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#504]
When views are aggregated in categories, they can be filtered, but when they are aggregated in sub-categories, they can not be filtered anymore.

Edit: same problem with "Filter activated views": it is only possible to see the views in categories, not in **sub** categories.

**Comment by thomaspiller** [comment]
Duplicate of https://github.com/unep-grid/map-x-mgl/issues/493#issuecomment-549874704 ?

**Comment by MarionPlanque** [comment]
No: bug 493 was about the filters applied to the categories
This one is about filter by "Search a view" in **sub** categories

**Comment by fxi** [comment]
Seems to be working in version 1.6.31. Even is nested sub categories.

![mx_filter_sub](https://user-images.githubusercontent.com/1196833/69161089-e80ccf00-0aea-11ea-893f-b37d08b4e5da.gif)

**Comment by thomaspiller** [comment]
This issue is solved in the online version.
