### ISSUE TITLE
Bug or logical?: conflict of views order saved

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#505]
I noticed the following situation, could you please indicate if this is a bug or the normal "logic" of the new MapX update with the categories?

If:
1) A user (any type of user privileges) saves views **locally** in a certain order
2) Then, the administrator saves the views **permanently** in another order
3) The views for the normal user will appear as he/she saved them, NOT the order from the administrator.
4) If he/she wants to see the order set by the administrator, he/she can click on "reset original state".
5) If the page is refreshed, reloaded etc, the order of the views will be **again** the one set by the **normal user**, not the administrator one

--> "Reset original state" doesn't have a permanent effect, the order of the views **always** comes back to the one **set by the user**. Normal or not?

**Comment by antobenve** [comment]
Hi @MarionPlanque , I will leave the logical to @fxi because he is certainly more qualified than me in describing it. 
However, as you have well described, the user can save locally whatever order in the panel he has. This also includes the order that is generated temporally when clicking "Reset original state". 
Do you think this last part should be omitted and the process of resetting to the default status overrun the locally saved status by default?

**Comment by MarionPlanque** [comment]
"the user can save locally whatever order in the panel he has. This also includes the order that is generated temporally when clicking "Reset original state"."

I see what you mean, I didn't think about it this way, but I guess this is the logic behind! That's why I wasn't sure whether it was a bug or simply very logical :) 

"Do you think this last part should be omitted and the process of resetting to the default status overrun the locally saved status by default?"

--> I don't know actually, I'm not sure that my logic would be better at all, especially now that you explained me the logic behind the current behaviou... Let's see what @fxi thinks!

**Comment by fxi** [comment]
I would recommend to discuss this with other users and see what they prefer. Describe a complete working logic and I will implement it.

**Comment by thomaspiller** [comment]
"Reset original state" has a permanent effect and "Using last action" allows to revert back to the order defined by the user.
