### ISSUE TITLE
Problems with the "download" function

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#507]
When downloading a dataset, the zip folder is not downloaded automatically as it used to be.
Users must now click on the "click here" green sentence at the bottom of the download window at the end of the download process. It is a problem because:
1. the content of the download window doesn't scroll down automatically to the end of the text where the user could see the sentence "click here to download". The window displays only the beginning of the text which may not be user-friendly.
2. it is much less intuitive

_Suggestion_: the dataset should be downloaded automatically at the end of the download process without clicking on anything.

Also, users receive an email containing a link to download the data, but the link doesn't work and says (for me) "Cette page ne fonctionne pas".
Link: http://api.mapx.org:443/download/mx_dl_5x1d2_rL6mL_FMGfj_iTwKb.zip 
Console: there is nothing written in the console

**Comment by MarionPlanque** [comment]
@fxi I see that you tagged this bug under "done", will it be pushed in the next version?

**Comment by fxi** [comment]
I think this was solved by 82e90d6874b1eeada0ddfd49d19cfb8cfc0537c8
It should be available next week, in the next update, with a lot of other things.
