### ISSUE TITLE
Add non-geospatial dataset support

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#508]
- [x] API: new route to upload non-geospatial datasets (csv, xls & xlsx)
- [x] new type of source with metadata (without _Spatial_ section)
- [ ] new type of view (tabular ?)

**Comment by thomaspiller** [comment]
It is now possible to upload tabular data in MapX from the toolbox using the upload tool.
Data must be in CSV format.
Even if the CSV has a geospatial component (e.g. lat/lng columns), no geometry will be generated in the process.
For now, 'tabular' source in MapX are non-geospatial.

**Comment by fxi** [comment]
The last step is a bit more complicated. 

Which features are expected for a "tabular view" ? Join with any other table or at least countries ? 

- Edition
    - Title
    - Description
    - Other projects
    - read access
    - edit access
    - collections
    - source tabular
    - source geom + COUNTRIES UN
    - join attribute name ( optional )
    - other columns (optional )  
- Style if geom source + join column are selected, then same features as "vector tiles"
- Download
-  Zoom to visible
-  Attribute table visualisation ( could be a good opportunity to enable "edit attribute table")
- All other view's button ( zoom, meta, reset, opacity, filter )
