### ISSUE TITLE
Bug story map with custom views

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#511]
To be investigated, I'll come back on github to explain the bug. 
Please don't push the new version before.

**Comment by MarionPlanque** [comment]
@fxi Do you confirm that you discussed the problem of the custom views in the story map with @thomaspiller and that you found a solution? If not, I am available for further discussion by email, skype or else

**Comment by fxi** [comment]
This is solved by 695e6c30768dfe491e2513041c36b94935aec3dd 
It should be available this afternoon.
Thanks

**Comment by MarionPlanque** [comment]
ok, great! Many thanks
