### ISSUE TITLE
Impossible to share a custom code view on kiosk mode

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#513]
The kiosk mode "use the static mode" doesn't work for custom views: the map is blank and doesn't show any data.

**Comment by fxi** [comment]
Can you try in private browsing mode ?

**Comment by MarionPlanque** [comment]
Nope, doesn't work neither...

**Comment by fxi** [comment]
I've tested with Edge 44.17763.1.0, Firefox 71.0 and Chrome 78.0.390, on Windows 10. Everything seems fine. 

@thomaspiller also tried, but I don't know which browser versions and OS he uses.

Can you provide an example of a failing link ?  If it's private, by email..

Maybe restarting your computer could solve the issue : it does not seem to be related to MapX.

**Comment by thomaspiller** [comment]
On my side, everything is fine with Edge 44.17763.831.0, Chrome 79.0.3945.79 & Firefox 71 on Windows 10.

**Comment by MarionPlanque** [comment]
Weird, maybe it's linked to this UN laptop thing?
@fxi I'll try as you said anyway

**Comment by fxi** [comment]
Is there any new information about this issue ? That's quite a huge bug, but I'm not able to reproduce it. I also checked on browserstack : not a single error on modern browsers.
Without more technical information, without console logs, I will not be able to solve this issue.

**Comment by MarionPlanque** [comment]
Now I can't reproduce it either! Let's pause this bug for the moment

**Comment by fxi** [comment]
So, I close it for now. You can reopen it if it happens again.
