### ISSUE TITLE
"Share this view in another project" logic change 

### ISSUE THREAD

**Issue by tdearden** [unep-grid/map-x-mgl#517]
The logic of sharing external views into your project has changed recently, in which now the user must be a member of the project they are trying to share a view from. (being logged in + a publisher of the project you are trying to share the view into remains the same) This is somewhat illogical for users because:

- It voids the purpose and "selling point" of MapX's data sharing capabilities. If the dataset is public, why can it not be shared between data projects for comparison?
- For most public projects, the "join" button is unavailable, meaning users cannot become members even if they wanted to.  
- If the issue is data security, it is also illogical because the rule is project, not view-based. For example, I can share the view "Biodiversity Intactness Index" from "UNBiodiversityLab - World" project, but not from "Home" project. 
- This actually presents a larger load of work for you guys 👎  as whenever someone is creating a "data inventory" in MapX, now they must ask you for help to share the data into the project they are building! boo, more work. 

Suggestions: 
- Have the "Share this view in another project" button enabled for all views if the user is logged in. Keep the same function whereas users can only "Add in Selected Project" if they are a publisher of another project, or:
- Any data where the read access is "public" can be shared by external users into their projects, or:
- Add a checkbox in "configure this view" where publishers and admins can decide "this view can be shared to other projects"

**Comment by thomaspiller** [comment]
We were talking about this problem right now and fun fact, we thought of the same solutions.
The first solution will be implemented soon and the third is planned for later as it requires more work.

**Comment by tdearden** [comment]
@thomaspiller Ok, great to know! Thanks for the update :)

**Comment by thomaspiller** [comment]
@tdearden Solution 1 will be available in the next version of MapX.
