### ISSUE TITLE
WMS: Bug in GetFeatureInfo request

### ISSUE THREAD

**Issue by psaile** [unep-grid/map-x-mgl#518]
The GetFeatureInfo request produced by [queryWMS](https://github.com/unep-grid/map-x-mgl/blob/4e97174d5b3520bb9f223d4e176257c4c3c45e1c/app/src/js/mx_helper_wms.js#L349) is malformed and produces exceptions on non-geoserver WMS (e.g. ArcGIS Server). 

The paramsInfo object contains the following issues:

1. There needs to be a "version" property as in the other requests
2. The "info_format" property is hard-coded. This might work with your Geoserver but our ArcGIS Server has different formats and uses the MIME-type "application/geojson" to return geojson. This should be taken from the list of formats of the Capabilities document I guess.
3. The same holds true for the "exception" property.
4. The property "src" should read "srs" to request the coordinate reference system.

[Edited by @fxi : missing protocol in provided link]

**Comment by fxi** [comment]
@psaile Thanks for reporting this !  Much appreciated.

I this a big issue for you ? I have no idea how many ArcGIS server are used of WMS service in MapX and our code is maybe a little under-tested in that case.

**Comment by antobenve** [comment]
@psaile The issue was corrected with the new version of MapX. The GetFeatureInfo request is now more flexible and takes into account the results of a GetCapabilities query. My tests seems positive on the layer available through the GetCapabilities link you sent me privately.
 Can you send us feedbacks please?

**Comment by psaile** [comment]
Dear Antonio,

we've tested the revised version and it now works as expected. Thanks for fixing this issue!

**Comment by antobenve** [comment]
@psaile , thanks to @fxi who fixed it.
