### ISSUE TITLE
Features with missing values provoke an error when clicked on map

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#519]
Clicking features with missing value leads to an error:

`Cannot read property 'color' of undefined`

These features are well displayed with the correct color on map. The problem is only related to click events.

Test with this view in Gibraltar for instance:
https://app.mapx.org?project=MX-XVK-HPH-OGN-HVE-GGN&views=MX-CY3C3-R9YDU-EXGPW&viewsOpen=MX-CY3C3-R9YDU-EXGPW

Tested online v. 1.6.51 
Win10
Chrome v.79.0.3945.117

**Comment by fxi** [comment]
Related to custom code in dashboard.

**Comment by thomaspiller** [comment]
It's fixed.
