### ISSUE TITLE
Use current Style is not an option in the Share module anymore

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#520]
I don't seem to find this option anymore in the new share module. 
It was not used enormously but I think it was an interesting tool and we should keep it unless it poses problems with other tools.
If this is the case in the static mode, is it possible to have the option in the normal mode only?

**Comment by thomaspiller** [comment]
The _style_ argument is no more active and is replaced by _theme_. Two themes are currently available (_light_ & _smartgray_) and one or the other can be specified in the URL.
Themes management will be improved later.
