### ISSUE TITLE
Style editor for country boundaries is not effective

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#521]
The style editor of the boundaries on map is not effective.
This applies to both:
Map: boundaries
Map: disputed boundaries

I remember we discussed about it and I think we agreed that it doesn't work because the path to the layers has changed. On the other hand, I don't remember why this wasn't fixed.
If the reason is that boundaries must keep the defined UN style, we should probably think about removing the option from the style editor. What do you think?

**Comment by thomaspiller** [comment]
It is again possible to edit the style of the administrative borders from the toolbox.
