### ISSUE TITLE
Dashboard is not closed after log-in

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#524]
If a user logs-in while a view with dashboard is active, the dashboard and its content are kept active after the list of views in the project reloads. 
Suggestion: close the dashboard every time the project reloads,

**Comment by fxi** [comment]
Thanks.

It happens for every dashboard or specific ones ? Is there any meaningful logs in the console ?

Note : The dashboard module as been rewritten this week : a lot of changes ahead.

**Comment by antobenve** [comment]
No, nothing on console. And yes, it seems systematic. I tried with 2 different dashboards and the result is the same.

Maybe I wasn't clear enough in my suggestion, sorry:
The problem is not related to the complete reload of the project.
It is related to the reload of the list of views available in the panel that happens after the log-in is completed. This process deactivate any view that is displayed on map but it doesn't deactivate the dashboard module and clear its content.

We have 2 options:
- keep active any active view and its dashboard after the log in process.
- clear views and their dashboard content after the log in process (preferred to me)

**Comment by thomaspiller** [comment]
A patch has just been deployed online.
