### ISSUE TITLE
Unable to configure new views

### ISSUE THREAD

**Issue by sade618** [unep-grid/map-x-mgl#537]
When a new view is created, I'm unable to configure it to new data.
Operating System Windows 10
Browsers both Chrome version 80.0.3987.163 and Firefox 75.0

**Comment by scabecks** [comment]
This is also occurring on Linux Mint 19.3. Further, if the newly created View that was made (and unable to edit/link a data source to) is not deleted in the same session, it becomes uneditable (e.g., cannot even be deleted) in subsequent sessions, even where it shows I am the creator/editor of the View (see below).

![Screenshot_2020-04-22 MapX](https://user-images.githubusercontent.com/8373509/79925279-5af4ea00-847d-11ea-92f2-217775306e2e.png)

OS: Linux Mint 19.3
Browser: Firefox 75.0

**Comment by thomaspiller** [comment]
I also managed to reproduce this bug.

There are no errors in the web console.
The only relevant information that I could note is in the panel indicating that something went wrong: _"subscript out of bounds"_

The changes between version 1.6.74 and 1.6.75 seem to be the source of this problem as I just did a test on my local stack and everything works fine in MapX 1.6.74.

MapX 1.6.75
Linux Mint 19.3
Chrome 81.0.4044.113

**Comment by fxi** [comment]
Ok, I will check this now.

**Comment by fxi** [comment]
It should be solved in 1.6.76

**Comment by fxi** [comment]
By the way, welcome to @sade618 and thanks for reporting your first issue :)

**Comment by thomaspiller** [comment]
I tested version 1.6.76 on my local stack and the problem is solved.

**Comment by thomaspiller** [comment]
The patch has been released online in version 1.6.76.
