### ISSUE TITLE
Option to set the default size of a dashboard

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#560]
In the dashboard editor, add a field to define the default size of the dashboard with four options to choose from:
- horizontal alignment
- vertical alignment
- full screen
- reduced size (current behavior)

The default value for this field should be the reduced size to avoid problems with dashboards already available in MapX.
If several dashboards are activated simultaneously, the size should be that of the first dashboard activated by the user

**Comment by fxi** [comment]
Done : 
![mx_dashboard_layout](https://user-images.githubusercontent.com/1196833/86615389-ae72d080-bfb4-11ea-84f3-c65e6093ecb3.gif)

**Comment by thomaspiller** [comment]
It works fine but default value should be "Fit to largest widget" instead of "Full size" to ensure the compatibility of old dashboards with this new option.
