### ISSUE TITLE
Publication of views using geoserver take too much time

### ISSUE THREAD

**Issue by fxi** [unep-grid/map-x-mgl#565]
After configuring available OGC services of a source, updating a view that use this source will trigger an update of GeoServer database. This operation will take a very long time, which blocks the server side app of MapX. 

The more source we have published, the more time this operation will take. 

Possible solutions :

- Solve the issue upstream: avoid using GeoServer. Updating layer list is too slow. No viable solution found. Using MapServer and mapfile instead ?
- Upgrade Shiny to enable to use promises support.

If anyone has a better idea, please write a comment. :)

**Comment by trepmag** [comment]
A potential 3rd option would be to make this operation as an asynchronous task outside of the server side process which when finished notify that app... The user would trigger that operation and doesn't wait but would be notified when finished.

**Comment by fxi** [comment]
Yes, that could be an option. Trigger update -> create new process -> load package curl, geosapi [...] -> launch script -> send email with result -> failed or success. We should also make sure to keep track of the job.

In my app "LebaMod" that I wrote back in 2014, the user could  check the status of each job he requested and all jobs configuration were stored in a SQLite db. So any job not started could be canceled and removed from the queue (not implemented in  the app, but manually it was possible).  

However, that will not solve the whole issue : the whole GeoServer is down during the process and will not respond. If the "catalog" is updated, nothing can be done and from what I've seen,  the API, services, and the interface is blocked. I don't think a callback could be sent after the whole process is done. So, basically, we have to probe from time to time if GeoServer can handle new request. Hopefully I'm wrong because that would be lame. 

In all case, MapX should implement a job management system or a least make use of promises : GeoServer is not the only blocking process.

**Comment by trepmag** [comment]
The GeoServer down issue can be mitigated with:
- a clustering setup; while the reload is being made on the master the cluster slaves still respond to reads
- [jdbcconfig](https://docs.geoserver.org/stable/en/user/community/jdbcconfig/index.html) would improve the update of the catalog

But that doesn't remove the necessity of a job/queue system for this king of task (a candidate library to study: https://github.com/OptimalBits/bull)...

**Comment by fxi** [comment]
That's theoretical solutions or production ready solutions ?

- Clustering will not work as the catalog is based on XML files : there is a high risk of conflicts during rewrite process, unless having a clumsy sync system that periodically restart workers and copy those files around.  
- `jdbcconfig` looks like a good solution, but we should make sure that's robust enough to be used inside our swarm without supervision and manual tweaks. If you are able to make a docker image that make use of this extension, with a postgres backend, that would be great. Why not a docker-compose project ?  

`bull` would need to instantiate R child processes, to launch our scripts and `geosapi` OR uses direct GeoServer API method.  In that case, the whole thing  currently running in R should be ported in Node. Which could be an improvement.

**Comment by trepmag** [comment]
We could start with the try of jdbcconfig indeed...

Geoserver clustering is something that geosolution has expertise on (I need to check with JP where stands the discussion on this): https://docs.geoserver.org/stable/en/user/community/jms-cluster/index.html

**Comment by fxi** [comment]
@trepmag As I said, I don't think clustering is a solution in that specific case. `jdbcconfig` is more likely to be one. Could you try this ?
