### ISSUE TITLE
MapX Style

### ISSUE THREAD

**Issue by fxi** [unep-grid/map-x-mgl#566]
MapX could maybe use a better style builder : https://github.com/geostyler/geostyler. It could be use to convert style between multiple format, such as MapServer, OpenLayer and SLD.

**Comment by thomaspiller** [comment]
@fxi is this still relevant now that the style editor has been improved with the addition of the _Auto style_ tool?

**Comment by fxi** [comment]
Yep, more or less. Their tool seems more advanced. But with our sld->mapx, the gap is shrinking. We ca close it: it's always findable through the github search.
