### ISSUE TITLE
Application update alert in SDK context

### ISSUE THREAD

**Issue by trepmag** [unep-grid/map-x-mgl#571]
When a embedded mapx instance needs to be updated a dialog box `window.alert()` popup. As it is a modal window it prevents the user from accessing anything on the page but this dialog.

This will probably confused the user as he might not even know from which instance it comes (host or embedded). Also, multiple embedded instances might open a sequence of those modal dialogs... 

A solution would be to replace this  `window.alert` dialog with a `<div>` modal box like the "disconnected" overlay...

**Comment by fxi** [comment]
The alert was useful when nothing else worked: no js, no css, huge mess. It did not happen very often.

We can instead force the skip waiting : 

_app/src/js/init_sw.js_
```js
var skipWaiting = !window.mx || !window.mx.helpers.getDictItem || window.parent !== window;

  if (skipWaiting) {
    return update();
  }
[...]
```

**Comment by fxi** [comment]
@trepmag, can I close this issue ?

**Comment by trepmag** [comment]
Yes, I could notice a "silent" reload instead of the window.alert()...
