### ISSUE TITLE
Uncaught TypeError: $n is not a function thrown with current sdk 1.6.110-beta

### ISSUE THREAD

**Issue by trepmag** [unep-grid/map-x-mgl#587]
Importing sdk mxsdk@1.6.110-beta throw the following exception:
```
Uncaught TypeError: $n is not a function
    at regexp-exec.js:87
    at mxsdk.umd.js:1
    at mxsdk.umd.js:1
```

1.6.106-beta is the previous working version...

**Comment by thomaspiller** [comment]
@trepmag MapX v1.7.1 has just been released can you test if this bug has been corrected in this version please?

**Comment by trepmag** [comment]
Yes solved!
