### ISSUE TITLE
Raster layers with lat/long values exceeding (even by little) the allowed max are not displayed in static mode

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#592]
Raster views which layer has exceeding max latitude and/or longitude values are not displayed on map.
The issue only concerns the static mode.
Here an example:

Static mode link
https://app.mapx.org/static.html?zoomToViews=true&language=en&views=MX-BYFNH-UUI3S-W9L6B

App mode link
https://app.mapx.org?project=MX-ZU2-F8I-ZVS-JCK-FBQ&views=MX-BYFNH-UUI3S-W9L6B&viewsOpen=MX-BYFNH-UUI3S-W9L6B&language=en

![image](https://user-images.githubusercontent.com/30286565/91549453-40e57f80-e927-11ea-899d-04b22203e1f4.png)

**Comment by fxi** [comment]
It seems ok now. The raster layer bbox has changed ?
![image](https://user-images.githubusercontent.com/1196833/94406586-8b4e5c00-0172-11eb-9fd6-f6ffac712534.png)
In general, if the longitude is greater that or less than 180 or -180, there is a projection issue that should be solved before publishing the data.

**Comment by antobenve** [comment]
You're right, it seems fine now.  I'm closing the issue.

My request was related to the fact that the projection issue was well handled by the dynamic app mode and I thought the static mode could be able to handle it too. And in fact this seems to be the case now although I don't see what could have changed since then as MapX was not developed further.
