### ISSUE TITLE
Auto style improvements

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#595]
The new _Auto style_ tool is extremely practical but its use could improve by:

- [ ] adding a new binning method _custom_. It would allow the editor to define a number of bins and a color ramp then to manually define the bounds of the bins.
- [ ] integrating the _Auto style_ module into the _edit style_ panel to avoid having a tool in a tool.

**Comment by antobenve** [comment]
Useful improvement to add: 
- [ ] Be able to invert the color scale.

**Comment by thomaspiller** [comment]
The style manager will evolve shortly, possibly making this issue irrelevant.

**Comment by thomaspiller** [comment]
I close this issue as it is no longer relevant. I will post a new one soon with an updated list of improvements that takes into account the latest developments.
