### ISSUE TITLE
Auto style glitches

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#596]
- [x] the default point size should be 5 (or 7), same for "missing values". 10 is too big if there is a large number of points on map.
- [x] allow 2 bins to have the same value. It seems that the elements that fall in the first and in the second bin are counted twice.
![image](https://user-images.githubusercontent.com/19908801/92565250-a2d4ac00-f27a-11ea-8445-94ff96ef20b0.png)

**Comment by fxi** [comment]
Can you provide a file that fails ? I'm not able to reproduce the second point...
Thanks !

**Comment by antobenve** [comment]
Please check https://app.staging.mapx.org?project=MX-YGZ-V30-RMA-YTK-SFW&views=MX-OMNR5-0OSIT-RQDVE&viewsOpen=MX-OMNR5-0OSIT-RQDVE&language=en&
You can play with the data as you wish.

**Comment by antobenve** [comment]
The two elements seem to be corrected in the testing version v1.7.3 except for the default size of points with "missing values" which is still 1.

**Comment by antobenve** [comment]
The remaining item is corrected in v.1.7.5-beta (tested in staging platform).
