### ISSUE TITLE
Highlight the clicked item in the map

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#602]
It would be interesting to highlight which item was clicked on in the map by changing its style.
A source of inspiration: https://docs.mapbox.com/mapbox-gl-js/example/hover-styles/

This feature would be particularly relevant when a view has a dashboard or when MapX is driven by the SDK with the pop-up disabled.

**Comment by thomaspiller** [comment]
@fxi @trepmag We should discuss the implementation of this feature in early October. This development was requested for WESR and should be done by the end of October.

**Comment by thomaspiller** [comment]
Experimental version available in MapX 1.7.4-beta.

**Comment by fxi** [comment]
Can we close this one ?
