### ISSUE TITLE
Time out avoid loading Attribute table viewer if data is considerably large (i.e. Acled)

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#603]
`Uncaught (in promise) fetchProgress : timeout exceeded ( 5000 ms )` when loading the attribute table viewer if data is too large (i.e. [Acled data](https://app.mapx.org?project=MX-KVV-ANS-WBN-QXR-S71&views=MX-B4DGM-36XSS-CR5CF&viewsOpen=MX-B4DGM-36XSS-CR5CF&language=en&)).
The time out doesn't allow the tool to open and ends up blocking MapX which must be refreshed afterwards.
An idea could be to create calibarated time outs based on the size of the data to be loaded (if larger than 2x expected time -> time out -> MapX doesn't get stuck).

**Comment by fxi** [comment]
Is this still an issue ?

**Comment by antobenve** [comment]
It seems it has been corrected. Have you increased the time out value or changed the way the request is handled?
In any case I couldn't reproduce the problem anymore and I also did not experience time outs in any other case recently (while I was in September from time to time when MapX was loading).

**Comment by fxi** [comment]
1. PostgreSQL timeout handling (`s.db.timeout`) : 65c5a5848b4960
2. Unification of time to live (`mx.settings.maxTimeCache`) and timeout (`mx.settings.maxTimeFetch`) : 4c63c1a591f8

**Comment by antobenve** [comment]
Ok. Thanks. I'm closing the issue.
