### ISSUE TITLE
[WMS URL Generator] - List of available layers from WMS service is generated from cached data rather than the GetCapabilities

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#605]
The list of available layers from a given WMS service seems to be based on cached data. Any update in the server is missed by the user requesting the layers list.

The list of available layers should always be based on the xml that is provided by the server in consequence of the GetCapabilities request.

**Comment by antobenve** [comment]
This has a further implication on the getFeatureInfo request that is sent when the user clicks on map. If the layer is not in the getCapabilities xml file that is being used in the user's browser, the request will result in `Failed to display attributes` due to `Operation not permited by the requested server or layer, check console for details`

**Comment by fxi** [comment]
`GetCapabilities` can be extremely heavy to fetch. Sometimes even more than 500MB. We can't afford 1/100 of that in a web app... Caching is mandatory : service workers or custom cache system. 

I chose to use MapX custom cache to handle this. WMS `GetCapabilities` has no versioning system. Or I don't know it. 

For now, the cache duration is set to two days. We could reduce this to one hour.

I can also add a trigger to remove cache locally on demand. A button to invalidate cached WMS `GetCapabilites`. The publisher could then test updated version of the WMS `GetCapabilities` without waiting the end of the cache. This could be also a global checkbox : do not use WMS cache locally. 

The third option would be to wrap a `GetCapabilities` method server side, in our API and and handle cache versioning or/and hash  system there. But it would be more complicated.

@antobenve What do you think ?

**Comment by antobenve** [comment]
Ok, I didn't know it was only kept for 2 days. 
In this case it is less problematic.

I haven't found any info on versioning of the capabilities. And we have to consider that each provider (GeoServer and ArcGIS for instance) might have its way to handle it, in case they do.

I think it is acceptable, for publishers, to wait when we download the list of layers for a service in the configuration window of a view. In this case we would not need a method to invalidate the cached xml (but we could still think about implementing it with a toggle in the configuration window). 

However, I think that normal users that query layers will always have the risk to run into issues when they query a new layer that is not present in their capabilities. This can be reduced if we reduce the time in which we use the cached file from 2 days to 1 hour but still we have an hour where the risk exists.

**Comment by antobenve** [comment]
The issue is fixed in v7.1.4-beta available in staging.
