### ISSUE TITLE
SDK : improvement and feature request

### ISSUE THREAD

**Issue by fxi** [unep-grid/map-x-mgl#609]
Here is a list of futur developments and fixes for the SDK module. 

## Quick fixes
- [x] URL query parameter to handle view panel state: by default, in SDK mode, the view panel should be hidden.

## Advanced changes
- [ ] Add SDK support for static mode: subset methods, use a token system (idApp, token) to perform action directly to the api. 
- [ ] UI testing should report at the command line. Use phantom JS ?

**Comment by thomaspiller** [comment]
@fxi I believe the remaining points were developed recently in MaPX. Can I close this issue?

**Comment by fxi** [comment]
We can close this one and I will reopen proper issues for what's left later.
