### ISSUE TITLE
Feature request: share button in story map mode 

### ISSUE THREAD

**Issue by tdearden** [unep-grid/map-x-mgl#613]
It would be useful to have a sharing button available in the top toolbar when in story map mode, so that the user can share a link to the story map directly from full-screen mode (particularly good when the story map has been shared in static auto-play or in an iframe & don't have access to the MapX project).

Suggestion: add Sharing Manager button to the top toolbar, visible only when in story map mode

![image](https://user-images.githubusercontent.com/41048297/97288184-cca35b80-1845-11eb-88b8-cc43840c3462.png)

**Comment by fxi** [comment]
It could be a handy feature.
So, this button, when clicked, would not open the MapX sharing manager, but only open a modal window with the link to the story in static mode.
![image](https://user-images.githubusercontent.com/1196833/97290674-29544580-1849-11eb-9b3a-8a5758057aab.png)
@antobenve I let you set the priority on this, thanks !

**Comment by antobenve** [comment]
As we're approaching the development of this feature I propose the share button allows sharing the story map in NON-static mode too. 
This can be useful if people need to share the link to a story map embedded in an iframe for allowing others to find it and edit it.

I know the story map play mode doesn't take into account projects rights etc... I propose, therefore, not to load the share module but to provide 2 links from which the user can chose from based on easily accessible information from the view's metadata.
1) static link
2) app.mapx.org/?project=<ID of the project where the story is published originally>&views=<viewID>&viewsOpen=<viewID>&language=<language the story map is being played in>

**Comment by PierreLacroix** [comment]
Good suggestion in principle.
In practice I have a preference for only one button (static mode) in order to simplify users' work

**Comment by antobenve** [comment]
Definitely true. In this case we could imagine to place this other functionality somewhere else, such as in the metadata form. However, the metadata of the story map are not displayed in presentation mode and we need to think about a new button to load them (not a useless thing in my opinion as many story maps are used as embedded iframes in websites)

**Comment by thomaspiller** [comment]
I would also look at the simplest solution for users: a single static link allowing to access the story map in reading mode.

For the metadata, it seems to me that the fields available in the UI are not very relevant for the general public as they are very technical. Your option?

For the link with the possibility of editing, an editor can already generate it from the MapX UI with the sharing tool so I don't really understand your remark.

**Comment by antobenve** [comment]
The metadata information can be too technical, it is true, but it offers stats and the abstract of the story map one is displaying.
Let's remember the user might be displaying the story map from a website in which it is embedded as static link in presentation mode. There is no other way for the viewer to access the metadata.
For the same reason there is no way for the viewer of the story map to generate a link that points to the project where the story is published in in case he needs it (e.g. sending it to someone that needs to edit it or simply finding the space where the story is published).

I recognize two links can be confusing for the users. In this case, if we don't find an alternative solution, we can stick to the original plan and only develop a button to generate a static link and we'll think about a solution afterwards in case there is a relevant need.

**Comment by PierreLacroix** [comment]
The website developer can for example include all relevant information into the web page.

**Comment by antobenve** [comment]
Mmmm Pierre, I don't think this would be a good solution as I'm mostly thinking about partners that needs to find/edit their story map that is displayed in a webpage. I'm not talking about way of accessing other data by public users. However, as I said, we can stick to the plan if you all think the need I reported is not relevant.

**Comment by thomaspiller** [comment]
Perhaps this point deserves a discussion to clarify what needs to be developed.

**Comment by antobenve** [comment]
the solution finally agreed after the discussion is:
- a button in the "controls panel" when in story map presentation mode that provides: static + app + iframe links
- a static hyperlink to the view (when clicking on view title) and an app hyperlink to the project (when clicking on project title) in metadata module

**Comment by antobenve** [comment]
I'm closing the issue as it is available in prod. If new developments will be asked we will reopen it again or open new issues separately depending on the case.
