### ISSUE TITLE
Suggestion: data display

### ISSUE THREAD

**Issue by MarionPlanque** [unep-grid/map-x-mgl#619]
When a link points to a map showing data, the view panel doesn't display the views activated. Therefore, users must open each category to identify which data is activated (see example below)

![image](https://user-images.githubusercontent.com/25179050/98977986-89b9d700-2519-11eb-942a-3947bc5266b8.png)

Suggestion: the categories should be expanded to display activated data

**Comment by fxi** [comment]
Hey, Marion, what's up ?

I've added two options for this, in the sharing tool : 
- Hide categories 
- Filter activated views by default

The categories are not expanded, but the result is close. I can add something to expend them, if needed.

![image](https://user-images.githubusercontent.com/1196833/98978333-1bc1df80-251a-11eb-957b-232e75220d4f.png)

Example, with hide categories enabled:https://app.mapx.org?project=MX-WJO-FOV-NNB-1BN-SZN&views=MX-U0277-AF2G4-AG4C5&viewsOpen=MX-U0277-AF2G4-AG4C5&lat=38.982&lng=43.41&z=4.445&viewsListFlatMode=true&language=en&viewsListFilterActivated=true&

**Comment by fxi** [comment]
@MarionPlanque Can we close this or your request is not covered by the new parameter ?
