### ISSUE TITLE
URL terms: viewsListFlatMode is invalidated by viewsListFilterActivated

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#620]
1. Using the two terms in the URL (with value "true") invalidates the viewsListFlatMode.
2. Furthermore, the viewsListFlatMode is also invalidated when it is used alone in the URL but the user clicks twice on "Filter activated views" on the interface (on and off in sequence).

The wished behaviour is that both terms can coexist in the URL and that the interface doesn't overwrite the URL specs.

For instance:
1) https://app.mapx.org/?project=MX-YCD-XAV-LBN-PRT-TL1&views=MX-1MWJ2-S06B8-VOUMT&viewsOpen=MX-1MWJ2-S06B8-VOUMT&lat=5.532&lng=45.745&z=5.965&language=en&viewsListFlatMode=true&viewsListFilterActivated=true
2) https://app.mapx.org/?project=MX-YCD-XAV-LBN-PRT-TL1&views=MX-1MWJ2-S06B8-VOUMT&viewsOpen=MX-1MWJ2-S06B8-VOUMT&lat=5.532&lng=45.745&z=5.965&language=en&viewsListFlatMode=true

**Comment by thomaspiller** [comment]
It seems fixed. @antobenve can you please confirm that it works as expected? Thanks.

**Comment by antobenve** [comment]
Yes, sorry. I forgot to report here. It does work as expected to me too.
