### ISSUE TITLE
Add MapX metadata for raster and custom code views

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#622]
- Addition of a button in the `Edit view` panel to access the metadata form.
- Compared to the metadata of vector views, the `text -> attributes` and `text -> attributes_alias` keys can be removed from the metadata schema.
- Metadata is saved in the `mx_views` table in the `data` column.
- In general, the same functionalities must be available for these two types of views:
  - warning sign when metadata is not complete;
  - source metadata appears in the `Display metadata` panel accessible from the view.

**Comment by fxi** [comment]
Isn't the title section in the metadata a duplicate of the view title ?

**Comment by thomaspiller** [comment]
It is possible that the name of the view in MapX is not exactly the same as the one defined by the data provider. If this is not a problem, we could indeed delete the `text -> title` section.
Anyway, the title must appear when exporting raster and custom code views metadata.

**Comment by thomaspiller** [comment]
Some suggestions to improve this development:
- group the different sections related to the metadata into a main section
- add the "In Depth Validation" button in the panel next to the "save" button

**Comment by fxi** [comment]
> - group the different sections related to the metadata into a main section
In the view editor or in summary view summary ? Not sure to understand.

**Comment by thomaspiller** [comment]
Forget this remark, it's already in MapX.  I must have hallucinated.

![image](https://user-images.githubusercontent.com/19908801/104923247-178fc380-599c-11eb-87d1-87e63bd25c55.png)

**Comment by thomaspiller** [comment]
Available in v1.8.4-beta.
