### ISSUE TITLE
Style manager: strange behaviors to explore in early 2021

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#629]
Hi team,

A few strange behaviors I noticed during my testing of MapX version 1.8 (dev). This also seems to be present in the version currently in production (1.7.9). This should be looked at carefully in early 2021.

- [x] First rule of a style: the lower bound is always equal to the minimum value of the main attribut and not the value specified by the user in the MapX style manager.
- [x] Style with twice the same value causes a problem with the filter from the legend.
<details>
<summary> Same value glitch gif </summary>

![ezgif com-gif-maker](https://user-images.githubusercontent.com/19908801/102515429-0d716100-408e-11eb-954e-5c5806d776dc.gif)

</details>

- [x] If a `missing value` of numeric type is specified by the user it gets a double style.
![image](https://user-images.githubusercontent.com/19908801/102516091-c768cd00-408e-11eb-822f-cb8dffe5c1db.png)
- [x] Auto style: when the main attribute is numeric, there are n-1 elements in the summary.
  - In this exemple, the count should be 9 with values (integer) from 1 to 9.
![image](https://user-images.githubusercontent.com/19908801/102516579-4eb64080-408f-11eb-9fa9-721db3be18f0.png)

**Comment by fxi** [comment]
This is also happening with all classification functions or just jenks ? Or just jenks when n could not be divided without remains by n jenks ? Like 9 numbers in 5 classes ?

**Comment by antobenve** [comment]
I'm seeing the same problem in this [view](https://app.staging.mapx.org?project=MX-GWE-HNB-O5P-NXA-YH9&views=MX-YEMRE-ZPXC6-T6D1Q&viewsOpen=MX-YEMRE-ZPXC6-T6D1Q&language=en&) with 18 rows but only 17 counted in Summary. This happens with any stat function and any class number.

**Comment by thomaspiller** [comment]
I confirm that this affects all classification functions. I did a test using the following source:
![image](https://user-images.githubusercontent.com/19908801/102520259-c9815a80-4093-11eb-9a88-f0bbc444f1fe.png)

number of bins | < 9 | 9 | > 9
-- | -- | -- | --
equal interval | 8 | 8 | 8
quantile | 8 | 9 | > 9
head/tail | 8 | 8 | 8
jenks | 8 | 9 | NA

**Comment by fxi** [comment]
Those results are the output of the style manager or a request on https://api.staging.mapx.org/get/source/summary/ ?

If this coud be reproduced in /get/source/summary, the issue will be in 
- api/modules/source/getSourceSummary.js
- api/modules/template/sql/getSourceSummary_attr_continuous.sql

In the worse case, it's in base formulas from carto : 
- api/modules/db/sql/mx_cdb_jenks_bins.sql
- api/modules/db/sql/mx_cdb_quantile_bins.sql
- api/modules/db/sql/mx_cdb_heads_tails_bins.sql
- api/modules/db/sql/mx_cdb_equal_interval_bins.sql

**Comment by fxi** [comment]
@thomaspiller 

> First rule of a style: the lower bound is always equal to the minimum value of the main attribut and not the value specified by the user in the MapX style manager.

Could you explain a bit more what's the problem ? I think this was defined like that, according to the text describing the option "include upper bound" : 

![image](https://user-images.githubusercontent.com/1196833/131341555-353f638b-4ba0-464c-a84f-b3ce0581768b.png)

**Comment by fxi** [comment]
We could add a mode where numeric values behave like string based values : the style could then be set using exact match instead of upper/lower bounds

**Comment by thomaspiller** [comment]
Indeed, the text under the rules explains well how the min and max values are used in the style. However, I find it counter-intuitive to have the possibility to change the lower-bound of the first rule in the interface while it is fixed.
Is it possible to block the _value_ of the first rule in the form?

**Comment by fxi** [comment]
So, two new options:

1. Don't use numeric bounds : use exact matches ex. value === 1 instead of value >= 0 && value <= 1
2. Don't use min max from source's stats for absolute lower and upper bounds. but.. min / max from rules. ex. in rules, min = 1 max = 2 -> 
       value >= 1 && value < 2 (rule 1)
       value === 2 (rule 2)

Maybe we should discuss this in person, as there is many ways of doing it.

**Comment by antobenve** [comment]
Thanks for the correction @fxi, 
With the new option to "NOT TO USE STATS" I think we solve the lower bound issue. We can now define the minimum value to start the first rule from.

However, if we activate this option the last rule does not include the max value of data anymore (i.e. everything above the value of the last rule is not painted).
This goes against the way all the other classes are defined [STYLE defined in row applies to values FROM value of row TO (just below the) value of next row]. 

I suggest the correction that you have implemented is integrated in the normal behavior of the style module. This means that we should not add an option "NOT TO USE STATS" but, by default, :
1) the minimum value of the first class should be taken from the style module (at the place of the minimum value of the stats) and 
2) the maximum value of the last class should be taken from the stats.

**Comment by thomaspiller** [comment]
@antobenve There are plans to improve the style editor in the coming weeks.
A new entry will be added to the _Rules_ section so that users can define for each rule a lower bound and an upper bound.
So the problem you mentioned will be solved by this new development.

**Comment by antobenve** [comment]
Ok @thomaspiller , I'll check the new dev when it will be available. Thanks

**Comment by thomaspiller** [comment]
@fxi  the double style issue is still present if the `missing value` is not one of the extremes. See this example: https://app.staging.mapx.org?project=MX-IHX-BP0-9AO-44B-5YX&views=MX-S7BXY-14CPW-9DIDN&viewsOpen=MX-S7BXY-14CPW-9DIDN&viewsListFlatMode=true&language=en&

**Comment by fxi** [comment]
@thomaspiller The example you gave includes the `na` value also in bounds.

```sh
     ┌─┐
  6  │ │
     ├─┤
  5  │ │
     ├─┤
  4  │ │
     ├─┤
  3  │ │<- represents "nulls" AND present in bounds 
     ├─┤
  2  │ │
     ├─┤
  1  │ │
     └─┘


     ┌─┐
 -999│ │
     └─┘


```
The only way I see to solve this is to add a conditional filter in each rule just for that case.. It's a bit noisy, but doable.

So, I've added a block handle manual numeric null value within bounds. As the user can also put the same value in non-numeric rule in null value handler AND in the rule panel, this could solve this 
```js
      if (useStyleNull) {
        const value = ruleNulls.value;
        if (isNumeric) {
          if (value) {
            filter.push(['!=', attr, value * 1]);
          } else {
            filter.push(['!=', attr, '']);
          }
        } else {
          if (value || value === false) {
            filter.push(['!=', attr, value]);
          } else {
            filter.push(['!=', attr, '']);
          }
        }
      }


```

**Comment by fxi** [comment]
For the case mentioned by @antobenve,

We could split the new option  

> Ignore min/max statistics for the lower / upper bounds
> Ignore min / max from source statistics for absolute lower / upper bounds. Those values will be taken from the rules set.

Into 

> Ignore min statistics for the lower bounds
> Ignore min  from source statistics for absolute lower bounds. Those values will be taken from the rules set.


and

> Ignore max statistics for the upper bounds
> Ignore max from source statistics for absolute upper bounds. Those values will be taken from the rules set.
