### ISSUE TITLE
UI: Modules in wrong order

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#632]
In some cases, the modules are not in the right order.
It has been experienced that 
- [x] Login module is hidden by views panel when opening a private project without credentials (see https://app.staging.mapx.org?project=MX-GWE-HNB-O5P-NXA-YH9&views=MX-X5TZ7-NF8Y1-ND3L6&viewsOpen=MX-X5TZ7-NF8Y1-ND3L6&language=en&)
- [x] Views' panel is hidden by the dashboard (not reproducible)

example first point

![image](https://user-images.githubusercontent.com/30286565/104212694-c6308300-5435-11eb-9283-3e20e5cdb1d2.png)

Version 1.8.0-alpha using Chrome 87.0.4280.88 on Windows 10

**Comment by thomaspiller** [comment]
I like the fact that the panel where the mouse is located goes to the foreground but there is a edge case (not critical): when you move your mouse quickly, the dashboard may go under the views panel.


![dash_view](https://user-images.githubusercontent.com/19908801/104922123-8e2bc180-599a-11eb-815b-701c476668e4.gif)

Do you find this problematic? If not, I think we can close the issue

**Comment by fxi** [comment]
uhm. The listener being on the window, the mouse can travel faster than the panel. It can hover briefly other panels, which trigger their zIndex. By the time the animation reach up, it's too late, hover is no more on the original panel. I can put a higher zIndex on panels being dragged/resized.

**Comment by fxi** [comment]
![mx_button_panel_hover_glitch](https://user-images.githubusercontent.com/1196833/104925699-6f7bf980-599f-11eb-9cfd-683931a13713.gif)

**Comment by thomaspiller** [comment]
I just tested the fix in v1.8.4-beta and it works fine. Thanks.
