### ISSUE TITLE
MapX's GeoServer notifications

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#638]
As MapX now has a notification system in its interface, it could be used to transmit messages related to interactions with MapX's GeoServer instead of sending emails.

**Comment by fxi** [comment]
Async R scripts to update geoserver are disconnected from the webocket session (shiny). The only way to reach the client's browser is to .. reach the api from the spawned process with the ID of the user, check if a websocket session (node js) is associated with this particular user and then stream a message to all browsers from that user. Alternatively, we could get the session id of the node's websocket connection from the client, at one point, and pass this to the spawned process, which could reach the api and send a message to the user. It's possible, but a bit convoluted.

**Comment by thomaspiller** [comment]
As this development is complex and is by far not a necessity at this time, I am closing this issue for now.
