### ISSUE TITLE
Issue: the province boundaries on the background map don't match those from the institution in Afghanistan.

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#64]
### Expected Behavior
When visualizing heatmaps the boundaries of polygons should match those in the background map. It is not a big deal but it might disturb users when reading those maps because it suggests them that the layer is inaccurate.

### Current Behavior
Province boundaries don't match with polygons that were built using institutional province boundaries in Afghanistan.

### Steps to Reproduce

1. Try selecting one of the views that are under the keywords "Social" or "Development" in Afghanistan

**Comment by fxi** [comment]
Thanks.

This is data related, not code related. 

There is no unified administrative boundaries source layer yet. So, users can upload what they consider "legit" and unless an administrator like you decides to remove it, the data will be shown as it.

So, if this is wrong, remove the related views and sources or make them private : we don't want wrong data in the platform, do we ? 

CC @PierreLacroix @nicolasray

**Comment by antobenve** [comment]
No, sure not. The fact is that the views that I've created are related to correct province boundaries according to the government of Afghanstan. In fact, they were generated according to the guidelines of the only institution in Afghanistan that have the right to define the district and province boundaries.

Thus, the data is good but it seems bad if seen on map. If you think this is not important there is nothing more to do. However, if you think that this incongruence creates a bad effect and you want to avoid it, I think the best solution is to remove the province boundaries from the background map if it is possible. This is the reason why I mentioned this issue. It all depends on the importance you give to this.

Antonio

**Comment by fxi** [comment]
Yep.

It's still data related and it could be reported to the open street map project, if you are certain that the geometry is more correct than the one displayed.

So for now we put this on hold and we decide later what do to with this.

Thanks
