### ISSUE TITLE
Metadata validation: values consisting of spaces should not be accepted

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#640]
Values consisting of spaces are considered as invalid in "In Depth Validation" but there is no warning message in the panel to inform the user and it is possible to save the schema with these invalid values.

![image](https://user-images.githubusercontent.com/19908801/104289611-a2168580-54b9-11eb-861f-841faf6966e1.png)

![image](https://user-images.githubusercontent.com/19908801/104289677-b8bcdc80-54b9-11eb-96eb-ab461ff37088.png)

**Comment by fxi** [comment]
This issue comes from json-editor itself:

https://json-editor.github.io/json-editor/

https://user-images.githubusercontent.com/1196833/104293909-da6c9280-54be-11eb-8f5c-3a4e07b4c72b.mov

With sound for dramatic effect :)

Should't  this be reported / solved at json-editor level ?

**Comment by thomaspiller** [comment]
A solution could be to create a [custom validation](https://github.com/json-editor/json-editor#custom-validation) for text inputs at json-editor level. What do you think about this approach?

**Comment by thomaspiller** [comment]
Custom validation works well in version 1.8.3-beta. Thanks.
