### ISSUE TITLE
Add the dictionaries to the MapX database

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#648]
Now that the ISO3 and M49 codes are used for the geographic keywords, it would be interesting to add a table in the db containing the dictionaries located in the [dict](https://github.com/unep-grid/map-x-mgl/tree/master/app/src/data/dict) folder.

It should be quick to set up and very useful for queries run from psql / pgAdmin / R.

Thanks.

**Comment by thomaspiller** [comment]
This development remains in priority 1 but can wait a bit to explore the best way to manage the publication of dictionaries in the database. Until then, some data manipulation will be done outside of MapX from `BASH` / `R` scripts.

**Comment by fxi** [comment]
This have been added in be2142e12

**Comment by thomaspiller** [comment]
I just looked at the table in the staging DB and everything looks fine. Thanks.
