### ISSUE TITLE
Adjust the width of the views panel according to the app size

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#649]
Depending on the size of the MapX window, the views panel can hide almost the entire map. 
Therefore, the default size of this panel should adapt to the dimension of MapX.
Perhaps some rule should be created based on the width of the application like:

|App / iFrame width     |Panel width|
|---------------|-----------|
|< 500px        |200px      |
|> 500 & < 750  |250px      |
|> 750 & < 1200 |350px      |
|> 1200 & < 1600|400px      |
|> 1600         |450px      |

**Comment by fxi** [comment]
I tried that, but it's ... shrinked. It would be smarter to have the panel in closed state for viewport  width < 750px and let the current system do the rest for open state. What do you thing @thomaspiller ?

`< 500px | 200px`
![image](https://user-images.githubusercontent.com/1196833/107388150-cfc10f80-6af5-11eb-82aa-163cb0a75bdf.png)
`> 500 & < 750 | 250px`
![image](https://user-images.githubusercontent.com/1196833/107388324-039c3500-6af6-11eb-8f9f-ad8853c6655c.png)
`> 750 & < 1200 | 350px`
![image](https://user-images.githubusercontent.com/1196833/107388430-22023080-6af6-11eb-9b18-1fc1ab31ab88.png)
`> 1200 & < 1600 | 400px`
![image](https://user-images.githubusercontent.com/1196833/107388531-3ba37800-6af6-11eb-8c87-b4158a86a152.png)
`> 1600 | 450px`
![image](https://user-images.githubusercontent.com/1196833/107388683-5e359100-6af6-11eb-8bfb-90ac3ae2cbff.png)

**Comment by fxi** [comment]
We can also make this a classic sliding panel for small devices : 
https://user-images.githubusercontent.com/1196833/107390741-48c16680-6af8-11eb-88fe-68a583a6e843.mov

**Comment by thomaspiller** [comment]
I like the classic sliding panel solution but there are also cases where MapX is embedded in a web page via a small iFrame.
In these cases, the sliding panel may not be the best solution.
Looking at the screenshots I'm thinking the panel size should be  >= 300px. Smaller than that, the rendering is not that great.

**Comment by fxi** [comment]
In iframe, e.g. using the SDK, the panel could be just removed, which solve the case, no ?

**Comment by thomaspiller** [comment]
In some simple cases, the SDK is not used for embedding MapX.
