### ISSUE TITLE
Mobile devices: panel resizing options are not 100% operational

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#650]
On a mobile device, the button used to modify the size of the panels (full circle) cannot be used. Once the button is selected, movements made with the finger are not taken into account.

The other options that are triggered by clicking work fine.

![image](https://user-images.githubusercontent.com/19908801/106728137-75fba980-660c-11eb-91e2-4bc64a23e775.png)

**Comment by fxi** [comment]
Which platform should we support ? Tablets, small devices ? Apple watch ? 😄 

MapX is not really touch-ready, but if that is a requirement, we can list targeted devices sizes and I will update events system and media queries to be more usable on touch devices. 

If tablets are a real use cases for admins and base users, this could implies low level changes.

**Comment by thomaspiller** [comment]
Although I think this does not represent a high number of MapX users, I think we should target "moderate" support for tablets and smartphones.
