### ISSUE TITLE
GEMET integration for keywords management in MapX

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#651]
Before starting the developments, here are some ideas to explore to assess the feasibility of integrating GEMET into MapX:
- web services: [https://www.eionet.europa.eu/gemet/en/webservices/](https://www.eionet.europa.eu/gemet/en/webservices/)
- deploy an instance of GEMET API in our stack: [https://github.com/eea/gemet](https://github.com/eea/gemet)
- integration of GEMET thesaurus into the MapX database. Data sources:
   - RDF / SKOS: [https://www.eionet.europa.eu/gemet/en/exports/rdf/latest](https://www.eionet.europa.eu/gemet/en/exports/rdf/latest)
   - SQL _(TBC)_: [https://hub.docker.com/r/eeacms/gemet](https://hub.docker.com/r/eeacms/gemet)

**Comment by PierreLacroix** [comment]
I like the approach presented at https://app.mapx.org?project=MX-AKP-01B-JK4-LY8-WME&views=MX-MFH5V-25MFD-DV2U3&viewsOpen=MX-MFH5V-25MFD-DV2U3&language=en&

**Comment by fxi** [comment]
@PierreLacroix in addition to this link, here is a quick screen capture of the widget featured in the view linked : 
![mx_gemet_search_box](https://user-images.githubusercontent.com/1196833/120327788-6d7d5c00-c2ea-11eb-98b2-60952f632c20.gif)

The request is done currently on `https://www.eionet.europa.eu` directly and feed a selectize input. 

-> I think we can use this option. Endpoint should be added as `GEMET_SEARCH_ENDPOINT` variable in our env file, e.g.

`GEMET_SEARCH_ENDPOINT=https://www.eionet.europa.eu/gemet/getConceptsMatchingRegexByThesaurus`

**Comment by thomaspiller** [comment]
GEMET keywords have been added to the MapX metadata form and are now available in the prod version of MapX.
