### ISSUE TITLE
Update MapX Terms of Use

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#652]
MapX Terms of Use should be updated with the UNGIS disclaimer dating from 2020.

**Comment by fxi** [comment]
As this could have grown huge, it was stored in the DB.

We have two solutions:

1) Let super-admin edit this in the UI, as it's transversal to the app. I will have to add a modal with an ace-editor + language support + title

2) Update as a patch:

You can PR a patch named '1.8.7_ungis_disclaimer_2020.sql' in `/api/modules/migrate/sql_patches`.

I guess JSON strings/html should be properly escaped.

Something like :

```sql
UPDATE mx_config SET data =
'[
  {
    "title": {
      "en": "< string >",
      "fr": "",
      "bn": "",
      "de": "",
      "es": "",
      "ar": "",
      "fa": "",
      "ps": "",
      "ru": "",
      "zh": ""
    },
    "content": {
      "en": "< html >",
      "bn": "",
      "de": "",
      "es": "",
      "ar": "",
      "fa": "",
      "fr": "",
      "ps": "",
      "ru": "",
      "zh": "" 
}
]'
WHERE key = 'about'
```

I don't remember why this was stored in an.. array ?¿

**Comment by antobenve** [comment]
I have prepared this version and tested positively in a local instance. I can make the change in the db directly if accepted. French will need to be deleted from db or updated if someone translates the following lines.

`'"\n <ol>\n <li> The boundaries and names shown and the designations used on this map do not imply official endorsement or acceptance by the United Nations.</li>\n <li> The designations employed and the presentation of material on this map do not imply the expression of any opinion whatsoever on the part of the Secretariat of the United Nations concerning the legal status of any country, territory, city or area or of its authorities, or concerning the delimitation of its frontiers or boundaries.</li>\n <li> Dotted line represents approximately the Line of Control in Jammu and Kashmir agreed upon by India and Pakistan. The final status of Jammu and Kashmir has not yet been agreed upon by the parties.</li>\n <li> Final boundary between the Republic of Sudan and the Republic of South Sudan has not yet been determined.</li>\n <li> Final status of the Abyei area is not yet determined.</li>\n <li> A dispute exists between the Governments of Argentina and the United Kingdom of Great Britain and Northern Ireland concerning sovereignty over the Falkland Islands (Malvinas).</li>\n </ol>\n"'`

**Comment by antobenve** [comment]
I think we could also improve the MapX disclaimer by adding all terms that were prepared in the past years, although we have never got a final review of them (but many people contributed and checked it at different steps). The complete document contains the following parts: 
- disclaimer (the one that you read above);
- limitation of liability;
- terms of use;
- confidential information;
- cookies
If you accept to use it we could imagine to edit the table by adding a row per each part and use the part name in the column "title". In this case, the first row should change its value for "title" from 'about' to 'Disclaimer' etc....
I don't know how this could be best shown in MapX but I was thinking about showing the "titles" as collapsed fields that, if expanded, reveals the content of "data".

**Comment by fxi** [comment]
French version : 
```html
<ol>
  <li>
    Les limites et les noms indiqués et les désignations utilisées sur cette
    carte n'impliquent aucune approbation ou acceptation officielle par les
    Nations Unies.
  </li>
  <li>
    Les désignations utilisées et la présentation de matériel sur cette carte
    n'implique l'expression d'aucune opinion de la part du Secrétariat des
    Nations Unies concernant le statut juridique d'un pays, territoire, ville ou
    région ou de ses autorités, ou concernant la délimitation de ses frontières
    ou frontières.
  </li>
  <li>
    La ligne pointillée représente approximativement la ligne de contrôle au
    Jammu-et-Cachemire convenue par l’Inde et le Pakistan. Le statut final du
    Jammu-et-Cachemire n’a pas encore été convenu par les parties.
  </li>
  <li>
    La frontière définitive entre la République du Soudan et la République du
    Soudan du Sud n’a pas encore été déterminée.
  </li>
  <li>Le statut final de la région d'Abyei n'est pas encore déterminé.</li>
  <li>
    Il existe un différend entre les gouvernements de l'Argentine et du
    Royaume-Uni de Grande-Bretagne et d'Irlande du Nord concernant la
    souveraineté sur les îles Falkland (Malvinas ).
  </li>
</ol>
```

**Comment by antobenve** [comment]
Thanks for the translation. Should I do the update now of the disclaimer and we leave the discussion as a next step?

**Comment by fxi** [comment]
I think that this should maybe be decided outside the github repository, as it's unrelated to the code : MapX as software – an empty shell – should be decoupled from the live instance MapX on the mapx.org domain, which holds the data and represents the identity of an organization. 
But for any technical issue, I'm glad to explain how to do it or do something to make it happen.

**Comment by antobenve** [comment]
OK. I'm going to do the update of mx_config with the disclaimer part as it was prepared by us and leave the rest out. 
Ok for discussing about the rest in another environment although here would be easy to follow up (we could tag it as "non-code related"  issue in case)

**Comment by antobenve** [comment]
I'm closing the issue as the disclaimer is updated.
