### ISSUE TITLE
Group the option buttons in a panel

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#655]
The options buttons available on the right of the application should be grouped in a panel to prevent them from being hidden by a dashboard.
This will also harmonize the way in which users will interact with the different elements of MapX e.g. data catalog, notifications and dashboard.

**Comment by antobenve** [comment]
what do you mean with the option buttons?

**Comment by thomaspiller** [comment]
![image](https://user-images.githubusercontent.com/19908801/107786987-d1394480-6d4e-11eb-94c4-ce860d5ad2ba.png)

**Comment by antobenve** [comment]
Ah ok, I was thinking about them, but you said to the left. :) Good idea btw.

**Comment by thomaspiller** [comment]
Sorry, I just updated the issue.
