### ISSUE TITLE
Improve the visibility of panel resizing options

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#656]
To improve the visibility of these options, they could be displayed for a few seconds when opening a panel and then gently masked by reducing the opacity.

**Comment by thomaspiller** [comment]
@fxi I don't see this new display option in the staging stack. Could you check that everything is ok please? Thanks.

**Comment by fxi** [comment]
Not pushed yet. I had to change a bit how panels work and it will be included in the next version. 
However, here is a preview - with poor framerate.
![mx_hint_resize_handle_delay](https://user-images.githubusercontent.com/1196833/108819482-309f1c00-75bb-11eb-9187-06bb46152489.gif)

**Comment by thomaspiller** [comment]
I just tested this new feature on version 1.8.11-beta. Looks great. Thanks!
