### ISSUE TITLE
Dashboard is not closed after login event

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#657]
If the guest user opens a view with dashboard and, while the view is on, he logs-in, the views in panel are reloaded with "toggle option: off" but the dashboard stays on. This causes the dashboard to remain visible until the page is reloaded and generates errors when clicking on map.

The dashboard should close when the view's panel is reloaded.

**Comment by antobenve** [comment]
Tested using this view: [Sierra Leone](https://app.mapx.org?project=MX-YBJ-YYF-08R-UUR-QW6&viewsOpen=MX-5B50G-DD57I-HJHWL&language=en&)

**Comment by fxi** [comment]
Does it happen in staging too ?
Does this occur with all dashboards or just this one ? e.g. If you create a view with a dashboard and a single widget,  then log out, open the view and re-log in ?

**Comment by antobenve** [comment]
Let me try

**Comment by antobenve** [comment]
> Does it happen in staging too ?

Yes, tested using the same view
> Does this occur with all dashboards or just this one ? e.g. If you create a view with a dashboard and a single widget, then log out, open the view and re-log in ?

Yes, I tried on another one and then on a brand new dashboard and the result is the same.

**Comment by fxi** [comment]
Thanks. 
That's pretty basic stuff, it should not happen. 
I will look at this issue soon : there is a lot of priority 1.

**Comment by antobenve** [comment]
Yes, if fixing it doesn't require too much time, I think it is wise to do it before addressing the non-bug issues.

**Comment by thomaspiller** [comment]
I just tested the patch on the staging stack and this problem is resolved. @antobenve You can close this issue if it's also good on your side. Thanks!

**Comment by antobenve** [comment]
Sure.
