### ISSUE TITLE
Download of raster layers should be enabled again in views panel for raster views

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#658]
Since the integration of the metadata template in raster and custom code views, the download icon in the views' panel disappeared for the rt and cc views that were modified through the interface.
In fact, the modification process cleans "data" in mx_views and removes the field that previously hosted the link to download the layer and the one that points to the external page where metadata were stored. 

As the link was moved to the field Source>sources during the migration process, the download functionality from the panel should be enabled again using the first link in the fields source>urls in the metadata template of the views.

The download from metadata page is still possible of course, but it is not straightforward.

**Comment by thomaspiller** [comment]
Multiple urls can be set in the metadata in `origin -> source -> urls`. Currently, only the first link is open when clicking on the download button. Would it be possible to open them all at once (one panel that lists all links)?

**Comment by thomaspiller** [comment]
In case an invalid URL is provided in the metadata in `origin -> source -> urls`, an error is displayed in the console: `Error: Not a valid URL:`

This example generates the error:
```
{
  "homepage": {
    "url": "https://explorer.naturemap.earth/map"
  },
  "source": {
    "urls": [
      {
        "is_download_link": false,
        "url": ""
      }
    ]
  }
}
```

Unfortunately, nothing is displayed in the MapX interface if this error is generated. Perhaps a panel should be displayed in the UI to inform the user that something went wrong.

**Comment by antobenve** [comment]
I suggest the link with tag `"is_download_link": true` should be used by default.

If no link has the above tag, all links in `source `could be shown to the user, which could open them by clicking on them instead of on `Confirm`. This will avoid open all links everytime there is more than one.

 -> Open for discussion

**Comment by antobenve** [comment]
I'm closing this issue as the improvement of the tool is moved to #736
