### ISSUE TITLE
Maki sprites are not displayed in legends

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#659]
When maki symbols are used in a vector view style, the legend environment does not show them as the svg could not be obtained. The legend show no symbol, which make the data difficult to read.

`GET https://app.mapx.org/sprites/svg/maki-square-stroked-15.svg 404`

**Comment by thomaspiller** [comment]
I was able to reproduce the problem encountered by @antobenve by editing the style of vector views.

**Comment by thomaspiller** [comment]
Fixed in version 1.8.30-alpha.

**Comment by thomaspiller** [comment]
Problem solved, the fix is available in the prod version of MapX
