### ISSUE TITLE
Not receiving login code at my email address

### ISSUE THREAD

**Issue by Svensl** [unep-grid/map-x-mgl#669]
Issuance of the login code has been quite slow lately.
Today, I tried twice and have not received any code through email yet. I am at 10+ minutes now.

**Comment by thomaspiller** [comment]
@Svensl Thanks for reporting this issue.

I tried to log into MapX a few times using my professional and personal email accounts and received the login code in a few seconds. If I remember well, this problem had already been reported by @MarionPlanque in the past and our investigations had shown that it was specific to `@un` email addresses.

@MarionPlanque could you please confirm that? Did you find a solution at the time?

**Comment by Svensl** [comment]
Ok thanks for the info and sorry for the bother.
Still nothing on my side though and the MapX limit is 20 minutes so I effectively can't log on.
But will wait and try another time as the problem is likely on the UN Exchange server. Will let you know if the issue persists.

**Comment by thomaspiller** [comment]
Hi @Svensl, have you encountered this problem lately? If not, can I close this issue?
Many thanks!

**Comment by Svensl** [comment]
Hi @thomaspiller. I have not encountered this issue again. I guess the latency was on UNEP MS Exchange server and not MapX. Please close this issue. Thanks for your unwavering support!
