### ISSUE TITLE
Feature request: add a button that disable animations in a story map

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#67]
### Expected Behavior

When one is in a story map, a button allows to disable the animations between the slides.
It is then only possible to navigate in the story map with the arrow keys or by clicking on the slide numbers at the bottom of the screen.

**Comment by thomaspiller** [comment]
Is it still relevant with all the improvements that have been made to the story maps engine? @MarionPlanque @antobenve What do you think?

**Comment by MarionPlanque** [comment]
I don't think it's relevant anymore indeed
