### ISSUE TITLE
Vector tiles views - style: Reverse displayed layers order is active even if untoggled

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#671]
In case of overlapping features, the stack of layers on map should follow the order of rules in the style configuration module unless the "Reverse displayed layers order" is active.
This works when the view is previewed from the style manager.
However, when the view is activated from the views' panel it seems that the stack is reversed.

Example: https://app.mapx.org?project=MX-R2F-467-2PL-J9H-CCR&views=MX-D1K4D-4XWXH-10U9W&viewsOpen=MX-D1K4D-4XWXH-10U9W&viewsListFlatMode=true&language=en&

**Comment by fxi** [comment]
Thanks.

Seems to be an issue during the view saving step, as the layers are correctly rendered if we add the view manually : 

```js
const h = mx.helpers;
(async ()=>{
    const v = await h.getViewRemote('MX-D1K4D-4XWXH-10U9W');
    v.data.style.reverseLayer = true;
    const done = await h.viewsListAddSingle(v);
})()
```

![image](https://user-images.githubusercontent.com/1196833/111643262-1eea1680-87ff-11eb-9ea7-8d2d60433e82.png)

In any case, overlapping polygons in the same layer is considered as a topology error by ... all GIS software.  Normally, you would either substract, combine or build a new entity based on overlapping areas.

**Comment by antobenve** [comment]
I managed to narrow the problem.

- I think that the Reverse mode works as it is supposed to.

- Moreover, it seems that the order of rules in the style editor has an influence on the superposition of features on map. 

> However, and that's the problem, the order of features on map when the view is previewed or saved from the style configuration module is reversed to that when the view is later activated from the panel.

I think that the correct order is generated when the view is displayed in the preview mode (features responding to top rules are displayed at the top of the sandwich) while the order of features when the view is later activated is reversed (features responding to top rules are displayed at the bottom and viceversa).

**Comment by antobenve** [comment]
If it can help further:
If a layer is used in story maps in 2 consecutive steps, the order of features on map is inversed from one step to the next one.
See this example:
https://app.mapx.org/static.html?views=MX-DSOKO-SEI3N-8PSJ4&zoomToViews=true&language=en&
Steps 14 to 15

**Comment by fxi** [comment]
Thanks.
Well, that's quite embarrassing... 

https://github.com/unep-grid/map-x-mgl/blob/c9b15d1ea2a1682f41fa281ae95821d215c3c288/app/src/js/mx_helper_map.js#L4359-L4361

The reverse method mutate the array and, as it's stored in a view, the view itself.

It should be something like
```js
layers = [...layers].reverse()
```

**Comment by antobenve** [comment]
Glad you found the cause and you can correct it accordingly. :)

**Comment by fxi** [comment]
I was wrong... Layers are not stored in views, they are generated each time.. So, this need to be investigating. 
The best way to solve this for now is to correct the topology to avoid overlaps for now. I will not be able to handle this for a while.

**Comment by antobenve** [comment]
Ok.

**Comment by antobenve** [comment]
@fxi, I have additional insights on this issue. I think I haven't realized it before and I hope it would help you understanding the problem and correct it.

- The order of features of a view (A) on map is reversed even when another view (B) is toggled on/off.

Thus, to resume, the order of features in a view A is reversed when:

- a view A is active on map and another view B is switched ON or OFF ([evidence: try these 2 views](https://app.mapx.org?project=MX-R2F-467-2PL-J9H-CCR&views=MX-AYUEA-8SVBA-5KEVS,MX-ZNRPT-FF8OG-CK5UA&viewsOpen=MX-AYUEA-8SVBA-5KEVS,MX-ZNRPT-FF8OG-CK5UA&viewsListFlatMode=true&language=en&)).
- a view A is previewed (from style module), then the style is saved and the same view A is displayed on map without using the style module ([evidence](https://app.mapx.org?project=MX-R2F-467-2PL-J9H-CCR&views=MX-AYUEA-8SVBA-5KEVS&viewsOpen=MX-AYUEA-8SVBA-5KEVS&language=en&viewsListFlatMode=true)).
- a view A is used in consecutive steps in a story map (in this case the order is reversed when changing step).  ([evidence: steps 1 to 3](https://app.mapx.org?project=MX-R2F-467-2PL-J9H-CCR&views=MX-DZLY3-Z7KXR-2I26K&viewsOpen=MX-DZLY3-Z7KXR-2I26K&language=en&))

**Comment by thomaspiller** [comment]
Problem solved, the fix is available in the prod version of MapX
