### ISSUE TITLE
Categories are not displayed in a private project in case the user logs in during the project loading phase

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#672]
If a private project is open as an unlogged user, the user is requested to login through the interface before the project could load. If the user succeeds: the project opens, the views load but the categories in the panel are not displayed.
This is solved when the page is refreshed.

The categories should be loaded even if a log-in process occurs during the project loading phase.

**Comment by fxi** [comment]
This should be solved in `^1.9.35-alpha.1`

**Comment by thomaspiller** [comment]
According to my tests, this problem is fixed.

**Comment by fxi** [comment]
The issue I've seen was far worse than described, where app project was decoupled from the client's views list, after an alternate login process ( access to private projects )

**Comment by antobenve** [comment]
I confirm it is fixed in staging in ^1.9.35-alpha.1
