### ISSUE TITLE
Update administrative boundaries base layer using UN_0 2020

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#688]
MapX's base map should use the new UN_0 map dating late 2020 for administrative boundaries and country labels.
The UN map map also (partly) covers the subnational administrative boundaries at level 1. MapX should employ it at the place of the current data source.
The layer to be used for labels has been already generated (it is available in ownCloud and through an email dating 29/01/2021) and the rules for the style of the labels were updated in the style attached to the same email. 

**Level 0**
- [ ] generate tileset for level 0 using UN_0 2020 
- [ ] change source of layer in MapX style
- [ ] check if style rules still apply

**Level 1** 
- [ ] generate tileset for level 1 using UN_0 2020
- [ ] change source of layer in MapX style
- [ ] check if style rules still apply

**Labels at level 0** 
- [ ] generate tileset using file in email (29/01/2021)
- [ ] change source of layer in MapX style
- [ ] use the MapX style file attached in email to update style rules related to labels.

**Comment by thomaspiller** [comment]
This update was made by @fxi in early July. The 2020 version of UNMap is now used in MapX basemap.
