### ISSUE TITLE
How to manage a version missmatch between MapX and the sdk?

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#710]
The version of the MapX application and of the sdk may be different in case of update. We should study the technical solutions available to either automatically notify the developers that the versions are different (email?) or develop an automatic update system for the sdk.

**Comment by fxi** [comment]
The SDK will complain if its version is not compatible : 
<img src="https://user-images.githubusercontent.com/1196833/125651014-65960117-6f6f-4fd4-98a7-c88d34ec3f9e.png">
https://github.com/unep-grid/map-x-mgl/issues/670#issuecomment-880000815
-> The dev should handle the messages using the simple event system. E.g
```js
m.on('message', (msg) => {
  switch (msg.level) {
    case 'log':
      return console.log(msg.text);
    case 'message':
      return console.info(msg.text);
    case 'warning':
      return console.warn(msg.text);
    case 'error':
      return console.error(msg.text);
    default:
      consol.log('unhandler msg', msg);
  }
});
```
Maybe the doc is not that clear.

Other ways  : 
– Fetch the resolvers from the worker, at start. 
– Publish the sdk as a bundle that could be downloaded from the worker instance. E.g.
```html
 <script type="text/javascript"  src="https://app.mapx.org/sdk.js"></script>
```

**Comment by fxi** [comment]
So, starting from version 1.9.3, the latest SDK library is available directly from the main app's assets.
e.g. https://app.staging.mapx.org/sdk/mxsdk.umd.js
It's part of the build process and no mismatch should be expected. However, if the client's code do not match the latest SDK code, issues could be expected. But backward compatibility will always be a top priority of the SDK. 
Working jsfiddle example: 
https://jsfiddle.net/fxi/tc8km7zg/  
Please comment on this 😄

**Comment by trepmag** [comment]
Yes, I think it's fair to propose this and it will serve developers who require the sdk inline using the html `<script src="...">` tag.

For those who are in the module import realm, then version mismatch might happens sooner or later. But, without necessarily a compatibility issue as long as there is no hiccup btw mapx sdk and it's instance...

Perhaps there is a way to remotely load a module at runtime :scream: but don't have experience with that...

**Comment by fxi** [comment]
`<script type="module">` ?

**Comment by trepmag** [comment]
Was thinking of module include of this form: `import { stuff } from 'modules/amodule.js';`...

**Comment by fxi** [comment]
As this is a "priority 1", and two solutions are currently available, it could be great to wrap this up quickly : close this issue or offer another idea.

The two solutions currently available are : 

1) The module indicates a version mismatch as a warning in the console –  warnings that are now part of the `verbose` option.
2) An UMD  is now always available from the host at https://<host>/sdk/mxsdk.umd.js

On top of that, the UMD contains only the "manager" part of the SDK : all resolvers – aka MapX's methods – are provided by the "worker", which means they are always up to date. Backward compatibility should be ensured. Deprecated method will be marked as such is the future.

@thomaspiller @PierreLacroix : you are also invited to comment

**Comment by trepmag** [comment]
Closing since the available solutions mentioned above are more than reasonable; thank you for this!

**Comment by thomaspiller** [comment]
@trepmag  I reopen this issue as the fix has not yet been published in prod. I just updated its status in the "Short-term tasks" project.
