### ISSUE TITLE
Zoom to all features does not work correctly for views generated by the overlap tool

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#730]
This is due to `null` values in `extent_sp` in the source summary ([example](https://api.staging.mapx.org/get/source/summary/?idView=MX-WTAAA-SZZ7S-C4TSM&idSource=mx_vector_mcabb_ibpej_sllld_ue3nm&idAttr=id&useCache=true&binsMethod=jenks&binsNumber=5&stats=base%2Cattributes%2Ctemporal%2Cspatial&timestamp=2021-09-02T09%3A00%3A25.670Z)):
```
extent_sp": {
"lat1": null,
"lng1": null,
"lat2": null,
"lng2": null
}
```

**Comment by fxi** [comment]
The problem is linked to missing `ANALYZE` statement after recent import of a new layer :  `ST_EstimatedExtent` requires that to read the stats.
