### ISSUE TITLE
Improve the way source links are used by the "Download tool" of raster and custom code views

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#736]
Since the use of metadata form in raster and custom code views, the download button of these views cannot uniquely use a specific link for the download of the resource. 

- [ ] Define a strategy to improve the way the app uses the available information in the metadata fields. 

    Suggestion:
    - List links from "source>urls" field in a module and let the user click on each URL to execute it.
      Fallback strategy;
      1) Only show links with "is_download_link=true" if there are any.
      2) If no links with "is_download_link=true" is available -> show all links from "sources".
      3) If no link is in "sources" -> The resource cannot be downloaded.
    
    Less appealing option:
    - Directly execute the first link from "sources" that have the tag "is_download_link=true".

- [ ] Let the user know that an error occurred when executing an invalid URL.

**Comment by antobenve** [comment]
#658

**Comment by fxi** [comment]
-> the `is_download_link` is here to tell an automated script that it could expect a dataset ( tiff, erdas imagine, ) and not a web page. For a use via the UI, when a user clicks, it does not really change anything, so I would not show or hide a link in ui based on this.

**Comment by antobenve** [comment]
We can list all links, obviously. The suggestion was to reduce the information that is shown to the user after he clicks the "download" button as many links can be present under "sources>urls".

**Comment by antobenve** [comment]
This should be fixed withe next release.
