### ISSUE TITLE
Mini bug style configuration module - categorical data

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#748]
When using categorical data, the rule value "All" does not exclude the value defined in "Missing values".
This results in double styles for the feature tagged as missing value.

**Comment by thomaspiller** [comment]
I just tested the fix on staging and the style editor works fine now. Thanks!

**Comment by antobenve** [comment]
It does work. Thanks.
I just discovered a related issue which could be fixed in the frame of this issue:
- feaures with missing values are not excluded from the map if the legend is filtered based on the value "all". 
See exemple [here](https://app.staging.mapx.org?project=MX-J8V-G2L-4Y3-O6Z-Z0B&views=MX-Q5W6Z-6MPZ3-68ZVG&viewsOpen=MX-Q5W6Z-6MPZ3-68ZVG&language=en&).
This only happens if the value "all" is used for the class that is clicked. In case a value is specified, clicking on it would exclude all the other features (including those with missing values) from the map.
