### ISSUE TITLE
Set dashboard visibility in views

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#758]
It would be useful to have a method to set the visibility of a dashboard when a view is activated. SDK offers a [method ](https://github.com/unep-grid/map-x-mgl/tree/master/app/src/js/sdk#MapxResolversStatic+set_dashboard_visibility) which could be used as basis potentially. 
A discussion is open in order to find if this is possible and what are its limits.

If possible, the method or methods should suits the following purposes:
- [x] definition of the default appearence of the dashboard by the publisher 
In the dashboard configuration module we could add the value "Collapsed" under the "Initial dashboard layout" options.

- [x] use of view in story map 
The publisher of the story map might want to overwrite the default appearance and set it to collapsed or expanded in each different step of the story where the view is displayed.

- [x] use of view in iframe through URL parameters 
The user that creates the URL might want the dashboard to be visible or collapsed indipendently from its default status.

**Comment by thomaspiller** [comment]
Regarding the dashboards, I would add another option that seems essential: a button to activate or not the display of the dashboard in MapX. This would make it possible to keep the code of an obsolete dashboard or whose display must be temporarily hidden without having to duplicate views or go through other hacks.

In the dashboard edit panel, the following options would then be available:
- Checkbox: display the dashboard in MapX
- Dropdown list: default dashboard size
    1. Vertical
    2. Horizontal
    3. Fit largest widget
    4. Collapsed/minimized
