### ISSUE TITLE
View metadata panel improvements 

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#762]
- [x] The `div` containing the chart is not resized when the size of the metadata panel is changed.
- [x] The code of the chart should be modified to:
  1. remove credits:
        ```js
        credits: {
        enabled: false
        }
       ```
  2. modify the export options:
      ```js
     exporting: {
       buttons: {
         contextButton: {
           menuItems: [
             'printChart',
             'separator',
             'downloadPNG',
             'downloadJPEG',
             'downloadSVG',
             'separator',
             'downloadCSV',
             'downloadXLS'
           ]
         }
       }
     }
      ```
- [x] `Number of activations by distinct registered users` is not so clear to me. Wouldn't it rather be: `Number of distinct registered users who activated the view` ?

**Comment by fxi** [comment]
Thanks!

I think I will remove this graph. Pie charts are hard to read, it take a huge amount of space / can't be scrolled and with more than 10 countries, it's a mess. It will be a simple ordered table, an handsontable, a barplot or a lollipop plot:

![image](https://user-images.githubusercontent.com/1196833/140704062-f86d4fd9-73b5-4d16-9611-7b1eac903fdb.png)

**Comment by thomaspiller** [comment]
+1 for changing the type of chart
