### ISSUE TITLE
Error when using the map composer on temporary views

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#765]
The following error is received in console if the map composer is launched and a temporary view is active due to missing style information.
`Cannot set properties of undefined (setting 'style')
`
I propose a solution is put in place to allow the use of the map composer on custom geometries to users that cannot publish new layers in projects. 
I have the feeling this was possible and was changed at a certain time, thus I guess it could be easy to fix, but I'm not sure about it.

In alternative, inform the user the tool cannot be used with temporary views on map.

**Comment by fxi** [comment]
I'm not sure to understand this issue and your proposition is confusing to me.

I tried on the staging server:
- Search tool > add "Mogadishu urban extent 2001" > click map composer > export  ✅ 
- Search tool > add  "Haiti Roads (Open Street Map, 2018)" > click map compose > export ✅ 

Could you add steps to reproduce this issue ? thanks

**Comment by antobenve** [comment]
With the term "temporary views" I meant the views that are characterized by the orange circle and that are created by these processes before these are uploaded into the db;
1) by the use of the tool to draw new geometries on map and 
2) by a drag and drop of a geospatial layer on map.

**Comment by fxi** [comment]
Those are GeoJSON views. They are not temporary. If you reload the page, they will be there. 

Temporary views have have a link logo:
![image](https://user-images.githubusercontent.com/1196833/141121066-14f1f65c-9d5c-439b-a1aa-40c9968c49b6.png)

So, I'm able to reproduce this : 
1) Create a point layer with the drawing tool
2) Add a point, save, close
3) Click the map composer = error in console

Two options : 

- Don't allow using the map composer with non styled view, such as GeoJSON views
- Add a feature to set basic style for GeoJSON views, such as size, and base color ( now it's random : not so good to be printed )

@thomaspiller you can also add your thoughts on this

**Comment by antobenve** [comment]
Do you remember if this has ever been possible before? I had the feeling it was and that's also why I have suggested MapX could allow the use of the map composer on GeoJSON views.
Btw, I'm in for option 2 if this is fast to develop, otherwise 3 is perfectly fine to me.

**Comment by thomaspiller** [comment]
I'm also in favor of option 2.
