### ISSUE TITLE
Assigning the EPSG code when uploading a layer using Toolbox fails when using the available tool

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#771]
"Toolbox" > "Upload a new source layer" > "Find EPSG code" > enter key > "Search" > click on resulting EPSG > Error in console `Cannot read properties of null (reading 'dataset')`

**Comment by thomaspiller** [comment]
There must have been a problem with the data provider because it is working again.

**Comment by antobenve** [comment]
I still have the issue. 
To make it clear, the issue occurs when I click on the EPSG that I want to use after this was provided to me through the search.

**Comment by fxi** [comment]
Please check the latest version `1.9.5-alpha.3`, this should be fixed.

**Comment by antobenve** [comment]
Yes. Fixed. Thanks.
