### ISSUE TITLE
Missing translations & typos [end 2021 update]

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#775]
_This issue is an update of #327_

### Edit style
- [x] change "opacity" to "transparency" to be consistent with the rest of the application

###  Area intersection tools
- [x] _select analysis_ section is not translated
 
###  Manage sources
- [x] pop-up title: Edit source -> Gérer la source / Editar la fuente de datos
 
### Search engine API
- [x] all terms in the panel

### Map composer
- [x] all terms in the module

### Draw tool
- [x] missing entry for `draw_feature_type`

### Story maps engine
- [x] slide -> In Spanish should be "Diapositiva"
- [x] slide classes (card, text-right ....)
- [x] in edition mode: all tooltips are not translated

### Attribut table
- [x] clear filter
- [x] export CSV

### Other remarks
- [x] ~texts accompanying the progress bars are not translated~ Will be refactored
- [x] ~logs are not translated~
- [x] lack of consistency between the terms Configure and Edit e.g. the "Configure view" button becomes "Edit view (in the header).

**Comment by fxi** [comment]
No clear : 

in edition mode: all tooltips are not translated. Which tooltips ?
progress bars are not translated: Progress bars do not contain text : modules that use them do. 
logs are not translated : Logs should not be translated...

**Comment by thomaspiller** [comment]
> in edition mode: all tooltips are not translated. Which tooltips ?

It's been a while since this issue was opened so I'm not 100% sure. From what I see, in preview mode, the tooltips of this panel are not translated but it is most likely independent of the MapX translation system.

![image](https://user-images.githubusercontent.com/19908801/185868329-9e641a1a-b5e3-456d-8836-7a5cc1d5d92b.png)

**Comment by thomaspiller** [comment]
For the rest, everything seems fine to me. Thanks!

**Comment by fxi** [comment]
> likely independent of the MapX translation system.
Sure it is : https://getcontenttools.com/api/content-edit#translations 
I will do the binding

**Comment by thomaspiller** [comment]
@fxi  Do you plan to add the binding we talked about at the end of August for the next prod version?

**Comment by fxi** [comment]
Missing Bengali and Pashto

<img width="545" alt="image" src="https://user-images.githubusercontent.com/1196833/194248865-9b8bee39-20b8-4638-bd73-f230ffe8346c.png">
