### ISSUE TITLE
Views catalog not properly loaded when opening private project as guest user

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#785]
##### Problem description:
When a private project is opened from a direct URL as un unlogged user, the content of the views' catalog is not loaded properly (HOME content is kept).

A refresh solves the problem. Opening the same project as a logged user doesn't cause the problem.

##### Error in console:
[ Edit by @fxi ]
Unrelated error reported in another issue, as agreed 

##### How to reproduce
[Edit @fxi for clarity ]

1. Open a private project link as guest
2. The default project is loaded correctly
3. A modal is shown, requesting the user to log in for the private project
4. Log in 
5. The private project is loaded, but the views list is the default one [ race condition issue ? ] instead of the project's list.
6. Reload to solve this

##### Tested on: 
Browsers: Chrome v.97 (up to date)
OS: Windows 10 + MAC - not experienced in Linux

**Comment by fxi** [comment]
> private project is opened from a direct URL 
The content of a private project should not be accessible to unlogged user, right ? 

So, If I read between the line, the "how to reproduce" seems incomplete. I suspect it to be something like:

1) Open a private project link as guest
2) The default project is loaded correctly
3) A modal is shown, requesting the user to log in
4) Log in
5) The project is still the default one

I can't test that right now

**Comment by antobenve** [comment]
No @fxi , your assumption is false because the private project is finally properly loaded except for the content of its catalog. All the other tools indicate the private project was loaded correctly (roles, properties, sources in "manage sources").

Thus, a private project is loaded after a successful login but its views are not loaded.

**Comment by fxi** [comment]
Should be solved by #6fe72

**Comment by thomaspiller** [comment]
According to my tests, this problem is fixed. @antobenve do you confirm?

**Comment by antobenve** [comment]
Seems so to me too.
