### ISSUE TITLE
SDK + CommonLoc : Accepts Array of M49 + ISO codes

### ISSUE THREAD

**Issue by fxi** [unep-grid/map-x-mgl#786]
For now, it's only possible to use CommonLoc / SDK to zoom on a single country or region.

In some use cases, some regions are not requested, some are not exactly the same as the M49 ones.

The client that uses the CommonLoc module should be able to create his own groups and feed them in CommonLoc, which  should create a bounding box of all items and return the final extent then zoom or fitBounds on that. 

Ex. of custom groups : 

```json
{
   "North Africa + South Europe + Turkmenistan" : ["m49_015","m49_039", "TKM"],
}

```

**Comment by antobenve** [comment]
I'm closing the issue as it is corrected in prod.
