### ISSUE TITLE
Map composer: map elements are not exported sharply on some displays

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#797]
The following images were taken using the map composer tool and show map elements too rough compared to the other elements.

DPI set in map composer: 300
Device pixel ratio: 1 (first three figures) - 1.25 (the last figure)
Display resolution: 1900x1080
Browser: Chrome (98.0.4758.81 (Official Build) (64-bit))

![map-composer-export (23)](https://user-images.githubusercontent.com/30286565/152825998-631ff98e-e80d-467f-bdf3-98af36bb61f7.png)
![map-composer-export (22)](https://user-images.githubusercontent.com/30286565/152826023-fbfb7ddf-0275-47dc-860e-76de79655e2d.png)
![map-composer-export (21)](https://user-images.githubusercontent.com/30286565/152826052-6a06f0be-c2f4-4319-bbab-7b1d6f8b2ff2.png)
![map-composer-export (24)](https://user-images.githubusercontent.com/30286565/152826108-8e5dd81c-540f-4eec-826a-6eea55d26a4b.png)

**Comment by fxi** [comment]
Yep, with a base DPR of 2, when the map composer is set to  300mmx300mm @ 300dpi, the DPR is temporarily changed to 3.125 for the "map composer" map. You should have a DPR similar to that, event with a base DPR of 1. 

With a base DPR of 2, the result is ok

![map-composer-export (36)](https://user-images.githubusercontent.com/1196833/152827977-e00da4f6-2569-4cf2-847e-85467cc6da42.png)

**Comment by fxi** [comment]
I can't reproduce this. It renders as expected

PNG diff from 300x300mm @ 300dpi  MapComposer output using two screens with different DPR and two browsers. 

Right 3072 × 1920, DPR 3.125; Left 3840 × 2160 DPR 1 ( for people with raptor eyesight )

---

Chrome 98.0 MacOS 11.6

### Text

<img width="530" alt="image" src="https://user-images.githubusercontent.com/1196833/153178036-57b0f3aa-dcf5-410c-b7d3-2eebbe4ae225.png">

### Map

<img width="629" alt="image" src="https://user-images.githubusercontent.com/1196833/153179165-66723aec-d8a9-4691-9afe-179826394031.png">

### Legends

<img width="830" alt="image" src="https://user-images.githubusercontent.com/1196833/153179319-0eb15577-b73a-4696-9580-cd06af19cb6b.png">

---

Firefox 96.0.3 MacOS 11.6

### Text

<img width="800" alt="image" src="https://user-images.githubusercontent.com/1196833/153181931-27490642-72be-4ffc-abc2-916192153804.png">

### Map

<img width="858" alt="image" src="https://user-images.githubusercontent.com/1196833/153182045-edbfca85-86f5-420f-b0c3-b0fe73c266df.png">

**Comment by fxi** [comment]
It should be solved in 1.9.39-alpha.8
Huge image for testing :
![map-composer-export (80)](https://user-images.githubusercontent.com/1196833/153284246-d6f87376-dea7-44e1-bfc1-c92e11033167.png)

**Comment by thomaspiller** [comment]
I did some export from the map composer and everything was sharp.

**Comment by antobenve** [comment]
I'm closing the issue as it is corrected in prod.
