### ISSUE TITLE
Editing attributes of vector sources from MapX

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#811]
Development of a new tool in the toolbox (e.g. `Edit attributes table`) to:
1. add/delete columns
2. modify cell content (attributes)

Editing geometries is not considered as it is complex to set up. This may come in a future iteration of the tool.

Editing rights of the attribute tables should be linked to the `Groups with write access` option of the `Edit source settings` tool.

**Comment by fxi** [comment]
As attribute table editions can collide if multiple users perform operation simultaneously, I propose a system of auto save + change propagation using websocket + sub/pub Redis, to mitigate issues. The same system could apply to other module, like vt style, source metadata, etc..  

- Authentication system ( already active for geoserver + source layers download / crop / reprojection )
- Auto save in postgres
- Changes propagation among a pool of users, through redis + websocket
- Undo / Redo handled by the table module

A first draft of this idea, if two users launch an edition session on the same table. Green arrows symbolize an edit : add column, remove line ( and geometry ), update cell, etc..  

![mx-table-sync](https://user-images.githubusercontent.com/1196833/177998942-81d0ba9a-0c05-4763-a47c-4066aad13cbe.png)

**Comment by thomaspiller** [comment]
After internal discussions, here is a list of some additional specs:
- enable blur mode (as for metadata) when the tool is open
- message/warning explaining to users that the edits are directly saved in the database and that there are undo/redo buttons if needed
- padlock to (un)lock the edition of the attributes table to avoid making unwanted modifications (e.g. the user makes filters to analyze the table before modification) [recommended]

**Comment by antobenve** [comment]
Hello, we have identified the following points to improve/fix:
# Bug:
- [ ] The list of sources available in the drop down list is not complete (i.e. big difference between list of sources in "edit sources metadata" vs "edit source attributes table" (check https://app.staging.mapx.org/?project=MX-R2F-467-2PL-J9H-CCR&language=en))
# Improvements:
- [ ] Improve how to list sources (YES date & NO abstract as in "edit metadata" tool + chose source from a list of views like in the overlap tool)
- [ ] Improve user experience when adding a column with a name that already exists -> Add a text that explains why it can't be created. "A column with this name exists already".
- [ ] Handle when clicking "Undo" if the operation was done on a column that was meanwhile deleted by another user (Error in console + nothing happens on tool) -> Remove actions to be undo from log if these concern the deleted column or find an alternative to inform user about the behavior of the button in this situation.

Additional points/improvements will be discussed and defined later on.
