### ISSUE TITLE
GeoServer client : > 2.18, layers not updated after publishing a view

### ISSUE THREAD

**Issue by fxi** [unep-grid/map-x-mgl#812]
To check on testing/local version.

both 
`> 2.18.0`
and 
`> 2.20.0`

version seem to produce the same issue : the layer list is not updated after a view change, even for a public view in a public project. 

When updating workspace manually, an error is returned : 

```error
Caractères invalides dans \"MX-0A4-7LY-1Z3-TNN-XGL@gs_ws_a\". Commencez avec une lettre suivie de lettres, nombres ou .-_
```

Nothing in logs, but this should be verified again.

@thomaspiller @antobenve

**Comment by thomaspiller** [comment]
Is this issue still relevant now that GeoServer has been migrated to Node.JS and there have been changes in the logic for publishing views from MapX to GeoServer?

**Comment by fxi** [comment]
Not relevant anymore
