### ISSUE TITLE
Rename the Republic of Turkey in MapX

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#835]
The Republic of Turkey has been renamed to Republic of Türkiye.
Turkey has been renamed to Türkiye.

Consequently, the basemap and the countries dictionary in MapX should be updated.

Translations in UN languages:

Language | Short name | Formal name
-- | -- | --
English | Türkiye | Republic of Türkiye
French | Türkiye | République de Türkiye
Spanish | Türkiye | República de Türkiye

Russian, Chinese and Arabic translations are not available yet.

**Comment by thomaspiller** [comment]
Available on staging. The fix has been tested and MapX works fine.
This fix will be deployed in production in mid-June.

**Comment by thomaspiller** [comment]
Russian, Chinese and Arabic translations are now available on UNSTAT: https://unstats.un.org/unsd/methodology/m49/

**Comment by fxi** [comment]
@thomaspiller I think there are no differences for those language, compared to the current version

**Comment by thomaspiller** [comment]
You are right.
