### ISSUE TITLE
Modification of the aerial mode tooltip

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#847]
In the menu bar, there are two buttons whose tooltip refers to "Switch theme".
To avoid confusion, it would be better to change "Switch theme : aerial" to "Aerial mode".

**Comment by fxi** [comment]
I've changed to "Add an aerial imagery layer", so it match the "Add 3D terrain", next to it. 

<img width="294" alt="image" src="https://user-images.githubusercontent.com/1196833/179466751-a601a772-7077-43cb-9a2c-36f1971672dc.png">
<img width="347" alt="image" src="https://user-images.githubusercontent.com/1196833/179466792-4e08cd90-94e2-4f8c-a111-a723d28703f2.png">
