### ISSUE TITLE
Get temporary access to edit a dataset -> to be removed

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#856]
As 
1) the tool relies on temporary connections that in some cases cannot be properly handled by third parties (see QGIS), 
2) the new tool to edit attribute tables almost completely replace its purpose and 
3) editing a table with both the tools at the same time can give rise to conflicts

-> we propose to remove the functionality from Toolbox.

**Comment by PierreLacroix** [comment]
Agreed
