### ISSUE TITLE
GeoJSON polygon rendering is unreliable

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#859]
GeoJSON polygon rendering is unreliable (see [issue reported to Mapbox ](https://github.com/mapbox/mapbox-gl-js/issues/7023)) and could affect data visualization in MapX. As no solution is proposed at this time, an investigation on our side is necessary. Generating vector tiles from `PostGIS` is a solution worth exploring.

**Comment by fxi** [comment]
A fix is available on the staging branch. 

- Use PostGIS to generate tiles ( seems slower, but.. probably more accurate : to be tested )
- Geometry correction : new tool to crop geometries outside 180/-180 90/-90 + better validation 
- Faster cached tiles rendering 

Still in alpha. 

The geometry correction ( 90 / -90 ... ), should be done in PostGIS, in the `asMVTgeom` function, but it's not, so it should be done manually. For now.

**Comment by antobenve** [comment]
I tested the tool briefly and I remarked a relevant performance decrease which should be taken into account and evaluated more properly during our tests.
