### ISSUE TITLE
SDK's manager parameter url.host fails over https

### ISSUE THREAD

**Issue by trepmag** [unep-grid/map-x-mgl#865]
When over https, instantiating the sdk manager as follow will make the browser complains that an insecure frame was requested:
```js
const mapx = new mxsdk.Manager({
  container: document.getElementById('mapx'),
  url: {
    host: 'app.mapx.org',
  },
  static: true,
  verbose: true,
  params: {
    closePanels: true,
    views: ['MX-Z741Z-HA4JJ-OGV29'],
    language: 'fr'
  }
});
```

The above chunk was copy/pasted from https://github.com/unep-grid/map-x-mgl/tree/main/app/src/js/sdk#html-inline.

Error:
```
Mixed Content: The page at 'https://codepen.io/trepmag/pen/ExREMxZ' was loaded over HTTPS, but requested an insecure frame 'http://app.mapx.org/static.html?closePanels=true&views=MX-Z741Z-HA4JJ-OGV29&language=fr&sdkToken=0.h82rr7gig78'. This request has been blocked; the content must be served over HTTPS.
```

Although, using `{...url: 'https://app.mapx.org',...}` will work...

Example: https://codepen.io/trepmag/pen/ExREMxZ

**Comment by fxi** [comment]
Thanks.

It should be...

```json
...
 url: {
    protocol : "https",
    host: "app.mapx.org",
    port: 443
  },
...
```
But I agree that could be simplified...  The redirection `http->https` is handled by `traefik`. Same for the port. 
I will check this.
If it's a high priority, please add the corresponding label. e.g. `priority 1` or drop this in the short-term task project, has you have edition rights on this repo :)

**Comment by trepmag** [comment]
Not high priority from my point of view... Maybe just update sdk's README.md in a next push...
