### ISSUE TITLE
Generation of SLD in MapX and publication of view to GeoServer

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#871]
- [x] Depending on views, the SLD viewable in the MapX UI differs from the one published in GeoServer. In MapX, the `<sld:Name>`  tag in each style rule contains the name/label of the rule while in GeoServer it does not.
      Example ([view](https://app.mapx.org/?language=en&project=MX-R2F-467-2PL-J9H-CCR&viewsListFlatMode=false&viewsOpen=MX-ZNRPT-FF8OG-CK5UA%2CMX-3MRV2-03XOM-HK8LW&viewsListFilterActivated=true&p=0&b=0&z=3.922&lat=43.373&lng=4.238&t3d=false&sat=false&theme=water_light)):
      - MapX: `<Name>6.4 - 16.15</Name>`
      - GeoServer: `<sld:Name>MX-3MRV2-03XOM-HK8LW@Fhl0z</sld:Name>`

- [x] Views with a custom style are not published on the MapX GeoServer. If an SLD cannot be generated for a view, the default style available in GeoServer should be used.

- [x] The style rule for missing/null values is not present in the SLD. Is this due to a technical limitation or could we add it in a future version of MapX?

**Comment by fxi** [comment]
In the view you provided, the rule name is also wrong. Can I assume that it's the case everywhere or there are cases when name of the rule is correct ?

```xml 
<StyledLayerDescriptor version="1.0.0" xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd" xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <NamedLayer>
    <Name>Carbon dioxide emissions per energy use 2016 (MSSD Indicator 21)</Name>
    <UserStyle>
      <Name>Carbon dioxide emissions per energy use 2016 (MSSD Indicator 21)</Name>
      <Title>Carbon dioxide emissions per energy use 2016 (MSSD Indicator 21)</Title>
      <FeatureTypeStyle>
        <Rule>
          <Name>MX-ZNRPT-FF8OG-CK5UA@0__custom</Name>

```

**Comment by thomaspiller** [comment]
I have published in MapX GeoServer all public views of the [WESR: Mediterranean](https://app.mapx.org/?project=MX-R2F-467-2PL-J9H-CCR&language=en&theme=water_light) project. In all, there are about sixty styles that have been created in GeoServer. About half have a problem with the name of the rules.
