### ISSUE TITLE
Add library references used in a dashboard

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#877]
- [x] add a footer in the panel button
- [x] check which modules have been loaded inspecting the use of `moduleLoad()` and feed the footer accordingly

**Comment by fxi** [comment]
This is available in  1.10.0-alpha.3 ( to be tested )

<img width="577" alt="image" src="https://user-images.githubusercontent.com/1196833/211570277-c0298751-d36e-499d-924b-4090d21b46c2.png">
