### ISSUE TITLE
Improve list of sources in the tools inputs

### ISSUE THREAD

**Issue by thomaspiller** [unep-grid/map-x-mgl#881]
- [x] List view(s) associated to each source in the input of the `Edit source settings` and `Edit source metadata` tools.
      Implementation could be similar to what was developed for the `Edit vector source` tool.

  ![image](https://user-images.githubusercontent.com/19908801/213415742-2d05f656-6727-4f10-a07a-5bd1ac5b773e.png)

- [x] Add `HH:MM` to the date associated to each source

**Comment by fxi** [comment]
<img width="791" alt="image" src="https://user-images.githubusercontent.com/1196833/215825026-bd9323a9-efab-4f34-9c62-2cd42b0b4450.png">
