### ISSUE TITLE
Copy values from one column in Edit Vector Source has a limit of 1000 rows

### ISSUE THREAD

**Issue by antobenve** [unep-grid/map-x-mgl#893]
When editing a vector source, if a user selects the whole content of a column and wants to copy it manually, only the first 1000 rows are copied.

**Comment by fxi** [comment]
Not a bug, it's a settings in:
https://handsontable.com/docs/6.1.0/CopyPaste.html#rowsLimit
How much should we allow ?

**Comment by antobenve** [comment]
In my opinion we should allow the copy of the totality of the rows because we have stated that users can edit the attribute tables copy-pasting data from and to Excel in case they need to calculate new values based on existing values.

**Comment by antobenve** [comment]
Fixed
