### ISSUE TITLE
Option to add more homepage, source, rang and Issuance

### ISSUE THREAD

**Issue by alejandraarango** [unep-grid/map-x-mgl#93]
### Expected Behavior
Have the option to add more homepage, source, rang and Issuance. In case a layer have two sources as the CAMI – ITIE data.

**Comment by antobenve** [comment]
This issue was partly addressed with the possibility to add more sources, and more licensing. However, more homepages are still not possible (it is relevant if more sources can be added), and the same is for range and issuance.

**Comment by antobenve** [comment]
The issue will be closed because the item is reported in the list of improvements of issue #447
